//
// AddDomainConfig200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddDomainConfig200Response: Sendable, Codable, JSONEncodable, Hashable {

    public var reason: String
    public var code: String
    public var status: JSONValue?
    public var configuration: JSONValue?

    public init(reason: String, code: String, status: JSONValue?, configuration: JSONValue?) {
        self.reason = reason
        self.code = code
        self.status = status
        self.configuration = configuration
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reason
        case code
        case status
        case configuration
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(reason, forKey: .reason)
        try container.encode(code, forKey: .code)
        try container.encode(status, forKey: .status)
        try container.encode(configuration, forKey: .configuration)
    }
}

