//
// AddDomainConfig200ResponseAnyOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddDomainConfig200ResponseAnyOf: Sendable, Codable, JSONEncodable, Hashable {

    public var configuration: JSONValue?
    public var status: JSONValue?

    public init(configuration: JSONValue?, status: JSONValue?) {
        self.configuration = configuration
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case configuration
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(configuration, forKey: .configuration)
        try container.encode(status, forKey: .status)
    }
}

