//
// AdjustCommentVotesParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AdjustCommentVotesParams: Sendable, Codable, Hashable {

    public var adjustVoteAmount: Double

    public init(adjustVoteAmount: Double) {
        self.adjustVoteAmount = adjustVoteAmount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case adjustVoteAmount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(adjustVoteAmount, forKey: .adjustVoteAmount)
    }
}

