//
// AggregateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AggregateResponse: Sendable, Codable, Hashable {

    public var status: APIStatus
    public var data: [AggregationItem]?
    public var stats: AggregationResponseStats?
    public var reason: String?
    public var code: String?
    public var validResourceNames: [String]?

    public init(status: APIStatus, data: [AggregationItem]? = nil, stats: AggregationResponseStats? = nil, reason: String? = nil, code: String? = nil, validResourceNames: [String]? = nil) {
        self.status = status
        self.data = data
        self.stats = stats
        self.reason = reason
        self.code = code
        self.validResourceNames = validResourceNames
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case data
        case stats
        case reason
        case code
        case validResourceNames
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(stats, forKey: .stats)
        try container.encodeIfPresent(reason, forKey: .reason)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(validResourceNames, forKey: .validResourceNames)
    }
}

