//
// AggregationValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AggregationValue: Sendable, Codable, JSONEncodable, Hashable {

    /** Construct a type with a set of properties K of type T */
    public var groups: [String: String]?
    public var stringValue: String?
    public var numericValue: Double?
    public var distinctCount: Int64?
    /** Construct a type with a set of properties K of type T */
    public var distinctCounts: [String: Double]?

    public init(groups: [String: String]? = nil, stringValue: String? = nil, numericValue: Double? = nil, distinctCount: Int64? = nil, distinctCounts: [String: Double]? = nil) {
        self.groups = groups
        self.stringValue = stringValue
        self.numericValue = numericValue
        self.distinctCount = distinctCount
        self.distinctCounts = distinctCounts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case groups
        case stringValue
        case numericValue
        case distinctCount
        case distinctCounts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(groups, forKey: .groups)
        try container.encodeIfPresent(stringValue, forKey: .stringValue)
        try container.encodeIfPresent(numericValue, forKey: .numericValue)
        try container.encodeIfPresent(distinctCount, forKey: .distinctCount)
        try container.encodeIfPresent(distinctCounts, forKey: .distinctCounts)
    }
}

