//
// AggregationAPIError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AggregationAPIError: Sendable, Codable, Hashable {

    public var status: APIStatus
    public var reason: String
    public var code: String
    public var validResourceNames: [String]?

    public init(status: APIStatus, reason: String, code: String, validResourceNames: [String]? = nil) {
        self.status = status
        self.reason = reason
        self.code = code
        self.validResourceNames = validResourceNames
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case reason
        case code
        case validResourceNames
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(reason, forKey: .reason)
        try container.encode(code, forKey: .code)
        try container.encodeIfPresent(validResourceNames, forKey: .validResourceNames)
    }
}

