//
// AggregationOpType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The supported aggregation operation types */
public enum AggregationOpType: String, Sendable, Codable, CaseIterable {
    case sum = "sum"
    case countdistinct = "countDistinct"
    case distinct = "distinct"
    case avg = "avg"
    case min = "min"
    case max = "max"
    case count = "count"
}
