//
// AggregationItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AggregationItem: Sendable, Codable, JSONEncodable, Hashable {

    /** Construct a type with a set of properties K of type T */
    public var groups: [String: String]?

    public init(groups: [String: String]? = nil) {
        self.groups = groups
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case groups
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(groups, forKey: .groups)
    }
}

