//
// AggregationResponseStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AggregationResponseStats: Sendable, Codable, JSONEncodable, Hashable {

    public var timeMS: Int64
    public var scanned: Int64

    public init(timeMS: Int64, scanned: Int64) {
        self.timeMS = timeMS
        self.scanned = scanned
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case timeMS
        case scanned
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(timeMS, forKey: .timeMS)
        try container.encode(scanned, forKey: .scanned)
    }
}

