//
// AggregationRequestSort.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AggregationRequestSort: Sendable, Codable, JSONEncodable, Hashable {

    public enum Dir: String, Sendable, Codable, CaseIterable {
        case asc = "asc"
        case desc = "desc"
    }
    public var dir: Dir
    public var field: String

    public init(dir: Dir, field: String) {
        self.dir = dir
        self.field = field
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dir
        case field
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(dir, forKey: .dir)
        try container.encode(field, forKey: .field)
    }
}

