//
// AggregateQuestionResultsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AggregateQuestionResultsResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var data: QuestionResultAggregationOverall

    public init(status: APIStatus, data: QuestionResultAggregationOverall) {
        self.status = status
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(data, forKey: .data)
    }
}

