//
// AggregateTimeBucket.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum AggregateTimeBucket: String, Sendable, Codable, CaseIterable {
    case day = "day"
    case month = "month"
    case year = "year"
}
