//
// AggregationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The API response returns the aggregated data along with simple stats */
public struct AggregationResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var data: [AggregationItem]
    public var stats: AggregationResponseStats?

    public init(status: APIStatus, data: [AggregationItem], stats: AggregationResponseStats? = nil) {
        self.status = status
        self.data = data
        self.stats = stats
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case data
        case stats
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(data, forKey: .data)
        try container.encodeIfPresent(stats, forKey: .stats)
    }
}

