//
// AggregationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The aggregation request accepts a resource, optional grouping keys, an array of operations, and an optional sort */
public struct AggregationRequest: Sendable, Codable, JSONEncodable, Hashable {

    public var query: [QueryPredicate]?
    public var resourceName: String
    public var groupBy: [String]?
    public var operations: [AggregationOperation]
    public var sort: AggregationRequestSort?

    public init(query: [QueryPredicate]? = nil, resourceName: String, groupBy: [String]? = nil, operations: [AggregationOperation], sort: AggregationRequestSort? = nil) {
        self.query = query
        self.resourceName = resourceName
        self.groupBy = groupBy
        self.operations = operations
        self.sort = sort
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case query
        case resourceName
        case groupBy
        case operations
        case sort
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(query, forKey: .query)
        try container.encode(resourceName, forKey: .resourceName)
        try container.encodeIfPresent(groupBy, forKey: .groupBy)
        try container.encode(operations, forKey: .operations)
        try container.encodeIfPresent(sort, forKey: .sort)
    }
}

