//
// AggregationOperation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** An operation that will be applied on a field */
public struct AggregationOperation: Sendable, Codable, JSONEncodable, Hashable {

    /** The field to operate on */
    public var field: String
    public var op: AggregationOpType
    /** Optional alias for the output; if not provided, a default alias is computed */
    public var alias: String?
    public var expandArray: Bool?

    public init(field: String, op: AggregationOpType, alias: String? = nil, expandArray: Bool? = nil) {
        self.field = field
        self.op = op
        self.alias = alias
        self.expandArray = expandArray
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case field
        case op
        case alias
        case expandArray
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(field, forKey: .field)
        try container.encode(op, forKey: .op)
        try container.encodeIfPresent(alias, forKey: .alias)
        try container.encodeIfPresent(expandArray, forKey: .expandArray)
    }
}

