//
// APIAuditLog.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct APIAuditLog: Sendable, Codable, JSONEncodable, Hashable {

    public enum CrudType: String, Sendable, Codable, CaseIterable {
        case c = "c"
        case r = "r"
        case u = "u"
        case d = "d"
        case login = "login"
    }
    public enum From: String, Sendable, Codable, CaseIterable {
        case ui = "ui"
        case api = "api"
        case cron = "cron"
    }
    public var id: String
    public var userId: String?
    public var username: String?
    public var resourceName: String
    public var crudType: CrudType
    public var from: From?
    public var url: String?
    public var ip: String?
    public var when: Date?
    public var description: String?
    public var serverStartDate: Date?
    /** Construct a type with a set of properties K of type T */
    public var objectDetails: [String: JSONValue]?

    public init(id: String, userId: String? = nil, username: String? = nil, resourceName: String, crudType: CrudType, from: From? = nil, url: String? = nil, ip: String? = nil, when: Date? = nil, description: String? = nil, serverStartDate: Date? = nil, objectDetails: [String: JSONValue]? = nil) {
        self.id = id
        self.userId = userId
        self.username = username
        self.resourceName = resourceName
        self.crudType = crudType
        self.from = from
        self.url = url
        self.ip = ip
        self.when = when
        self.description = description
        self.serverStartDate = serverStartDate
        self.objectDetails = objectDetails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case userId
        case username
        case resourceName
        case crudType
        case from
        case url
        case ip
        case when
        case description
        case serverStartDate
        case objectDetails
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(username, forKey: .username)
        try container.encode(resourceName, forKey: .resourceName)
        try container.encode(crudType, forKey: .crudType)
        try container.encodeIfPresent(from, forKey: .from)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(ip, forKey: .ip)
        try container.encodeIfPresent(when, forKey: .when)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(serverStartDate, forKey: .serverStartDate)
        try container.encodeIfPresent(objectDetails, forKey: .objectDetails)
    }
}

