//
// APIBanUserChangeLog.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct APIBanUserChangeLog: Sendable, Codable, Hashable {

    public var createdBannedUserId: String?
    public var updatedBannedUserId: String?
    public var deletedBannedUsers: [APIBannedUser]?
    public var changedValuesBefore: APIBanUserChangedValues?

    public init(createdBannedUserId: String? = nil, updatedBannedUserId: String? = nil, deletedBannedUsers: [APIBannedUser]? = nil, changedValuesBefore: APIBanUserChangedValues? = nil) {
        self.createdBannedUserId = createdBannedUserId
        self.updatedBannedUserId = updatedBannedUserId
        self.deletedBannedUsers = deletedBannedUsers
        self.changedValuesBefore = changedValuesBefore
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdBannedUserId
        case updatedBannedUserId
        case deletedBannedUsers
        case changedValuesBefore
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(createdBannedUserId, forKey: .createdBannedUserId)
        try container.encodeIfPresent(updatedBannedUserId, forKey: .updatedBannedUserId)
        try container.encodeIfPresent(deletedBannedUsers, forKey: .deletedBannedUsers)
        try container.encodeIfPresent(changedValuesBefore, forKey: .changedValuesBefore)
    }
}

