//
// APIBanUserChangedValues.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct APIBanUserChangedValues: Sendable, Codable, Hashable {

    public var id: String?
    public var tenantId: String?
    public var userId: String?
    public var email: String?
    public var username: String?
    public var ipHash: String?
    public var createdAt: Date?
    public var bannedByUserId: String?
    public var bannedCommentText: String?
    public var banType: String?
    public var bannedUntil: Date?
    public var hasEmailWildcard: Bool?
    public var banReason: String?

    public init(id: String? = nil, tenantId: String? = nil, userId: String? = nil, email: String? = nil, username: String? = nil, ipHash: String? = nil, createdAt: Date? = nil, bannedByUserId: String? = nil, bannedCommentText: String? = nil, banType: String? = nil, bannedUntil: Date? = nil, hasEmailWildcard: Bool? = nil, banReason: String? = nil) {
        self.id = id
        self.tenantId = tenantId
        self.userId = userId
        self.email = email
        self.username = username
        self.ipHash = ipHash
        self.createdAt = createdAt
        self.bannedByUserId = bannedByUserId
        self.bannedCommentText = bannedCommentText
        self.banType = banType
        self.bannedUntil = bannedUntil
        self.hasEmailWildcard = hasEmailWildcard
        self.banReason = banReason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case tenantId
        case userId
        case email
        case username
        case ipHash
        case createdAt
        case bannedByUserId
        case bannedCommentText
        case banType
        case bannedUntil
        case hasEmailWildcard
        case banReason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(tenantId, forKey: .tenantId)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(username, forKey: .username)
        try container.encodeIfPresent(ipHash, forKey: .ipHash)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(bannedByUserId, forKey: .bannedByUserId)
        try container.encodeIfPresent(bannedCommentText, forKey: .bannedCommentText)
        try container.encodeIfPresent(banType, forKey: .banType)
        try container.encodeIfPresent(bannedUntil, forKey: .bannedUntil)
        try container.encodeIfPresent(hasEmailWildcard, forKey: .hasEmailWildcard)
        try container.encodeIfPresent(banReason, forKey: .banReason)
    }
}

