//
// APICreateUserBadgeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct APICreateUserBadgeResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var userBadge: UserBadge

    public init(status: APIStatus, userBadge: UserBadge) {
        self.status = status
        self.userBadge = userBadge
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case userBadge
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(userBadge, forKey: .userBadge)
    }
}

