//
// APICommentBase.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct APICommentBase: Sendable, Codable, JSONEncodable, Hashable {

    public var id: String
    public var aiDeterminedSpam: Bool?
    public var anonUserId: String?
    public var approved: Bool
    public var avatarSrc: String?
    public var badges: [CommentUserBadgeInfo]?
    public var comment: String
    public var commentHTML: String
    public var commenterEmail: String?
    public var commenterLink: String?
    public var commenterName: String
    public var date: Date?
    public var displayLabel: String?
    public var domain: String?
    public var externalId: String?
    public var externalParentId: String?
    public var expireAt: Date?
    public var feedbackIds: [String]?
    public var flagCount: Int?
    public var fromProductId: Int?
    public var hasCode: Bool?
    public var hasImages: Bool?
    public var hasLinks: Bool?
    public var hashTags: [CommentUserHashTagInfo]?
    public var isByAdmin: Bool?
    public var isByModerator: Bool?
    public var isDeleted: Bool?
    public var isDeletedUser: Bool?
    public var isPinned: Bool?
    public var isLocked: Bool?
    public var isSpam: Bool?
    public var localDateHours: Int?
    public var localDateString: String?
    public var locale: String?
    public var mentions: [CommentUserMentionInfo]?
    public var meta: FCommentMeta?
    public var moderationGroupIds: [String]?
    public var notificationSentForParent: Bool?
    public var notificationSentForParentTenant: Bool?
    public var pageTitle: String?
    public var parentId: String?
    public var rating: Double?
    public var reviewed: Bool?
    public var tenantId: String
    public var url: String
    public var urlId: String
    public var urlIdRaw: String?
    public var userId: String?
    public var verified: Bool
    public var verifiedDate: Date?
    public var votes: Int?
    public var votesDown: Int?
    public var votesUp: Int?

    public init(id: String, aiDeterminedSpam: Bool? = nil, anonUserId: String? = nil, approved: Bool, avatarSrc: String? = nil, badges: [CommentUserBadgeInfo]? = nil, comment: String, commentHTML: String, commenterEmail: String? = nil, commenterLink: String? = nil, commenterName: String, date: Date?, displayLabel: String? = nil, domain: String? = nil, externalId: String? = nil, externalParentId: String? = nil, expireAt: Date? = nil, feedbackIds: [String]? = nil, flagCount: Int? = nil, fromProductId: Int? = nil, hasCode: Bool? = nil, hasImages: Bool? = nil, hasLinks: Bool? = nil, hashTags: [CommentUserHashTagInfo]? = nil, isByAdmin: Bool? = nil, isByModerator: Bool? = nil, isDeleted: Bool? = nil, isDeletedUser: Bool? = nil, isPinned: Bool? = nil, isLocked: Bool? = nil, isSpam: Bool? = nil, localDateHours: Int? = nil, localDateString: String? = nil, locale: String?, mentions: [CommentUserMentionInfo]? = nil, meta: FCommentMeta? = nil, moderationGroupIds: [String]? = nil, notificationSentForParent: Bool? = nil, notificationSentForParentTenant: Bool? = nil, pageTitle: String? = nil, parentId: String? = nil, rating: Double? = nil, reviewed: Bool? = nil, tenantId: String, url: String, urlId: String, urlIdRaw: String? = nil, userId: String? = nil, verified: Bool, verifiedDate: Date? = nil, votes: Int? = nil, votesDown: Int? = nil, votesUp: Int? = nil) {
        self.id = id
        self.aiDeterminedSpam = aiDeterminedSpam
        self.anonUserId = anonUserId
        self.approved = approved
        self.avatarSrc = avatarSrc
        self.badges = badges
        self.comment = comment
        self.commentHTML = commentHTML
        self.commenterEmail = commenterEmail
        self.commenterLink = commenterLink
        self.commenterName = commenterName
        self.date = date
        self.displayLabel = displayLabel
        self.domain = domain
        self.externalId = externalId
        self.externalParentId = externalParentId
        self.expireAt = expireAt
        self.feedbackIds = feedbackIds
        self.flagCount = flagCount
        self.fromProductId = fromProductId
        self.hasCode = hasCode
        self.hasImages = hasImages
        self.hasLinks = hasLinks
        self.hashTags = hashTags
        self.isByAdmin = isByAdmin
        self.isByModerator = isByModerator
        self.isDeleted = isDeleted
        self.isDeletedUser = isDeletedUser
        self.isPinned = isPinned
        self.isLocked = isLocked
        self.isSpam = isSpam
        self.localDateHours = localDateHours
        self.localDateString = localDateString
        self.locale = locale
        self.mentions = mentions
        self.meta = meta
        self.moderationGroupIds = moderationGroupIds
        self.notificationSentForParent = notificationSentForParent
        self.notificationSentForParentTenant = notificationSentForParentTenant
        self.pageTitle = pageTitle
        self.parentId = parentId
        self.rating = rating
        self.reviewed = reviewed
        self.tenantId = tenantId
        self.url = url
        self.urlId = urlId
        self.urlIdRaw = urlIdRaw
        self.userId = userId
        self.verified = verified
        self.verifiedDate = verifiedDate
        self.votes = votes
        self.votesDown = votesDown
        self.votesUp = votesUp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case aiDeterminedSpam
        case anonUserId
        case approved
        case avatarSrc
        case badges
        case comment
        case commentHTML
        case commenterEmail
        case commenterLink
        case commenterName
        case date
        case displayLabel
        case domain
        case externalId
        case externalParentId
        case expireAt
        case feedbackIds
        case flagCount
        case fromProductId
        case hasCode
        case hasImages
        case hasLinks
        case hashTags
        case isByAdmin
        case isByModerator
        case isDeleted
        case isDeletedUser
        case isPinned
        case isLocked
        case isSpam
        case localDateHours
        case localDateString
        case locale
        case mentions
        case meta
        case moderationGroupIds
        case notificationSentForParent
        case notificationSentForParentTenant
        case pageTitle
        case parentId
        case rating
        case reviewed
        case tenantId
        case url
        case urlId
        case urlIdRaw
        case userId
        case verified
        case verifiedDate
        case votes
        case votesDown
        case votesUp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(aiDeterminedSpam, forKey: .aiDeterminedSpam)
        try container.encodeIfPresent(anonUserId, forKey: .anonUserId)
        try container.encode(approved, forKey: .approved)
        try container.encodeIfPresent(avatarSrc, forKey: .avatarSrc)
        try container.encodeIfPresent(badges, forKey: .badges)
        try container.encode(comment, forKey: .comment)
        try container.encode(commentHTML, forKey: .commentHTML)
        try container.encodeIfPresent(commenterEmail, forKey: .commenterEmail)
        try container.encodeIfPresent(commenterLink, forKey: .commenterLink)
        try container.encode(commenterName, forKey: .commenterName)
        try container.encode(date, forKey: .date)
        try container.encodeIfPresent(displayLabel, forKey: .displayLabel)
        try container.encodeIfPresent(domain, forKey: .domain)
        try container.encodeIfPresent(externalId, forKey: .externalId)
        try container.encodeIfPresent(externalParentId, forKey: .externalParentId)
        try container.encodeIfPresent(expireAt, forKey: .expireAt)
        try container.encodeIfPresent(feedbackIds, forKey: .feedbackIds)
        try container.encodeIfPresent(flagCount, forKey: .flagCount)
        try container.encodeIfPresent(fromProductId, forKey: .fromProductId)
        try container.encodeIfPresent(hasCode, forKey: .hasCode)
        try container.encodeIfPresent(hasImages, forKey: .hasImages)
        try container.encodeIfPresent(hasLinks, forKey: .hasLinks)
        try container.encodeIfPresent(hashTags, forKey: .hashTags)
        try container.encodeIfPresent(isByAdmin, forKey: .isByAdmin)
        try container.encodeIfPresent(isByModerator, forKey: .isByModerator)
        try container.encodeIfPresent(isDeleted, forKey: .isDeleted)
        try container.encodeIfPresent(isDeletedUser, forKey: .isDeletedUser)
        try container.encodeIfPresent(isPinned, forKey: .isPinned)
        try container.encodeIfPresent(isLocked, forKey: .isLocked)
        try container.encodeIfPresent(isSpam, forKey: .isSpam)
        try container.encodeIfPresent(localDateHours, forKey: .localDateHours)
        try container.encodeIfPresent(localDateString, forKey: .localDateString)
        try container.encode(locale, forKey: .locale)
        try container.encodeIfPresent(mentions, forKey: .mentions)
        try container.encodeIfPresent(meta, forKey: .meta)
        try container.encodeIfPresent(moderationGroupIds, forKey: .moderationGroupIds)
        try container.encodeIfPresent(notificationSentForParent, forKey: .notificationSentForParent)
        try container.encodeIfPresent(notificationSentForParentTenant, forKey: .notificationSentForParentTenant)
        try container.encodeIfPresent(pageTitle, forKey: .pageTitle)
        try container.encodeIfPresent(parentId, forKey: .parentId)
        try container.encodeIfPresent(rating, forKey: .rating)
        try container.encodeIfPresent(reviewed, forKey: .reviewed)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(url, forKey: .url)
        try container.encode(urlId, forKey: .urlId)
        try container.encodeIfPresent(urlIdRaw, forKey: .urlIdRaw)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encode(verified, forKey: .verified)
        try container.encodeIfPresent(verifiedDate, forKey: .verifiedDate)
        try container.encodeIfPresent(votes, forKey: .votes)
        try container.encodeIfPresent(votesDown, forKey: .votesDown)
        try container.encodeIfPresent(votesUp, forKey: .votesUp)
    }
}

