//
// APICommentCommonBannedUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct APICommentCommonBannedUser: Sendable, Codable, Hashable {

    public var id: String
    public var userId: String?
    public var banType: String
    public var email: String?
    public var ipHash: String?
    public var bannedUntil: Date?
    public var hasEmailWildcard: Bool
    public var banReason: String?

    public init(id: String, userId: String? = nil, banType: String, email: String? = nil, ipHash: String? = nil, bannedUntil: Date?, hasEmailWildcard: Bool, banReason: String? = nil) {
        self.id = id
        self.userId = userId
        self.banType = banType
        self.email = email
        self.ipHash = ipHash
        self.bannedUntil = bannedUntil
        self.hasEmailWildcard = hasEmailWildcard
        self.banReason = banReason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case userId
        case banType
        case email
        case ipHash
        case bannedUntil
        case hasEmailWildcard
        case banReason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encode(banType, forKey: .banType)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(ipHash, forKey: .ipHash)
        try container.encode(bannedUntil, forKey: .bannedUntil)
        try container.encode(hasEmailWildcard, forKey: .hasEmailWildcard)
        try container.encodeIfPresent(banReason, forKey: .banReason)
    }
}

