//
// APIDomainConfiguration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct APIDomainConfiguration: Sendable, Codable, JSONEncodable, Hashable {

    public var id: String
    public var domain: String
    public var emailFromName: String?
    public var emailFromEmail: String?
    /** Construct a type with a set of properties K of type T */
    public var emailHeaders: [String: String]?
    public var wpSyncToken: String?
    public var wpSynced: Bool?
    public var wpURL: String?
    public var createdAt: Date
    public var autoAddedDate: Date?
    public var siteType: ImportedSiteType?
    public var logoSrc: String?
    public var logoSrc100px: String?
    public var footerUnsubscribeURL: String?
    public var disableUnsubscribeLinks: Bool?

    public init(id: String, domain: String, emailFromName: String? = nil, emailFromEmail: String? = nil, emailHeaders: [String: String]? = nil, wpSyncToken: String? = nil, wpSynced: Bool? = nil, wpURL: String? = nil, createdAt: Date, autoAddedDate: Date? = nil, siteType: ImportedSiteType? = nil, logoSrc: String? = nil, logoSrc100px: String? = nil, footerUnsubscribeURL: String? = nil, disableUnsubscribeLinks: Bool? = nil) {
        self.id = id
        self.domain = domain
        self.emailFromName = emailFromName
        self.emailFromEmail = emailFromEmail
        self.emailHeaders = emailHeaders
        self.wpSyncToken = wpSyncToken
        self.wpSynced = wpSynced
        self.wpURL = wpURL
        self.createdAt = createdAt
        self.autoAddedDate = autoAddedDate
        self.siteType = siteType
        self.logoSrc = logoSrc
        self.logoSrc100px = logoSrc100px
        self.footerUnsubscribeURL = footerUnsubscribeURL
        self.disableUnsubscribeLinks = disableUnsubscribeLinks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case domain
        case emailFromName
        case emailFromEmail
        case emailHeaders
        case wpSyncToken
        case wpSynced
        case wpURL
        case createdAt
        case autoAddedDate
        case siteType
        case logoSrc
        case logoSrc100px
        case footerUnsubscribeURL
        case disableUnsubscribeLinks
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(domain, forKey: .domain)
        try container.encodeIfPresent(emailFromName, forKey: .emailFromName)
        try container.encodeIfPresent(emailFromEmail, forKey: .emailFromEmail)
        try container.encodeIfPresent(emailHeaders, forKey: .emailHeaders)
        try container.encodeIfPresent(wpSyncToken, forKey: .wpSyncToken)
        try container.encodeIfPresent(wpSynced, forKey: .wpSynced)
        try container.encodeIfPresent(wpURL, forKey: .wpURL)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(autoAddedDate, forKey: .autoAddedDate)
        try container.encodeIfPresent(siteType, forKey: .siteType)
        try container.encodeIfPresent(logoSrc, forKey: .logoSrc)
        try container.encodeIfPresent(logoSrc100px, forKey: .logoSrc100px)
        try container.encodeIfPresent(footerUnsubscribeURL, forKey: .footerUnsubscribeURL)
        try container.encodeIfPresent(disableUnsubscribeLinks, forKey: .disableUnsubscribeLinks)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension APIDomainConfiguration: Identifiable {}
