//
// APIGetUserBadgesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct APIGetUserBadgesResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var userBadges: [UserBadge]

    public init(status: APIStatus, userBadges: [UserBadge]) {
        self.status = status
        self.userBadges = userBadges
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case userBadges
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(userBadges, forKey: .userBadges)
    }
}

