//
// APIGetUserBadgeProgressListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct APIGetUserBadgeProgressListResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var userBadgeProgresses: [UserBadgeProgress]

    public init(status: APIStatus, userBadgeProgresses: [UserBadgeProgress]) {
        self.status = status
        self.userBadgeProgresses = userBadgeProgresses
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case userBadgeProgresses
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(userBadgeProgresses, forKey: .userBadgeProgresses)
    }
}

