//
// APIGetUserBadgeProgressResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct APIGetUserBadgeProgressResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var userBadgeProgress: UserBadgeProgress

    public init(status: APIStatus, userBadgeProgress: UserBadgeProgress) {
        self.status = status
        self.userBadgeProgress = userBadgeProgress
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case userBadgeProgress
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(userBadgeProgress, forKey: .userBadgeProgress)
    }
}

