//
// APIGetCommentResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct APIGetCommentResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var comment: APIComment

    public init(status: APIStatus, comment: APIComment) {
        self.status = status
        self.comment = comment
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case comment
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(comment, forKey: .comment)
    }
}

