//
// APIGetCommentsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct APIGetCommentsResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var comments: [APIComment]

    public init(status: APIStatus, comments: [APIComment]) {
        self.status = status
        self.comments = comments
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case comments
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(comments, forKey: .comments)
    }
}

