//
// APIModerateGetUserBanPreferencesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct APIModerateGetUserBanPreferencesResponse: Sendable, Codable, Hashable {

    public var preferences: APIModerateUserBanPreferences?
    public var status: APIStatus

    public init(preferences: APIModerateUserBanPreferences?, status: APIStatus) {
        self.preferences = preferences
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case preferences
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(preferences, forKey: .preferences)
        try container.encode(status, forKey: .status)
    }
}

