//
// APIModerateUserBanPreferences.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct APIModerateUserBanPreferences: Sendable, Codable, Hashable {

    public var shouldBanEmail: Bool
    public var shouldBanByIP: Bool
    public var lastBanType: String
    public var lastBanDuration: String

    public init(shouldBanEmail: Bool, shouldBanByIP: Bool, lastBanType: String, lastBanDuration: String) {
        self.shouldBanEmail = shouldBanEmail
        self.shouldBanByIP = shouldBanByIP
        self.lastBanType = lastBanType
        self.lastBanDuration = lastBanDuration
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case shouldBanEmail
        case shouldBanByIP
        case lastBanType
        case lastBanDuration
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(shouldBanEmail, forKey: .shouldBanEmail)
        try container.encode(shouldBanByIP, forKey: .shouldBanByIP)
        try container.encode(lastBanType, forKey: .lastBanType)
        try container.encode(lastBanDuration, forKey: .lastBanDuration)
    }
}

