//
// APIPage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct APIPage: Sendable, Codable, JSONEncodable, Hashable {

    public var isClosed: Bool?
    public var accessibleByGroupIds: [String]?
    public var rootCommentCount: Int64
    public var commentCount: Int64
    public var createdAt: Date
    public var title: String
    public var url: String?
    public var urlId: String
    public var id: String

    public init(isClosed: Bool? = nil, accessibleByGroupIds: [String]? = nil, rootCommentCount: Int64, commentCount: Int64, createdAt: Date, title: String, url: String? = nil, urlId: String, id: String) {
        self.isClosed = isClosed
        self.accessibleByGroupIds = accessibleByGroupIds
        self.rootCommentCount = rootCommentCount
        self.commentCount = commentCount
        self.createdAt = createdAt
        self.title = title
        self.url = url
        self.urlId = urlId
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isClosed
        case accessibleByGroupIds
        case rootCommentCount
        case commentCount
        case createdAt
        case title
        case url
        case urlId
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isClosed, forKey: .isClosed)
        try container.encodeIfPresent(accessibleByGroupIds, forKey: .accessibleByGroupIds)
        try container.encode(rootCommentCount, forKey: .rootCommentCount)
        try container.encode(commentCount, forKey: .commentCount)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encode(urlId, forKey: .urlId)
        try container.encode(id, forKey: .id)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension APIPage: Identifiable {}
