//
// APIStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum APIStatus: String, Sendable, Codable, CaseIterable {
    case success = "success"
    case failed = "failed"
}
