//
// APISSOUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct APISSOUser: Sendable, Codable, JSONEncodable, Hashable {

    public var id: String
    public var username: String
    public var websiteUrl: String
    public var email: String
    public var signUpDate: Int64
    public var createdFromUrlId: String
    public var loginCount: Int
    public var avatarSrc: String
    public var optedInNotifications: Bool
    public var optedInSubscriptionNotifications: Bool
    public var displayLabel: String
    public var displayName: String
    public var isAccountOwner: Bool?
    public var isAdminAdmin: Bool?
    public var isCommentModeratorAdmin: Bool?
    public var isProfileActivityPrivate: Bool?
    public var isProfileCommentsPrivate: Bool?
    public var isProfileDMDisabled: Bool?
    public var hasBlockedUsers: Bool?
    public var groupIds: [String]?

    public init(id: String, username: String, websiteUrl: String, email: String, signUpDate: Int64, createdFromUrlId: String, loginCount: Int, avatarSrc: String, optedInNotifications: Bool, optedInSubscriptionNotifications: Bool, displayLabel: String, displayName: String, isAccountOwner: Bool? = nil, isAdminAdmin: Bool? = nil, isCommentModeratorAdmin: Bool? = nil, isProfileActivityPrivate: Bool? = nil, isProfileCommentsPrivate: Bool? = nil, isProfileDMDisabled: Bool? = nil, hasBlockedUsers: Bool? = nil, groupIds: [String]? = nil) {
        self.id = id
        self.username = username
        self.websiteUrl = websiteUrl
        self.email = email
        self.signUpDate = signUpDate
        self.createdFromUrlId = createdFromUrlId
        self.loginCount = loginCount
        self.avatarSrc = avatarSrc
        self.optedInNotifications = optedInNotifications
        self.optedInSubscriptionNotifications = optedInSubscriptionNotifications
        self.displayLabel = displayLabel
        self.displayName = displayName
        self.isAccountOwner = isAccountOwner
        self.isAdminAdmin = isAdminAdmin
        self.isCommentModeratorAdmin = isCommentModeratorAdmin
        self.isProfileActivityPrivate = isProfileActivityPrivate
        self.isProfileCommentsPrivate = isProfileCommentsPrivate
        self.isProfileDMDisabled = isProfileDMDisabled
        self.hasBlockedUsers = hasBlockedUsers
        self.groupIds = groupIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case username
        case websiteUrl
        case email
        case signUpDate
        case createdFromUrlId
        case loginCount
        case avatarSrc
        case optedInNotifications
        case optedInSubscriptionNotifications
        case displayLabel
        case displayName
        case isAccountOwner
        case isAdminAdmin
        case isCommentModeratorAdmin
        case isProfileActivityPrivate
        case isProfileCommentsPrivate
        case isProfileDMDisabled
        case hasBlockedUsers
        case groupIds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(username, forKey: .username)
        try container.encode(websiteUrl, forKey: .websiteUrl)
        try container.encode(email, forKey: .email)
        try container.encode(signUpDate, forKey: .signUpDate)
        try container.encode(createdFromUrlId, forKey: .createdFromUrlId)
        try container.encode(loginCount, forKey: .loginCount)
        try container.encode(avatarSrc, forKey: .avatarSrc)
        try container.encode(optedInNotifications, forKey: .optedInNotifications)
        try container.encode(optedInSubscriptionNotifications, forKey: .optedInSubscriptionNotifications)
        try container.encode(displayLabel, forKey: .displayLabel)
        try container.encode(displayName, forKey: .displayName)
        try container.encodeIfPresent(isAccountOwner, forKey: .isAccountOwner)
        try container.encodeIfPresent(isAdminAdmin, forKey: .isAdminAdmin)
        try container.encodeIfPresent(isCommentModeratorAdmin, forKey: .isCommentModeratorAdmin)
        try container.encodeIfPresent(isProfileActivityPrivate, forKey: .isProfileActivityPrivate)
        try container.encodeIfPresent(isProfileCommentsPrivate, forKey: .isProfileCommentsPrivate)
        try container.encodeIfPresent(isProfileDMDisabled, forKey: .isProfileDMDisabled)
        try container.encodeIfPresent(hasBlockedUsers, forKey: .hasBlockedUsers)
        try container.encodeIfPresent(groupIds, forKey: .groupIds)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension APISSOUser: Identifiable {}
