//
// APITicket.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct APITicket: Sendable, Codable, JSONEncodable, Hashable {

    public var id: String
    public var urlId: String
    public var userId: String
    public var managedByTenantId: String
    public var assignedUserIds: [String]
    public var subject: String
    public var createdAt: String
    public var state: Int
    public var fileCount: Int

    public init(id: String, urlId: String, userId: String, managedByTenantId: String, assignedUserIds: [String], subject: String, createdAt: String, state: Int, fileCount: Int) {
        self.id = id
        self.urlId = urlId
        self.userId = userId
        self.managedByTenantId = managedByTenantId
        self.assignedUserIds = assignedUserIds
        self.subject = subject
        self.createdAt = createdAt
        self.state = state
        self.fileCount = fileCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case urlId
        case userId
        case managedByTenantId
        case assignedUserIds
        case subject
        case createdAt
        case state
        case fileCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(urlId, forKey: .urlId)
        try container.encode(userId, forKey: .userId)
        try container.encode(managedByTenantId, forKey: .managedByTenantId)
        try container.encode(assignedUserIds, forKey: .assignedUserIds)
        try container.encode(subject, forKey: .subject)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(state, forKey: .state)
        try container.encode(fileCount, forKey: .fileCount)
    }
}

