//
// APITenant.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct APITenant: Sendable, Codable, JSONEncodable, Hashable {

    public var id: String
    public var name: String
    public var email: String?
    public var signUpDate: Double
    public var packageId: String
    public var paymentFrequency: Double
    public var billingInfoValid: Bool
    public var billingHandledExternally: Bool?
    public var createdBy: String
    public var isSetup: Bool
    public var domainConfiguration: [APIDomainConfiguration]
    public var billingInfo: BillingInfo?
    public var stripeCustomerId: String?
    public var stripeSubscriptionId: String?
    public var stripePlanId: String?
    public var enableProfanityFilter: Bool
    public var enableSpamFilter: Bool
    public var lastBillingIssueReminderDate: Date?
    public var removeUnverifiedComments: Bool?
    public var unverifiedCommentsTTLms: Double?
    public var commentsRequireApproval: Bool?
    public var autoApproveCommentOnVerification: Bool?
    public var sendProfaneToSpam: Bool?
    public var hasFlexPricing: Bool?
    public var hasAuditing: Bool?
    public var flexLastBilledAmount: Double?
    public var deAnonIpAddr: Double?
    /** Construct a type with a set of properties K of type T */
    public var meta: [String: String]?

    public init(id: String, name: String, email: String? = nil, signUpDate: Double, packageId: String, paymentFrequency: Double, billingInfoValid: Bool, billingHandledExternally: Bool? = nil, createdBy: String, isSetup: Bool, domainConfiguration: [APIDomainConfiguration], billingInfo: BillingInfo? = nil, stripeCustomerId: String? = nil, stripeSubscriptionId: String? = nil, stripePlanId: String? = nil, enableProfanityFilter: Bool, enableSpamFilter: Bool, lastBillingIssueReminderDate: Date? = nil, removeUnverifiedComments: Bool? = nil, unverifiedCommentsTTLms: Double? = nil, commentsRequireApproval: Bool? = nil, autoApproveCommentOnVerification: Bool? = nil, sendProfaneToSpam: Bool? = nil, hasFlexPricing: Bool? = nil, hasAuditing: Bool? = nil, flexLastBilledAmount: Double? = nil, deAnonIpAddr: Double? = nil, meta: [String: String]? = nil) {
        self.id = id
        self.name = name
        self.email = email
        self.signUpDate = signUpDate
        self.packageId = packageId
        self.paymentFrequency = paymentFrequency
        self.billingInfoValid = billingInfoValid
        self.billingHandledExternally = billingHandledExternally
        self.createdBy = createdBy
        self.isSetup = isSetup
        self.domainConfiguration = domainConfiguration
        self.billingInfo = billingInfo
        self.stripeCustomerId = stripeCustomerId
        self.stripeSubscriptionId = stripeSubscriptionId
        self.stripePlanId = stripePlanId
        self.enableProfanityFilter = enableProfanityFilter
        self.enableSpamFilter = enableSpamFilter
        self.lastBillingIssueReminderDate = lastBillingIssueReminderDate
        self.removeUnverifiedComments = removeUnverifiedComments
        self.unverifiedCommentsTTLms = unverifiedCommentsTTLms
        self.commentsRequireApproval = commentsRequireApproval
        self.autoApproveCommentOnVerification = autoApproveCommentOnVerification
        self.sendProfaneToSpam = sendProfaneToSpam
        self.hasFlexPricing = hasFlexPricing
        self.hasAuditing = hasAuditing
        self.flexLastBilledAmount = flexLastBilledAmount
        self.deAnonIpAddr = deAnonIpAddr
        self.meta = meta
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case email
        case signUpDate
        case packageId
        case paymentFrequency
        case billingInfoValid
        case billingHandledExternally
        case createdBy
        case isSetup
        case domainConfiguration
        case billingInfo
        case stripeCustomerId
        case stripeSubscriptionId
        case stripePlanId
        case enableProfanityFilter
        case enableSpamFilter
        case lastBillingIssueReminderDate
        case removeUnverifiedComments
        case unverifiedCommentsTTLms
        case commentsRequireApproval
        case autoApproveCommentOnVerification
        case sendProfaneToSpam
        case hasFlexPricing
        case hasAuditing
        case flexLastBilledAmount
        case deAnonIpAddr
        case meta
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encode(signUpDate, forKey: .signUpDate)
        try container.encode(packageId, forKey: .packageId)
        try container.encode(paymentFrequency, forKey: .paymentFrequency)
        try container.encode(billingInfoValid, forKey: .billingInfoValid)
        try container.encodeIfPresent(billingHandledExternally, forKey: .billingHandledExternally)
        try container.encode(createdBy, forKey: .createdBy)
        try container.encode(isSetup, forKey: .isSetup)
        try container.encode(domainConfiguration, forKey: .domainConfiguration)
        try container.encodeIfPresent(billingInfo, forKey: .billingInfo)
        try container.encodeIfPresent(stripeCustomerId, forKey: .stripeCustomerId)
        try container.encodeIfPresent(stripeSubscriptionId, forKey: .stripeSubscriptionId)
        try container.encodeIfPresent(stripePlanId, forKey: .stripePlanId)
        try container.encode(enableProfanityFilter, forKey: .enableProfanityFilter)
        try container.encode(enableSpamFilter, forKey: .enableSpamFilter)
        try container.encodeIfPresent(lastBillingIssueReminderDate, forKey: .lastBillingIssueReminderDate)
        try container.encodeIfPresent(removeUnverifiedComments, forKey: .removeUnverifiedComments)
        try container.encodeIfPresent(unverifiedCommentsTTLms, forKey: .unverifiedCommentsTTLms)
        try container.encodeIfPresent(commentsRequireApproval, forKey: .commentsRequireApproval)
        try container.encodeIfPresent(autoApproveCommentOnVerification, forKey: .autoApproveCommentOnVerification)
        try container.encodeIfPresent(sendProfaneToSpam, forKey: .sendProfaneToSpam)
        try container.encodeIfPresent(hasFlexPricing, forKey: .hasFlexPricing)
        try container.encodeIfPresent(hasAuditing, forKey: .hasAuditing)
        try container.encodeIfPresent(flexLastBilledAmount, forKey: .flexLastBilledAmount)
        try container.encodeIfPresent(deAnonIpAddr, forKey: .deAnonIpAddr)
        try container.encodeIfPresent(meta, forKey: .meta)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension APITenant: Identifiable {}
