//
// APIUserSubscription.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct APIUserSubscription: Sendable, Codable, JSONEncodable, Hashable {

    public var createdAt: Date
    public var pageTitle: String?
    public var url: String?
    public var urlId: String
    public var anonUserId: String?
    public var userId: String?
    public var id: String

    public init(createdAt: Date, pageTitle: String? = nil, url: String? = nil, urlId: String, anonUserId: String? = nil, userId: String? = nil, id: String) {
        self.createdAt = createdAt
        self.pageTitle = pageTitle
        self.url = url
        self.urlId = urlId
        self.anonUserId = anonUserId
        self.userId = userId
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt
        case pageTitle
        case url
        case urlId
        case anonUserId
        case userId
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(pageTitle, forKey: .pageTitle)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encode(urlId, forKey: .urlId)
        try container.encodeIfPresent(anonUserId, forKey: .anonUserId)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encode(id, forKey: .id)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension APIUserSubscription: Identifiable {}
