//
// AwardUserBadgeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AwardUserBadgeResponse: Sendable, Codable, Hashable {

    public var notes: [String]?
    public var badges: [CommentUserBadgeInfo]?
    public var status: APIStatus

    public init(notes: [String]? = nil, badges: [CommentUserBadgeInfo]? = nil, status: APIStatus) {
        self.notes = notes
        self.badges = badges
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case notes
        case badges
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(badges, forKey: .badges)
        try container.encode(status, forKey: .status)
    }
}

