//
// BannedUserMatchType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum BannedUserMatchType: String, Sendable, Codable, CaseIterable {
    case userid = "userId"
    case email = "email"
    case emailWildcard = "email-wildcard"
    case ip = "IP"
}
