//
// BannedUserMatch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BannedUserMatch: Sendable, Codable, Hashable {

    public var matchedOn: BannedUserMatchType
    public var matchedOnValue: BannedUserMatchMatchedOnValue?

    public init(matchedOn: BannedUserMatchType, matchedOnValue: BannedUserMatchMatchedOnValue?) {
        self.matchedOn = matchedOn
        self.matchedOnValue = matchedOnValue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case matchedOn
        case matchedOnValue
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(matchedOn, forKey: .matchedOn)
        try container.encode(matchedOnValue, forKey: .matchedOnValue)
    }
}

