//
// BanUserUndoParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BanUserUndoParams: Sendable, Codable, Hashable {

    public var changelog: APIBanUserChangeLog

    public init(changelog: APIBanUserChangeLog) {
        self.changelog = changelog
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case changelog
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(changelog, forKey: .changelog)
    }
}

