//
// BanUserFromCommentResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BanUserFromCommentResult: Sendable, Codable, Hashable {

    public var status: String
    public var changelog: APIBanUserChangeLog?
    public var code: String?
    public var reason: String?

    public init(status: String, changelog: APIBanUserChangeLog? = nil, code: String? = nil, reason: String? = nil) {
        self.status = status
        self.changelog = changelog
        self.code = code
        self.reason = reason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case changelog
        case code
        case reason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(changelog, forKey: .changelog)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(reason, forKey: .reason)
    }
}

