//
// BillingInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BillingInfo: Sendable, Codable, JSONEncodable, Hashable {

    public var name: String
    public var address: String
    public var city: String
    public var state: String
    public var zip: String
    public var country: String
    /** Currency for invoices. */
    public var currency: String?
    /** Email for invoices. */
    public var email: String?

    public init(name: String, address: String, city: String, state: String, zip: String, country: String, currency: String? = nil, email: String? = nil) {
        self.name = name
        self.address = address
        self.city = city
        self.state = state
        self.zip = zip
        self.country = country
        self.currency = currency
        self.email = email
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case address
        case city
        case state
        case zip
        case country
        case currency
        case email
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(address, forKey: .address)
        try container.encode(city, forKey: .city)
        try container.encode(state, forKey: .state)
        try container.encode(zip, forKey: .zip)
        try container.encode(country, forKey: .country)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(email, forKey: .email)
    }
}

