//
// BulkPreBanSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BulkPreBanSummary: Sendable, Codable, Hashable {

    public var status: String
    public var totalRelatedCommentCount: Int
    public var emailDomains: [String]
    public var emails: [String]
    public var userIds: [String]
    public var ipHashes: [String]

    public init(status: String, totalRelatedCommentCount: Int, emailDomains: [String], emails: [String], userIds: [String], ipHashes: [String]) {
        self.status = status
        self.totalRelatedCommentCount = totalRelatedCommentCount
        self.emailDomains = emailDomains
        self.emails = emails
        self.userIds = userIds
        self.ipHashes = ipHashes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case totalRelatedCommentCount
        case emailDomains
        case emails
        case userIds
        case ipHashes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(totalRelatedCommentCount, forKey: .totalRelatedCommentCount)
        try container.encode(emailDomains, forKey: .emailDomains)
        try container.encode(emails, forKey: .emails)
        try container.encode(userIds, forKey: .userIds)
        try container.encode(ipHashes, forKey: .ipHashes)
    }
}

