//
// BulkAggregateQuestionResultsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BulkAggregateQuestionResultsRequest: Sendable, Codable, JSONEncodable, Hashable {

    public var aggregations: [BulkAggregateQuestionItem]

    public init(aggregations: [BulkAggregateQuestionItem]) {
        self.aggregations = aggregations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aggregations
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(aggregations, forKey: .aggregations)
    }
}

