//
// BulkCreateHashTagsBodyTagsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BulkCreateHashTagsBodyTagsInner: Sendable, Codable, JSONEncodable, Hashable {

    public var url: String?
    public var tag: String

    public init(url: String? = nil, tag: String) {
        self.url = url
        self.tag = tag
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case tag
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encode(tag, forKey: .tag)
    }
}

