//
// BulkCreateHashTagsBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BulkCreateHashTagsBody: Sendable, Codable, JSONEncodable, Hashable {

    public var tenantId: String?
    public var tags: [BulkCreateHashTagsBodyTagsInner]

    public init(tenantId: String? = nil, tags: [BulkCreateHashTagsBodyTagsInner]) {
        self.tenantId = tenantId
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tenantId
        case tags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tenantId, forKey: .tenantId)
        try container.encode(tags, forKey: .tags)
    }
}

