//
// BulkAggregateQuestionItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BulkAggregateQuestionItem: Sendable, Codable, JSONEncodable, Hashable {

    public var aggId: String
    public var questionId: String?
    public var questionIds: [String]?
    public var urlId: String?
    public var timeBucket: AggregateTimeBucket?
    public var startDate: Date?

    public init(aggId: String, questionId: String? = nil, questionIds: [String]? = nil, urlId: String? = nil, timeBucket: AggregateTimeBucket? = nil, startDate: Date? = nil) {
        self.aggId = aggId
        self.questionId = questionId
        self.questionIds = questionIds
        self.urlId = urlId
        self.timeBucket = timeBucket
        self.startDate = startDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aggId
        case questionId
        case questionIds
        case urlId
        case timeBucket
        case startDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(aggId, forKey: .aggId)
        try container.encodeIfPresent(questionId, forKey: .questionId)
        try container.encodeIfPresent(questionIds, forKey: .questionIds)
        try container.encodeIfPresent(urlId, forKey: .urlId)
        try container.encodeIfPresent(timeBucket, forKey: .timeBucket)
        try container.encodeIfPresent(startDate, forKey: .startDate)
    }
}

