//
// ChangeTicketStateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ChangeTicketStateResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var status: APIStatus
    public var ticket: APITicket

    public init(status: APIStatus, ticket: APITicket) {
        self.status = status
        self.ticket = ticket
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case ticket
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(ticket, forKey: .ticket)
    }
}

