//
// ChangeCommentPinStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ChangeCommentPinStatusResponse: Sendable, Codable, JSONEncodable, Hashable {

    /** Construct a type with a set of properties K of type T */
    public var commentPositions: [String: RecordStringBeforeStringOrNullAfterStringOrNullValue]
    public var status: APIStatus

    public init(commentPositions: [String: RecordStringBeforeStringOrNullAfterStringOrNullValue], status: APIStatus) {
        self.commentPositions = commentPositions
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case commentPositions
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(commentPositions, forKey: .commentPositions)
        try container.encode(status, forKey: .status)
    }
}

