//
// ChangeTicketStateBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ChangeTicketStateBody: Sendable, Codable, ParameterConvertible, Hashable {

    public var state: Int

    public init(state: Int) {
        self.state = state
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case state
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(state, forKey: .state)
    }
}

