//
// CheckBlockedCommentsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CheckBlockedCommentsResponse: Sendable, Codable, JSONEncodable, Hashable {

    /** Construct a type with a set of properties K of type T */
    public var commentStatuses: [String: Bool]
    public var status: APIStatus

    public init(commentStatuses: [String: Bool], status: APIStatus) {
        self.commentStatuses = commentStatuses
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case commentStatuses
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(commentStatuses, forKey: .commentStatuses)
        try container.encode(status, forKey: .status)
    }
}

