//
// CommentHTMLRenderingMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum CommentHTMLRenderingMode: Double, Sendable, Codable, JSONEncodable, CaseIterable {
    case _0 = 0
    case _1 = 1
}
