//
// CommentLogType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum CommentLogType: Double, Sendable, Codable, JSONEncodable, CaseIterable {
    case _0 = 0
    case _1 = 1
    case _2 = 2
    case _3 = 3
    case _4 = 4
    case _5 = 5
    case _6 = 6
    case _7 = 7
    case _8 = 8
    case _9 = 9
    case _10 = 10
    case _11 = 11
    case _12 = 12
    case _13 = 13
    case _14 = 14
    case _15 = 15
    case _16 = 16
    case _17 = 17
    case _18 = 18
    case _19 = 19
    case _20 = 20
    case _21 = 21
    case _22 = 22
    case _23 = 23
    case _24 = 24
    case _25 = 25
    case _26 = 26
    case _27 = 27
    case _28 = 28
    case _29 = 29
    case _30 = 30
    case _31 = 31
    case _32 = 32
    case _33 = 33
    case _34 = 34
    case _35 = 35
    case _36 = 36
    case _37 = 37
    case _38 = 38
    case _39 = 39
    case _40 = 40
    case _41 = 41
    case _42 = 42
    case _43 = 43
    case _44 = 44
    case _45 = 45
    case _46 = 46
    case _47 = 47
    case _48 = 48
    case _49 = 49
    case _50 = 50
    case _51 = 51
    case _52 = 52
    case _53 = 53
    case _54 = 54
    case _55 = 55
}
