//
// CommentLogData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CommentLogData: Sendable, Codable, JSONEncodable, Hashable {

    public enum PermanentFlag: String, Sendable, Codable, CaseIterable {
        case permanent = "permanent"
    }
    public var clearContent: Bool?
    public var isDeletedUser: Bool?
    public var phrase: String?
    public var badWord: String?
    public var word: String?
    public var locale: String?
    public var tenantBadgeId: String?
    public var badgeId: String?
    public var wasLoggedIn: Bool?
    public var foundUser: Bool?
    public var verified: Bool?
    public var engine: String?
    public var engineResponse: String?
    public var engineTokens: Double?
    public var trustFactor: Double?
    public var rule: SpamRule?
    public var userId: String?
    public var subscribers: Double?
    public var notificationCount: Double?
    public var votesBefore: Double?
    public var votesUpBefore: Double?
    public var votesDownBefore: Double?
    public var votesAfter: Double?
    public var votesUpAfter: Double?
    public var votesDownAfter: Double?
    public var repeatAction: RepeatCommentHandlingAction?
    public var reason: RepeatCommentCheckIgnoredReason?
    public var otherData: JSONValue?
    public var spamBefore: Bool?
    public var spamAfter: Bool?
    public var permanentFlag: PermanentFlag?
    public var approvedBefore: Bool?
    public var approvedAfter: Bool?
    public var reviewedBefore: Bool?
    public var reviewedAfter: Bool?
    public var textBefore: String?
    public var textAfter: String?
    public var expireBefore: Date?
    public var expireAfter: Date?
    public var flagCountBefore: Double?
    public var trustFactorBefore: Double?
    public var trustFactorAfter: Double?
    public var referencedCommentId: String?
    public var invalidLocale: String?
    public var detectedLocale: String?
    public var detectedLanguage: String?

    public init(clearContent: Bool? = nil, isDeletedUser: Bool? = nil, phrase: String? = nil, badWord: String? = nil, word: String? = nil, locale: String? = nil, tenantBadgeId: String? = nil, badgeId: String? = nil, wasLoggedIn: Bool? = nil, foundUser: Bool? = nil, verified: Bool? = nil, engine: String? = nil, engineResponse: String? = nil, engineTokens: Double? = nil, trustFactor: Double? = nil, rule: SpamRule? = nil, userId: String? = nil, subscribers: Double? = nil, notificationCount: Double? = nil, votesBefore: Double? = nil, votesUpBefore: Double? = nil, votesDownBefore: Double? = nil, votesAfter: Double? = nil, votesUpAfter: Double? = nil, votesDownAfter: Double? = nil, repeatAction: RepeatCommentHandlingAction? = nil, reason: RepeatCommentCheckIgnoredReason? = nil, otherData: JSONValue? = nil, spamBefore: Bool? = nil, spamAfter: Bool? = nil, permanentFlag: PermanentFlag? = nil, approvedBefore: Bool? = nil, approvedAfter: Bool? = nil, reviewedBefore: Bool? = nil, reviewedAfter: Bool? = nil, textBefore: String? = nil, textAfter: String? = nil, expireBefore: Date? = nil, expireAfter: Date? = nil, flagCountBefore: Double? = nil, trustFactorBefore: Double? = nil, trustFactorAfter: Double? = nil, referencedCommentId: String? = nil, invalidLocale: String? = nil, detectedLocale: String? = nil, detectedLanguage: String? = nil) {
        self.clearContent = clearContent
        self.isDeletedUser = isDeletedUser
        self.phrase = phrase
        self.badWord = badWord
        self.word = word
        self.locale = locale
        self.tenantBadgeId = tenantBadgeId
        self.badgeId = badgeId
        self.wasLoggedIn = wasLoggedIn
        self.foundUser = foundUser
        self.verified = verified
        self.engine = engine
        self.engineResponse = engineResponse
        self.engineTokens = engineTokens
        self.trustFactor = trustFactor
        self.rule = rule
        self.userId = userId
        self.subscribers = subscribers
        self.notificationCount = notificationCount
        self.votesBefore = votesBefore
        self.votesUpBefore = votesUpBefore
        self.votesDownBefore = votesDownBefore
        self.votesAfter = votesAfter
        self.votesUpAfter = votesUpAfter
        self.votesDownAfter = votesDownAfter
        self.repeatAction = repeatAction
        self.reason = reason
        self.otherData = otherData
        self.spamBefore = spamBefore
        self.spamAfter = spamAfter
        self.permanentFlag = permanentFlag
        self.approvedBefore = approvedBefore
        self.approvedAfter = approvedAfter
        self.reviewedBefore = reviewedBefore
        self.reviewedAfter = reviewedAfter
        self.textBefore = textBefore
        self.textAfter = textAfter
        self.expireBefore = expireBefore
        self.expireAfter = expireAfter
        self.flagCountBefore = flagCountBefore
        self.trustFactorBefore = trustFactorBefore
        self.trustFactorAfter = trustFactorAfter
        self.referencedCommentId = referencedCommentId
        self.invalidLocale = invalidLocale
        self.detectedLocale = detectedLocale
        self.detectedLanguage = detectedLanguage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clearContent
        case isDeletedUser
        case phrase
        case badWord
        case word
        case locale
        case tenantBadgeId
        case badgeId
        case wasLoggedIn
        case foundUser
        case verified
        case engine
        case engineResponse
        case engineTokens
        case trustFactor
        case rule
        case userId
        case subscribers
        case notificationCount
        case votesBefore
        case votesUpBefore
        case votesDownBefore
        case votesAfter
        case votesUpAfter
        case votesDownAfter
        case repeatAction
        case reason
        case otherData
        case spamBefore
        case spamAfter
        case permanentFlag
        case approvedBefore
        case approvedAfter
        case reviewedBefore
        case reviewedAfter
        case textBefore
        case textAfter
        case expireBefore
        case expireAfter
        case flagCountBefore
        case trustFactorBefore
        case trustFactorAfter
        case referencedCommentId
        case invalidLocale
        case detectedLocale
        case detectedLanguage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(clearContent, forKey: .clearContent)
        try container.encodeIfPresent(isDeletedUser, forKey: .isDeletedUser)
        try container.encodeIfPresent(phrase, forKey: .phrase)
        try container.encodeIfPresent(badWord, forKey: .badWord)
        try container.encodeIfPresent(word, forKey: .word)
        try container.encodeIfPresent(locale, forKey: .locale)
        try container.encodeIfPresent(tenantBadgeId, forKey: .tenantBadgeId)
        try container.encodeIfPresent(badgeId, forKey: .badgeId)
        try container.encodeIfPresent(wasLoggedIn, forKey: .wasLoggedIn)
        try container.encodeIfPresent(foundUser, forKey: .foundUser)
        try container.encodeIfPresent(verified, forKey: .verified)
        try container.encodeIfPresent(engine, forKey: .engine)
        try container.encodeIfPresent(engineResponse, forKey: .engineResponse)
        try container.encodeIfPresent(engineTokens, forKey: .engineTokens)
        try container.encodeIfPresent(trustFactor, forKey: .trustFactor)
        try container.encodeIfPresent(rule, forKey: .rule)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(subscribers, forKey: .subscribers)
        try container.encodeIfPresent(notificationCount, forKey: .notificationCount)
        try container.encodeIfPresent(votesBefore, forKey: .votesBefore)
        try container.encodeIfPresent(votesUpBefore, forKey: .votesUpBefore)
        try container.encodeIfPresent(votesDownBefore, forKey: .votesDownBefore)
        try container.encodeIfPresent(votesAfter, forKey: .votesAfter)
        try container.encodeIfPresent(votesUpAfter, forKey: .votesUpAfter)
        try container.encodeIfPresent(votesDownAfter, forKey: .votesDownAfter)
        try container.encodeIfPresent(repeatAction, forKey: .repeatAction)
        try container.encodeIfPresent(reason, forKey: .reason)
        try container.encodeIfPresent(otherData, forKey: .otherData)
        try container.encodeIfPresent(spamBefore, forKey: .spamBefore)
        try container.encodeIfPresent(spamAfter, forKey: .spamAfter)
        try container.encodeIfPresent(permanentFlag, forKey: .permanentFlag)
        try container.encodeIfPresent(approvedBefore, forKey: .approvedBefore)
        try container.encodeIfPresent(approvedAfter, forKey: .approvedAfter)
        try container.encodeIfPresent(reviewedBefore, forKey: .reviewedBefore)
        try container.encodeIfPresent(reviewedAfter, forKey: .reviewedAfter)
        try container.encodeIfPresent(textBefore, forKey: .textBefore)
        try container.encodeIfPresent(textAfter, forKey: .textAfter)
        try container.encodeIfPresent(expireBefore, forKey: .expireBefore)
        try container.encodeIfPresent(expireAfter, forKey: .expireAfter)
        try container.encodeIfPresent(flagCountBefore, forKey: .flagCountBefore)
        try container.encodeIfPresent(trustFactorBefore, forKey: .trustFactorBefore)
        try container.encodeIfPresent(trustFactorAfter, forKey: .trustFactorAfter)
        try container.encodeIfPresent(referencedCommentId, forKey: .referencedCommentId)
        try container.encodeIfPresent(invalidLocale, forKey: .invalidLocale)
        try container.encodeIfPresent(detectedLocale, forKey: .detectedLocale)
        try container.encodeIfPresent(detectedLanguage, forKey: .detectedLanguage)
    }
}

