//
// CommentUserHashTagInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CommentUserHashTagInfo: Sendable, Codable, JSONEncodable, Hashable {

    public var id: String
    public var tag: String
    public var url: String?
    public var retain: Bool?

    public init(id: String, tag: String, url: String?, retain: Bool? = nil) {
        self.id = id
        self.tag = tag
        self.url = url
        self.retain = retain
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tag
        case url
        case retain
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tag, forKey: .tag)
        try container.encode(url, forKey: .url)
        try container.encodeIfPresent(retain, forKey: .retain)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension CommentUserHashTagInfo: Identifiable {}
