//
// CommentUserMentionInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CommentUserMentionInfo: Sendable, Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case user = "user"
        case sso = "sso"
    }
    public var id: String
    public var tag: String
    public var rawTag: String?
    public var type: ModelType?
    public var sent: Bool?

    public init(id: String, tag: String, rawTag: String? = nil, type: ModelType? = nil, sent: Bool? = nil) {
        self.id = id
        self.tag = tag
        self.rawTag = rawTag
        self.type = type
        self.sent = sent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tag
        case rawTag
        case type
        case sent
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tag, forKey: .tag)
        try container.encodeIfPresent(rawTag, forKey: .rawTag)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(sent, forKey: .sent)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension CommentUserMentionInfo: Identifiable {}
