//
// CommenterNameFormats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum CommenterNameFormats: Double, Sendable, Codable, JSONEncodable, CaseIterable {
    case _0 = 0
    case _1 = 1
    case _2 = 2
    case _3 = 3
    case _4 = 4
}
