//
// CommentLogEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CommentLogEntry: Sendable, Codable, JSONEncodable, Hashable {

    public var d: Date
    public var t: CommentLogType
    public var da: CommentLogData?

    public init(d: Date, t: CommentLogType, da: CommentLogData? = nil) {
        self.d = d
        self.t = t
        self.da = da
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case d
        case t
        case da
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(d, forKey: .d)
        try container.encode(t, forKey: .t)
        try container.encodeIfPresent(da, forKey: .da)
    }
}

