//
// CreateModeratorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateModeratorResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var moderator: Moderator

    public init(status: APIStatus, moderator: Moderator) {
        self.status = status
        self.moderator = moderator
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case moderator
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(moderator, forKey: .moderator)
    }
}

