//
// CreateTicketBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateTicketBody: Sendable, Codable, JSONEncodable, Hashable {

    public var subject: String

    public init(subject: String) {
        self.subject = subject
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case subject
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(subject, forKey: .subject)
    }
}

