//
// CreateModeratorBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateModeratorBody: Sendable, Codable, JSONEncodable, Hashable {

    public var name: String
    public var email: String
    public var userId: String?
    public var moderationGroupIds: [String]?

    public init(name: String, email: String, userId: String? = nil, moderationGroupIds: [String]? = nil) {
        self.name = name
        self.email = email
        self.userId = userId
        self.moderationGroupIds = moderationGroupIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case email
        case userId
        case moderationGroupIds
    }

    public var additionalProperties: [String: JSONValue] = [:]

    public subscript(key: String) -> JSONValue? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(moderationGroupIds, forKey: .moderationGroupIds)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        name = try container.decode(String.self, forKey: .name)
        email = try container.decode(String.self, forKey: .email)
        userId = try container.decodeIfPresent(String.self, forKey: .userId)
        moderationGroupIds = try container.decodeIfPresent([String].self, forKey: .moderationGroupIds)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("name")
        nonAdditionalPropertyKeys.insert("email")
        nonAdditionalPropertyKeys.insert("userId")
        nonAdditionalPropertyKeys.insert("moderationGroupIds")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(JSONValue.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

