//
// CreateFeedPostResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateFeedPostResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var feedPost: FeedPost

    public init(status: APIStatus, feedPost: FeedPost) {
        self.status = status
        self.feedPost = feedPost
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case feedPost
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(feedPost, forKey: .feedPost)
    }
}

