//
// CreateFeedPostParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateFeedPostParams: Sendable, Codable, JSONEncodable, Hashable {

    public var title: String?
    public var contentHTML: String?
    public var media: [FeedPostMediaItem]?
    public var links: [FeedPostLink]?
    public var fromUserId: String?
    public var fromUserDisplayName: String?
    public var tags: [String]?
    /** Construct a type with a set of properties K of type T */
    public var meta: [String: String]?

    public init(title: String? = nil, contentHTML: String? = nil, media: [FeedPostMediaItem]? = nil, links: [FeedPostLink]? = nil, fromUserId: String? = nil, fromUserDisplayName: String? = nil, tags: [String]? = nil, meta: [String: String]? = nil) {
        self.title = title
        self.contentHTML = contentHTML
        self.media = media
        self.links = links
        self.fromUserId = fromUserId
        self.fromUserDisplayName = fromUserDisplayName
        self.tags = tags
        self.meta = meta
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case contentHTML
        case media
        case links
        case fromUserId
        case fromUserDisplayName
        case tags
        case meta
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(contentHTML, forKey: .contentHTML)
        try container.encodeIfPresent(media, forKey: .media)
        try container.encodeIfPresent(links, forKey: .links)
        try container.encodeIfPresent(fromUserId, forKey: .fromUserId)
        try container.encodeIfPresent(fromUserDisplayName, forKey: .fromUserDisplayName)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encodeIfPresent(meta, forKey: .meta)
    }
}

