//
// CreateAPIPageData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateAPIPageData: Sendable, Codable, JSONEncodable, Hashable {

    public var accessibleByGroupIds: [String]?
    public var rootCommentCount: Int64?
    public var commentCount: Int64?
    public var title: String
    public var url: String
    public var urlId: String

    public init(accessibleByGroupIds: [String]? = nil, rootCommentCount: Int64? = nil, commentCount: Int64? = nil, title: String, url: String, urlId: String) {
        self.accessibleByGroupIds = accessibleByGroupIds
        self.rootCommentCount = rootCommentCount
        self.commentCount = commentCount
        self.title = title
        self.url = url
        self.urlId = urlId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accessibleByGroupIds
        case rootCommentCount
        case commentCount
        case title
        case url
        case urlId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accessibleByGroupIds, forKey: .accessibleByGroupIds)
        try container.encodeIfPresent(rootCommentCount, forKey: .rootCommentCount)
        try container.encodeIfPresent(commentCount, forKey: .commentCount)
        try container.encode(title, forKey: .title)
        try container.encode(url, forKey: .url)
        try container.encode(urlId, forKey: .urlId)
    }
}

