//
// CreateHashTagResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateHashTagResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var hashTag: TenantHashTag

    public init(status: APIStatus, hashTag: TenantHashTag) {
        self.status = status
        self.hashTag = hashTag
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case hashTag
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(hashTag, forKey: .hashTag)
    }
}

