//
// CreateQuestionResultBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateQuestionResultBody: Sendable, Codable, JSONEncodable, Hashable {

    public var urlId: String
    public var value: Double
    public var questionId: String
    public var anonUserId: String?
    public var userId: String?
    public var commentId: String?
    public var meta: [MetaItem]?

    public init(urlId: String, value: Double, questionId: String, anonUserId: String? = nil, userId: String? = nil, commentId: String? = nil, meta: [MetaItem]? = nil) {
        self.urlId = urlId
        self.value = value
        self.questionId = questionId
        self.anonUserId = anonUserId
        self.userId = userId
        self.commentId = commentId
        self.meta = meta
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case urlId
        case value
        case questionId
        case anonUserId
        case userId
        case commentId
        case meta
    }

    public var additionalProperties: [String: JSONValue] = [:]

    public subscript(key: String) -> JSONValue? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(urlId, forKey: .urlId)
        try container.encode(value, forKey: .value)
        try container.encode(questionId, forKey: .questionId)
        try container.encodeIfPresent(anonUserId, forKey: .anonUserId)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(commentId, forKey: .commentId)
        try container.encodeIfPresent(meta, forKey: .meta)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        urlId = try container.decode(String.self, forKey: .urlId)
        value = try container.decode(Double.self, forKey: .value)
        questionId = try container.decode(String.self, forKey: .questionId)
        anonUserId = try container.decodeIfPresent(String.self, forKey: .anonUserId)
        userId = try container.decodeIfPresent(String.self, forKey: .userId)
        commentId = try container.decodeIfPresent(String.self, forKey: .commentId)
        meta = try container.decodeIfPresent([MetaItem].self, forKey: .meta)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("urlId")
        nonAdditionalPropertyKeys.insert("value")
        nonAdditionalPropertyKeys.insert("questionId")
        nonAdditionalPropertyKeys.insert("anonUserId")
        nonAdditionalPropertyKeys.insert("userId")
        nonAdditionalPropertyKeys.insert("commentId")
        nonAdditionalPropertyKeys.insert("meta")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(JSONValue.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

