//
// CreateTenantUserResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateTenantUserResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var tenantUser: User

    public init(status: APIStatus, tenantUser: User) {
        self.status = status
        self.tenantUser = tenantUser
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case tenantUser
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(tenantUser, forKey: .tenantUser)
    }
}

