//
// CreateUserBadgeParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateUserBadgeParams: Sendable, Codable, JSONEncodable, Hashable {

    public var userId: String
    public var badgeId: String
    public var displayedOnComments: Bool?

    public init(userId: String, badgeId: String, displayedOnComments: Bool? = nil) {
        self.userId = userId
        self.badgeId = badgeId
        self.displayedOnComments = displayedOnComments
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId
        case badgeId
        case displayedOnComments
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userId, forKey: .userId)
        try container.encode(badgeId, forKey: .badgeId)
        try container.encodeIfPresent(displayedOnComments, forKey: .displayedOnComments)
    }
}

