//
// CreateAPIUserSubscriptionData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateAPIUserSubscriptionData: Sendable, Codable, JSONEncodable, Hashable {

    public var pageTitle: String?
    public var url: String?
    public var urlId: String
    public var anonUserId: String?
    public var userId: String?

    public init(pageTitle: String? = nil, url: String? = nil, urlId: String, anonUserId: String? = nil, userId: String? = nil) {
        self.pageTitle = pageTitle
        self.url = url
        self.urlId = urlId
        self.anonUserId = anonUserId
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pageTitle
        case url
        case urlId
        case anonUserId
        case userId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(pageTitle, forKey: .pageTitle)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encode(urlId, forKey: .urlId)
        try container.encodeIfPresent(anonUserId, forKey: .anonUserId)
        try container.encodeIfPresent(userId, forKey: .userId)
    }
}

