//
// CreateEmailTemplateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateEmailTemplateResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var emailTemplate: CustomEmailTemplate

    public init(status: APIStatus, emailTemplate: CustomEmailTemplate) {
        self.status = status
        self.emailTemplate = emailTemplate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case emailTemplate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(emailTemplate, forKey: .emailTemplate)
    }
}

