//
// CreateSubscriptionAPIResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateSubscriptionAPIResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var reason: String?
    public var code: String?
    public var subscription: APIUserSubscription?
    public var status: String

    public init(reason: String? = nil, code: String? = nil, subscription: APIUserSubscription? = nil, status: String) {
        self.reason = reason
        self.code = code
        self.subscription = subscription
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reason
        case code
        case subscription
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(reason, forKey: .reason)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(subscription, forKey: .subscription)
        try container.encode(status, forKey: .status)
    }
}

