//
// CreateQuestionConfigResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateQuestionConfigResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var questionConfig: QuestionConfig

    public init(status: APIStatus, questionConfig: QuestionConfig) {
        self.status = status
        self.questionConfig = questionConfig
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case questionConfig
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(questionConfig, forKey: .questionConfig)
    }
}

