//
// DeletedCommentResultComment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeletedCommentResultComment: Sendable, Codable, JSONEncodable, Hashable {

    public var isDeleted: Bool?
    public var commentHTML: String
    public var commenterName: String
    public var userId: String?

    public init(isDeleted: Bool? = nil, commentHTML: String, commenterName: String, userId: String? = nil) {
        self.isDeleted = isDeleted
        self.commentHTML = commentHTML
        self.commenterName = commenterName
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isDeleted
        case commentHTML
        case commenterName
        case userId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isDeleted, forKey: .isDeleted)
        try container.encode(commentHTML, forKey: .commentHTML)
        try container.encode(commenterName, forKey: .commenterName)
        try container.encodeIfPresent(userId, forKey: .userId)
    }
}

