//
// DeleteHashTagRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeleteHashTagRequest: Sendable, Codable, JSONEncodable, Hashable {

    public var tenantId: String?

    public init(tenantId: String? = nil) {
        self.tenantId = tenantId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tenantId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tenantId, forKey: .tenantId)
    }
}

