//
// DeleteCommentAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum DeleteCommentAction: String, Sendable, Codable, CaseIterable {
    case alreadyDeleted = "already-deleted"
    case hardRemoved = "hard-removed"
    case anonymized = "anonymized"
}
