//
// DigestEmailFrequency.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum DigestEmailFrequency: Double, Sendable, Codable, JSONEncodable, CaseIterable {
    case number1 = -1
    case _0 = 0
    case _1 = 1
    case _2 = 2
}
