//
// EmailTemplateRenderErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct EmailTemplateRenderErrorResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var id: String
    public var tenantId: String
    public var customTemplateId: String
    public var error: String
    public var count: Double
    public var createdAt: Date
    public var lastOccurredAt: Date

    public init(id: String, tenantId: String, customTemplateId: String, error: String, count: Double, createdAt: Date, lastOccurredAt: Date) {
        self.id = id
        self.tenantId = tenantId
        self.customTemplateId = customTemplateId
        self.error = error
        self.count = count
        self.createdAt = createdAt
        self.lastOccurredAt = lastOccurredAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tenantId
        case customTemplateId
        case error
        case count
        case createdAt
        case lastOccurredAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(customTemplateId, forKey: .customTemplateId)
        try container.encode(error, forKey: .error)
        try container.encode(count, forKey: .count)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(lastOccurredAt, forKey: .lastOccurredAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension EmailTemplateRenderErrorResponse: Identifiable {}
