//
// EmailTemplateDefinition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct EmailTemplateDefinition: Sendable, Codable, JSONEncodable, Hashable {

    public var emailTemplateId: String
    /** Construct a type with a set of properties K of type T */
    public var defaultTestData: [String: JSONValue]
    /** Construct a type with a set of properties K of type T */
    public var defaultTranslationsByLocale: [String: Dictionary]
    public var defaultEJS: String

    public init(emailTemplateId: String, defaultTestData: [String: JSONValue], defaultTranslationsByLocale: [String: Dictionary], defaultEJS: String) {
        self.emailTemplateId = emailTemplateId
        self.defaultTestData = defaultTestData
        self.defaultTranslationsByLocale = defaultTranslationsByLocale
        self.defaultEJS = defaultEJS
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case emailTemplateId
        case defaultTestData
        case defaultTranslationsByLocale
        case defaultEJS
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(emailTemplateId, forKey: .emailTemplateId)
        try container.encode(defaultTestData, forKey: .defaultTestData)
        try container.encode(defaultTranslationsByLocale, forKey: .defaultTranslationsByLocale)
        try container.encode(defaultEJS, forKey: .defaultEJS)
    }
}

