//
// FCommentMeta.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FCommentMeta: Sendable, Codable, JSONEncodable, Hashable {

    public var wpUserId: String?
    public var wpPostId: String?

    public init(wpUserId: String? = nil, wpPostId: String? = nil) {
        self.wpUserId = wpUserId
        self.wpPostId = wpPostId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case wpUserId
        case wpPostId
    }

    public var additionalProperties: [String: JSONValue] = [:]

    public subscript(key: String) -> JSONValue? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(wpUserId, forKey: .wpUserId)
        try container.encodeIfPresent(wpPostId, forKey: .wpPostId)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        wpUserId = try container.decodeIfPresent(String.self, forKey: .wpUserId)
        wpPostId = try container.decodeIfPresent(String.self, forKey: .wpPostId)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("wpUserId")
        nonAdditionalPropertyKeys.insert("wpPostId")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(JSONValue.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

