//
// FComment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FComment: Sendable, Codable, JSONEncodable, Hashable {

    public var id: String
    public var tenantId: String
    public var urlId: String
    public var urlIdRaw: String?
    public var url: String
    public var pageTitle: String?
    public var userId: String?
    public var anonUserId: String?
    public var commenterEmail: String?
    public var commenterName: String
    public var commenterLink: String?
    public var comment: String
    public var commentHTML: String
    public var parentId: String?
    public var date: Date?
    public var localDateString: String?
    public var localDateHours: Int?
    public var votes: Int?
    public var votesUp: Int?
    public var votesDown: Int?
    public var expireAt: Date?
    public var verified: Bool
    public var verifiedDate: Date?
    public var verificationId: String?
    public var notificationSentForParent: Bool?
    public var notificationSentForParentTenant: Bool?
    public var reviewed: Bool?
    public var imported: Bool?
    public var externalId: String?
    public var externalParentId: String?
    public var avatarSrc: String?
    public var isSpam: Bool?
    public var permNotSpam: Bool?
    public var aiDeterminedSpam: Bool?
    public var hasImages: Bool?
    public var pageNumber: Int?
    public var pageNumberOF: Int?
    public var pageNumberNF: Int?
    public var hasLinks: Bool?
    public var hasCode: Bool?
    public var approved: Bool
    public var locale: String?
    public var isDeleted: Bool?
    public var isDeletedUser: Bool?
    public var isBannedUser: Bool?
    public var isByAdmin: Bool?
    public var isByModerator: Bool?
    public var isPinned: Bool?
    public var isLocked: Bool?
    public var flagCount: Int?
    public var rating: Double?
    public var displayLabel: String?
    public var fromProductId: Int?
    public var meta: FCommentMeta?
    public var ipHash: String?
    public var mentions: [CommentUserMentionInfo]?
    public var hashTags: [CommentUserHashTagInfo]?
    public var badges: [CommentUserBadgeInfo]?
    public var domain: String?
    public var veteranBadgeProcessed: String?
    public var moderationGroupIds: [String]?
    public var didProcessBadges: Bool?
    public var fromOfflineRestore: Bool?
    public var autoplayJobId: String?
    public var autoplayDelayMS: Int64?
    public var feedbackIds: [String]?
    public var logs: [CommentLogEntry]?
    public var groupIds: [String]?
    public var viewCount: Int64?
    public var requiresVerification: Bool?
    public var editKey: String?

    public init(id: String, tenantId: String, urlId: String, urlIdRaw: String? = nil, url: String, pageTitle: String? = nil, userId: String? = nil, anonUserId: String? = nil, commenterEmail: String? = nil, commenterName: String, commenterLink: String? = nil, comment: String, commentHTML: String, parentId: String? = nil, date: Date?, localDateString: String? = nil, localDateHours: Int? = nil, votes: Int? = nil, votesUp: Int? = nil, votesDown: Int? = nil, expireAt: Date? = nil, verified: Bool, verifiedDate: Date? = nil, verificationId: String? = nil, notificationSentForParent: Bool? = nil, notificationSentForParentTenant: Bool? = nil, reviewed: Bool? = nil, imported: Bool? = nil, externalId: String? = nil, externalParentId: String? = nil, avatarSrc: String? = nil, isSpam: Bool? = nil, permNotSpam: Bool? = nil, aiDeterminedSpam: Bool? = nil, hasImages: Bool? = nil, pageNumber: Int? = nil, pageNumberOF: Int? = nil, pageNumberNF: Int? = nil, hasLinks: Bool? = nil, hasCode: Bool? = nil, approved: Bool, locale: String?, isDeleted: Bool? = nil, isDeletedUser: Bool? = nil, isBannedUser: Bool? = nil, isByAdmin: Bool? = nil, isByModerator: Bool? = nil, isPinned: Bool? = nil, isLocked: Bool? = nil, flagCount: Int? = nil, rating: Double? = nil, displayLabel: String? = nil, fromProductId: Int? = nil, meta: FCommentMeta? = nil, ipHash: String? = nil, mentions: [CommentUserMentionInfo]? = nil, hashTags: [CommentUserHashTagInfo]? = nil, badges: [CommentUserBadgeInfo]? = nil, domain: String? = nil, veteranBadgeProcessed: String? = nil, moderationGroupIds: [String]? = nil, didProcessBadges: Bool? = nil, fromOfflineRestore: Bool? = nil, autoplayJobId: String? = nil, autoplayDelayMS: Int64? = nil, feedbackIds: [String]? = nil, logs: [CommentLogEntry]? = nil, groupIds: [String]? = nil, viewCount: Int64? = nil, requiresVerification: Bool? = nil, editKey: String? = nil) {
        self.id = id
        self.tenantId = tenantId
        self.urlId = urlId
        self.urlIdRaw = urlIdRaw
        self.url = url
        self.pageTitle = pageTitle
        self.userId = userId
        self.anonUserId = anonUserId
        self.commenterEmail = commenterEmail
        self.commenterName = commenterName
        self.commenterLink = commenterLink
        self.comment = comment
        self.commentHTML = commentHTML
        self.parentId = parentId
        self.date = date
        self.localDateString = localDateString
        self.localDateHours = localDateHours
        self.votes = votes
        self.votesUp = votesUp
        self.votesDown = votesDown
        self.expireAt = expireAt
        self.verified = verified
        self.verifiedDate = verifiedDate
        self.verificationId = verificationId
        self.notificationSentForParent = notificationSentForParent
        self.notificationSentForParentTenant = notificationSentForParentTenant
        self.reviewed = reviewed
        self.imported = imported
        self.externalId = externalId
        self.externalParentId = externalParentId
        self.avatarSrc = avatarSrc
        self.isSpam = isSpam
        self.permNotSpam = permNotSpam
        self.aiDeterminedSpam = aiDeterminedSpam
        self.hasImages = hasImages
        self.pageNumber = pageNumber
        self.pageNumberOF = pageNumberOF
        self.pageNumberNF = pageNumberNF
        self.hasLinks = hasLinks
        self.hasCode = hasCode
        self.approved = approved
        self.locale = locale
        self.isDeleted = isDeleted
        self.isDeletedUser = isDeletedUser
        self.isBannedUser = isBannedUser
        self.isByAdmin = isByAdmin
        self.isByModerator = isByModerator
        self.isPinned = isPinned
        self.isLocked = isLocked
        self.flagCount = flagCount
        self.rating = rating
        self.displayLabel = displayLabel
        self.fromProductId = fromProductId
        self.meta = meta
        self.ipHash = ipHash
        self.mentions = mentions
        self.hashTags = hashTags
        self.badges = badges
        self.domain = domain
        self.veteranBadgeProcessed = veteranBadgeProcessed
        self.moderationGroupIds = moderationGroupIds
        self.didProcessBadges = didProcessBadges
        self.fromOfflineRestore = fromOfflineRestore
        self.autoplayJobId = autoplayJobId
        self.autoplayDelayMS = autoplayDelayMS
        self.feedbackIds = feedbackIds
        self.logs = logs
        self.groupIds = groupIds
        self.viewCount = viewCount
        self.requiresVerification = requiresVerification
        self.editKey = editKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case tenantId
        case urlId
        case urlIdRaw
        case url
        case pageTitle
        case userId
        case anonUserId
        case commenterEmail
        case commenterName
        case commenterLink
        case comment
        case commentHTML
        case parentId
        case date
        case localDateString
        case localDateHours
        case votes
        case votesUp
        case votesDown
        case expireAt
        case verified
        case verifiedDate
        case verificationId
        case notificationSentForParent
        case notificationSentForParentTenant
        case reviewed
        case imported
        case externalId
        case externalParentId
        case avatarSrc
        case isSpam
        case permNotSpam
        case aiDeterminedSpam
        case hasImages
        case pageNumber
        case pageNumberOF
        case pageNumberNF
        case hasLinks
        case hasCode
        case approved
        case locale
        case isDeleted
        case isDeletedUser
        case isBannedUser
        case isByAdmin
        case isByModerator
        case isPinned
        case isLocked
        case flagCount
        case rating
        case displayLabel
        case fromProductId
        case meta
        case ipHash
        case mentions
        case hashTags
        case badges
        case domain
        case veteranBadgeProcessed
        case moderationGroupIds
        case didProcessBadges
        case fromOfflineRestore
        case autoplayJobId
        case autoplayDelayMS
        case feedbackIds
        case logs
        case groupIds
        case viewCount
        case requiresVerification
        case editKey
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(urlId, forKey: .urlId)
        try container.encodeIfPresent(urlIdRaw, forKey: .urlIdRaw)
        try container.encode(url, forKey: .url)
        try container.encodeIfPresent(pageTitle, forKey: .pageTitle)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(anonUserId, forKey: .anonUserId)
        try container.encodeIfPresent(commenterEmail, forKey: .commenterEmail)
        try container.encode(commenterName, forKey: .commenterName)
        try container.encodeIfPresent(commenterLink, forKey: .commenterLink)
        try container.encode(comment, forKey: .comment)
        try container.encode(commentHTML, forKey: .commentHTML)
        try container.encodeIfPresent(parentId, forKey: .parentId)
        try container.encode(date, forKey: .date)
        try container.encodeIfPresent(localDateString, forKey: .localDateString)
        try container.encodeIfPresent(localDateHours, forKey: .localDateHours)
        try container.encodeIfPresent(votes, forKey: .votes)
        try container.encodeIfPresent(votesUp, forKey: .votesUp)
        try container.encodeIfPresent(votesDown, forKey: .votesDown)
        try container.encodeIfPresent(expireAt, forKey: .expireAt)
        try container.encode(verified, forKey: .verified)
        try container.encodeIfPresent(verifiedDate, forKey: .verifiedDate)
        try container.encodeIfPresent(verificationId, forKey: .verificationId)
        try container.encodeIfPresent(notificationSentForParent, forKey: .notificationSentForParent)
        try container.encodeIfPresent(notificationSentForParentTenant, forKey: .notificationSentForParentTenant)
        try container.encodeIfPresent(reviewed, forKey: .reviewed)
        try container.encodeIfPresent(imported, forKey: .imported)
        try container.encodeIfPresent(externalId, forKey: .externalId)
        try container.encodeIfPresent(externalParentId, forKey: .externalParentId)
        try container.encodeIfPresent(avatarSrc, forKey: .avatarSrc)
        try container.encodeIfPresent(isSpam, forKey: .isSpam)
        try container.encodeIfPresent(permNotSpam, forKey: .permNotSpam)
        try container.encodeIfPresent(aiDeterminedSpam, forKey: .aiDeterminedSpam)
        try container.encodeIfPresent(hasImages, forKey: .hasImages)
        try container.encodeIfPresent(pageNumber, forKey: .pageNumber)
        try container.encodeIfPresent(pageNumberOF, forKey: .pageNumberOF)
        try container.encodeIfPresent(pageNumberNF, forKey: .pageNumberNF)
        try container.encodeIfPresent(hasLinks, forKey: .hasLinks)
        try container.encodeIfPresent(hasCode, forKey: .hasCode)
        try container.encode(approved, forKey: .approved)
        try container.encode(locale, forKey: .locale)
        try container.encodeIfPresent(isDeleted, forKey: .isDeleted)
        try container.encodeIfPresent(isDeletedUser, forKey: .isDeletedUser)
        try container.encodeIfPresent(isBannedUser, forKey: .isBannedUser)
        try container.encodeIfPresent(isByAdmin, forKey: .isByAdmin)
        try container.encodeIfPresent(isByModerator, forKey: .isByModerator)
        try container.encodeIfPresent(isPinned, forKey: .isPinned)
        try container.encodeIfPresent(isLocked, forKey: .isLocked)
        try container.encodeIfPresent(flagCount, forKey: .flagCount)
        try container.encodeIfPresent(rating, forKey: .rating)
        try container.encodeIfPresent(displayLabel, forKey: .displayLabel)
        try container.encodeIfPresent(fromProductId, forKey: .fromProductId)
        try container.encodeIfPresent(meta, forKey: .meta)
        try container.encodeIfPresent(ipHash, forKey: .ipHash)
        try container.encodeIfPresent(mentions, forKey: .mentions)
        try container.encodeIfPresent(hashTags, forKey: .hashTags)
        try container.encodeIfPresent(badges, forKey: .badges)
        try container.encodeIfPresent(domain, forKey: .domain)
        try container.encodeIfPresent(veteranBadgeProcessed, forKey: .veteranBadgeProcessed)
        try container.encodeIfPresent(moderationGroupIds, forKey: .moderationGroupIds)
        try container.encodeIfPresent(didProcessBadges, forKey: .didProcessBadges)
        try container.encodeIfPresent(fromOfflineRestore, forKey: .fromOfflineRestore)
        try container.encodeIfPresent(autoplayJobId, forKey: .autoplayJobId)
        try container.encodeIfPresent(autoplayDelayMS, forKey: .autoplayDelayMS)
        try container.encodeIfPresent(feedbackIds, forKey: .feedbackIds)
        try container.encodeIfPresent(logs, forKey: .logs)
        try container.encodeIfPresent(groupIds, forKey: .groupIds)
        try container.encodeIfPresent(viewCount, forKey: .viewCount)
        try container.encodeIfPresent(requiresVerification, forKey: .requiresVerification)
        try container.encodeIfPresent(editKey, forKey: .editKey)
    }
}

