//
// FeedPostMediaItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FeedPostMediaItem: Sendable, Codable, JSONEncodable, Hashable {

    public var title: String?
    public var linkUrl: String?
    public var sizes: [FeedPostMediaItemAsset]

    public init(title: String? = nil, linkUrl: String? = nil, sizes: [FeedPostMediaItemAsset]) {
        self.title = title
        self.linkUrl = linkUrl
        self.sizes = sizes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case linkUrl
        case sizes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(linkUrl, forKey: .linkUrl)
        try container.encode(sizes, forKey: .sizes)
    }
}

