//
// FeedPost.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FeedPost: Sendable, Codable, JSONEncodable, Hashable {

    public var id: String
    public var tenantId: String
    public var title: String?
    public var fromUserId: String?
    public var fromUserDisplayName: String?
    public var fromUserAvatar: String?
    public var fromIpHash: String?
    public var tags: [String]?
    public var weight: Double?
    /** Construct a type with a set of properties K of type T */
    public var meta: [String: String]?
    public var contentHTML: String?
    public var media: [FeedPostMediaItem]?
    public var links: [FeedPostLink]?
    public var createdAt: Date
    public var reacts: [String: Int]?
    public var commentCount: Int?

    public init(id: String, tenantId: String, title: String? = nil, fromUserId: String? = nil, fromUserDisplayName: String? = nil, fromUserAvatar: String? = nil, fromIpHash: String? = nil, tags: [String]? = nil, weight: Double? = nil, meta: [String: String]? = nil, contentHTML: String? = nil, media: [FeedPostMediaItem]? = nil, links: [FeedPostLink]? = nil, createdAt: Date, reacts: [String: Int]? = nil, commentCount: Int? = nil) {
        self.id = id
        self.tenantId = tenantId
        self.title = title
        self.fromUserId = fromUserId
        self.fromUserDisplayName = fromUserDisplayName
        self.fromUserAvatar = fromUserAvatar
        self.fromIpHash = fromIpHash
        self.tags = tags
        self.weight = weight
        self.meta = meta
        self.contentHTML = contentHTML
        self.media = media
        self.links = links
        self.createdAt = createdAt
        self.reacts = reacts
        self.commentCount = commentCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case tenantId
        case title
        case fromUserId
        case fromUserDisplayName
        case fromUserAvatar
        case fromIpHash
        case tags
        case weight
        case meta
        case contentHTML
        case media
        case links
        case createdAt
        case reacts
        case commentCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(fromUserId, forKey: .fromUserId)
        try container.encodeIfPresent(fromUserDisplayName, forKey: .fromUserDisplayName)
        try container.encodeIfPresent(fromUserAvatar, forKey: .fromUserAvatar)
        try container.encodeIfPresent(fromIpHash, forKey: .fromIpHash)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encodeIfPresent(weight, forKey: .weight)
        try container.encodeIfPresent(meta, forKey: .meta)
        try container.encodeIfPresent(contentHTML, forKey: .contentHTML)
        try container.encodeIfPresent(media, forKey: .media)
        try container.encodeIfPresent(links, forKey: .links)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(reacts, forKey: .reacts)
        try container.encodeIfPresent(commentCount, forKey: .commentCount)
    }
}

