//
// FeedPostStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FeedPostStats: Sendable, Codable, JSONEncodable, Hashable {

    public var reacts: [String: Int]?
    public var commentCount: Int?

    public init(reacts: [String: Int]? = nil, commentCount: Int? = nil) {
        self.reacts = reacts
        self.commentCount = commentCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reacts
        case commentCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(reacts, forKey: .reacts)
        try container.encodeIfPresent(commentCount, forKey: .commentCount)
    }
}

