//
// FindCommentsByRangeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FindCommentsByRangeResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var results: [FindCommentsByRangeItem]
    public var createdAt: Date

    public init(results: [FindCommentsByRangeItem], createdAt: Date) {
        self.results = results
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case results
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(results, forKey: .results)
        try container.encode(createdAt, forKey: .createdAt)
    }
}

