//
// FlagComment200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FlagComment200Response: Sendable, Codable, JSONEncodable, Hashable {

    public var statusCode: Int?
    public var status: APIStatus
    public var code: String
    public var reason: String
    public var wasUnapproved: Bool?
    public var secondaryCode: String?
    public var bannedUntil: Int64?
    public var maxCharacterLength: Int?
    public var translatedError: String?
    public var customConfig: CustomConfigParameters?

    public init(statusCode: Int? = nil, status: APIStatus, code: String, reason: String, wasUnapproved: Bool? = nil, secondaryCode: String? = nil, bannedUntil: Int64? = nil, maxCharacterLength: Int? = nil, translatedError: String? = nil, customConfig: CustomConfigParameters? = nil) {
        self.statusCode = statusCode
        self.status = status
        self.code = code
        self.reason = reason
        self.wasUnapproved = wasUnapproved
        self.secondaryCode = secondaryCode
        self.bannedUntil = bannedUntil
        self.maxCharacterLength = maxCharacterLength
        self.translatedError = translatedError
        self.customConfig = customConfig
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case statusCode
        case status
        case code
        case reason
        case wasUnapproved
        case secondaryCode
        case bannedUntil
        case maxCharacterLength
        case translatedError
        case customConfig
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(statusCode, forKey: .statusCode)
        try container.encode(status, forKey: .status)
        try container.encode(code, forKey: .code)
        try container.encode(reason, forKey: .reason)
        try container.encodeIfPresent(wasUnapproved, forKey: .wasUnapproved)
        try container.encodeIfPresent(secondaryCode, forKey: .secondaryCode)
        try container.encodeIfPresent(bannedUntil, forKey: .bannedUntil)
        try container.encodeIfPresent(maxCharacterLength, forKey: .maxCharacterLength)
        try container.encodeIfPresent(translatedError, forKey: .translatedError)
        try container.encodeIfPresent(customConfig, forKey: .customConfig)
    }
}

