//
// GetApiExportStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetApiExportStatusResponse: Sendable, Codable, Hashable {

    public var status: APIStatus
    public var jobStatus: String?
    public var recordCount: Int?
    public var downloadUrl: String?
    public var reason: String?
    public var code: String?
    public var secondaryCode: String?
    public var bannedUntil: Int64?
    public var maxCharacterLength: Int?
    public var translatedError: String?
    public var customConfig: CustomConfigParameters?

    public init(status: APIStatus, jobStatus: String? = nil, recordCount: Int? = nil, downloadUrl: String? = nil, reason: String? = nil, code: String? = nil, secondaryCode: String? = nil, bannedUntil: Int64? = nil, maxCharacterLength: Int? = nil, translatedError: String? = nil, customConfig: CustomConfigParameters? = nil) {
        self.status = status
        self.jobStatus = jobStatus
        self.recordCount = recordCount
        self.downloadUrl = downloadUrl
        self.reason = reason
        self.code = code
        self.secondaryCode = secondaryCode
        self.bannedUntil = bannedUntil
        self.maxCharacterLength = maxCharacterLength
        self.translatedError = translatedError
        self.customConfig = customConfig
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case jobStatus
        case recordCount
        case downloadUrl
        case reason
        case code
        case secondaryCode
        case bannedUntil
        case maxCharacterLength
        case translatedError
        case customConfig
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(jobStatus, forKey: .jobStatus)
        try container.encodeIfPresent(recordCount, forKey: .recordCount)
        try container.encodeIfPresent(downloadUrl, forKey: .downloadUrl)
        try container.encodeIfPresent(reason, forKey: .reason)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(secondaryCode, forKey: .secondaryCode)
        try container.encodeIfPresent(bannedUntil, forKey: .bannedUntil)
        try container.encodeIfPresent(maxCharacterLength, forKey: .maxCharacterLength)
        try container.encodeIfPresent(translatedError, forKey: .translatedError)
        try container.encodeIfPresent(customConfig, forKey: .customConfig)
    }
}

