//
// GetAuditLogsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetAuditLogsResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var auditLogs: [APIAuditLog]

    public init(status: APIStatus, auditLogs: [APIAuditLog]) {
        self.status = status
        self.auditLogs = auditLogs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case auditLogs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(auditLogs, forKey: .auditLogs)
    }
}

