//
// GetBannedUsersCountResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetBannedUsersCountResponse: Sendable, Codable, Hashable {

    public var totalCount: Double
    public var status: String

    public init(totalCount: Double, status: String) {
        self.totalCount = totalCount
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalCount
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(totalCount, forKey: .totalCount)
        try container.encode(status, forKey: .status)
    }
}

