//
// GetBannedUsersFromCommentResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetBannedUsersFromCommentResponse: Sendable, Codable, Hashable {

    public enum Code: String, Sendable, Codable, CaseIterable {
        case notFound = "not-found"
        case notLoggedIn = "not-logged-in"
    }
    public var bannedUsers: [APIBannedUserWithMultiMatchInfo]
    public var code: Code?
    public var status: APIStatus

    public init(bannedUsers: [APIBannedUserWithMultiMatchInfo], code: Code? = nil, status: APIStatus) {
        self.bannedUsers = bannedUsers
        self.code = code
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bannedUsers
        case code
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(bannedUsers, forKey: .bannedUsers)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encode(status, forKey: .status)
    }
}

