//
// GetCommentVoteUserNamesSuccessResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetCommentVoteUserNamesSuccessResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var voteUserNames: [String]
    public var hasMore: Bool

    public init(status: APIStatus, voteUserNames: [String], hasMore: Bool) {
        self.status = status
        self.voteUserNames = voteUserNames
        self.hasMore = hasMore
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case voteUserNames
        case hasMore
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(voteUserNames, forKey: .voteUserNames)
        try container.encode(hasMore, forKey: .hasMore)
    }
}

