//
// GetCommentTextResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetCommentTextResponse: Sendable, Codable, Hashable {

    public var comment: String?
    public var status: APIStatus

    public init(comment: String? = nil, status: APIStatus) {
        self.comment = comment
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case comment
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(comment, forKey: .comment)
        try container.encode(status, forKey: .status)
    }
}

