//
// GetCommentsForUserResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetCommentsForUserResponse: Sendable, Codable, Hashable {

    public var moderatingTenantIds: [String]?

    public init(moderatingTenantIds: [String]? = nil) {
        self.moderatingTenantIds = moderatingTenantIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case moderatingTenantIds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(moderatingTenantIds, forKey: .moderatingTenantIds)
    }
}

