//
// GetCommentBanStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetCommentBanStatusResponse: Sendable, Codable, Hashable {

    public var status: String
    public var emailDomain: String?
    public var canIPBan: Bool?

    public init(status: String, emailDomain: String?, canIPBan: Bool?) {
        self.status = status
        self.emailDomain = emailDomain
        self.canIPBan = canIPBan
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case emailDomain
        case canIPBan
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(emailDomain, forKey: .emailDomain)
        try container.encode(canIPBan, forKey: .canIPBan)
    }
}

