//
// GetDomainConfig200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetDomainConfig200Response: Sendable, Codable, JSONEncodable, Hashable {

    public var configuration: JSONValue?
    public var status: JSONValue?
    public var reason: String
    public var code: String

    public init(configuration: JSONValue?, status: JSONValue?, reason: String, code: String) {
        self.configuration = configuration
        self.status = status
        self.reason = reason
        self.code = code
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case configuration
        case status
        case reason
        case code
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(configuration, forKey: .configuration)
        try container.encode(status, forKey: .status)
        try container.encode(reason, forKey: .reason)
        try container.encode(code, forKey: .code)
    }
}

