//
// GetDomainConfigs200ResponseAnyOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetDomainConfigs200ResponseAnyOf: Sendable, Codable, JSONEncodable, Hashable {

    public var configurations: JSONValue?
    public var status: JSONValue?

    public init(configurations: JSONValue?, status: JSONValue?) {
        self.configurations = configurations
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case configurations
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(configurations, forKey: .configurations)
        try container.encode(status, forKey: .status)
    }
}

