//
// GetDomainConfigs200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetDomainConfigs200Response: Sendable, Codable, JSONEncodable, Hashable {

    public var configurations: JSONValue?
    public var status: JSONValue?
    public var reason: String
    public var code: String

    public init(configurations: JSONValue?, status: JSONValue?, reason: String, code: String) {
        self.configurations = configurations
        self.status = status
        self.reason = reason
        self.code = code
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case configurations
        case status
        case reason
        case code
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(configurations, forKey: .configurations)
        try container.encode(status, forKey: .status)
        try container.encode(reason, forKey: .reason)
        try container.encode(code, forKey: .code)
    }
}

