//
// GetEmailTemplateRenderErrorsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetEmailTemplateRenderErrorsResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var renderErrors: [EmailTemplateRenderErrorResponse]

    public init(status: APIStatus, renderErrors: [EmailTemplateRenderErrorResponse]) {
        self.status = status
        self.renderErrors = renderErrors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case renderErrors
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(renderErrors, forKey: .renderErrors)
    }
}

