//
// GetEmailTemplatesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetEmailTemplatesResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var emailTemplates: [CustomEmailTemplate]

    public init(status: APIStatus, emailTemplates: [CustomEmailTemplate]) {
        self.status = status
        self.emailTemplates = emailTemplates
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case emailTemplates
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(emailTemplates, forKey: .emailTemplates)
    }
}

