//
// GetEventLogResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetEventLogResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var events: [EventLogEntry]
    public var status: APIStatus

    public init(events: [EventLogEntry], status: APIStatus) {
        self.events = events
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case events
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(events, forKey: .events)
        try container.encode(status, forKey: .status)
    }
}

