//
// GetFeedPostsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetFeedPostsResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var feedPosts: [FeedPost]

    public init(status: APIStatus, feedPosts: [FeedPost]) {
        self.status = status
        self.feedPosts = feedPosts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case feedPosts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(feedPosts, forKey: .feedPosts)
    }
}

