//
// GetFeedPostsPublic200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetFeedPostsPublic200Response: Sendable, Codable, JSONEncodable, Hashable {

    public var myReacts: [String: [String: Bool]]?
    public var status: APIStatus
    public var feedPosts: [FeedPost]
    public var user: UserSessionInfo?
    public var urlIdWS: String?
    public var userIdWS: String?
    public var tenantIdWS: String?
    public var reason: String
    public var code: String
    public var secondaryCode: String?
    public var bannedUntil: Int64?
    public var maxCharacterLength: Int?
    public var translatedError: String?
    public var customConfig: CustomConfigParameters?

    public init(myReacts: [String: [String: Bool]]? = nil, status: APIStatus, feedPosts: [FeedPost], user: UserSessionInfo? = nil, urlIdWS: String? = nil, userIdWS: String? = nil, tenantIdWS: String? = nil, reason: String, code: String, secondaryCode: String? = nil, bannedUntil: Int64? = nil, maxCharacterLength: Int? = nil, translatedError: String? = nil, customConfig: CustomConfigParameters? = nil) {
        self.myReacts = myReacts
        self.status = status
        self.feedPosts = feedPosts
        self.user = user
        self.urlIdWS = urlIdWS
        self.userIdWS = userIdWS
        self.tenantIdWS = tenantIdWS
        self.reason = reason
        self.code = code
        self.secondaryCode = secondaryCode
        self.bannedUntil = bannedUntil
        self.maxCharacterLength = maxCharacterLength
        self.translatedError = translatedError
        self.customConfig = customConfig
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case myReacts
        case status
        case feedPosts
        case user
        case urlIdWS
        case userIdWS
        case tenantIdWS
        case reason
        case code
        case secondaryCode
        case bannedUntil
        case maxCharacterLength
        case translatedError
        case customConfig
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(myReacts, forKey: .myReacts)
        try container.encode(status, forKey: .status)
        try container.encode(feedPosts, forKey: .feedPosts)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encodeIfPresent(urlIdWS, forKey: .urlIdWS)
        try container.encodeIfPresent(userIdWS, forKey: .userIdWS)
        try container.encodeIfPresent(tenantIdWS, forKey: .tenantIdWS)
        try container.encode(reason, forKey: .reason)
        try container.encode(code, forKey: .code)
        try container.encodeIfPresent(secondaryCode, forKey: .secondaryCode)
        try container.encodeIfPresent(bannedUntil, forKey: .bannedUntil)
        try container.encodeIfPresent(maxCharacterLength, forKey: .maxCharacterLength)
        try container.encodeIfPresent(translatedError, forKey: .translatedError)
        try container.encodeIfPresent(customConfig, forKey: .customConfig)
    }
}

