//
// GetGifsTrendingResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetGifsTrendingResponse: Sendable, Codable, Hashable {

    public var images: [[GifSearchResponseImagesInnerInner]]?
    public var status: APIStatus
    public var code: String?

    public init(images: [[GifSearchResponseImagesInnerInner]]? = nil, status: APIStatus, code: String? = nil) {
        self.images = images
        self.status = status
        self.code = code
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case images
        case status
        case code
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(images, forKey: .images)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(code, forKey: .code)
    }
}

