//
// GetHashTagsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetHashTagsResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var hashTags: [TenantHashTag]

    public init(status: APIStatus, hashTags: [TenantHashTag]) {
        self.status = status
        self.hashTags = hashTags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case hashTags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(hashTags, forKey: .hashTags)
    }
}

