//
// GetModeratorsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetModeratorsResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var moderators: [Moderator]

    public init(status: APIStatus, moderators: [Moderator]) {
        self.status = status
        self.moderators = moderators
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case moderators
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(moderators, forKey: .moderators)
    }
}

