//
// GetNotificationsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetNotificationsResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var notifications: [UserNotification]

    public init(status: APIStatus, notifications: [UserNotification]) {
        self.status = status
        self.notifications = notifications
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case notifications
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(notifications, forKey: .notifications)
    }
}

