//
// GetOfflineUsersResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetOfflineUsersResponse: Sendable, Codable, Hashable {

    public var nextAfterUserId: String?
    public var nextAfterName: String?
    public var users: [PageUserEntry]?
    public var status: APIStatus
    public var reason: String?
    public var code: String?
    public var secondaryCode: String?
    public var bannedUntil: Int64?
    public var maxCharacterLength: Int?
    public var translatedError: String?
    public var customConfig: CustomConfigParameters?

    public init(nextAfterUserId: String? = nil, nextAfterName: String? = nil, users: [PageUserEntry]? = nil, status: APIStatus, reason: String? = nil, code: String? = nil, secondaryCode: String? = nil, bannedUntil: Int64? = nil, maxCharacterLength: Int? = nil, translatedError: String? = nil, customConfig: CustomConfigParameters? = nil) {
        self.nextAfterUserId = nextAfterUserId
        self.nextAfterName = nextAfterName
        self.users = users
        self.status = status
        self.reason = reason
        self.code = code
        self.secondaryCode = secondaryCode
        self.bannedUntil = bannedUntil
        self.maxCharacterLength = maxCharacterLength
        self.translatedError = translatedError
        self.customConfig = customConfig
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nextAfterUserId
        case nextAfterName
        case users
        case status
        case reason
        case code
        case secondaryCode
        case bannedUntil
        case maxCharacterLength
        case translatedError
        case customConfig
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(nextAfterUserId, forKey: .nextAfterUserId)
        try container.encodeIfPresent(nextAfterName, forKey: .nextAfterName)
        try container.encodeIfPresent(users, forKey: .users)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(reason, forKey: .reason)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(secondaryCode, forKey: .secondaryCode)
        try container.encodeIfPresent(bannedUntil, forKey: .bannedUntil)
        try container.encodeIfPresent(maxCharacterLength, forKey: .maxCharacterLength)
        try container.encodeIfPresent(translatedError, forKey: .translatedError)
        try container.encodeIfPresent(customConfig, forKey: .customConfig)
    }
}

