//
// GetPendingWebhookEventsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetPendingWebhookEventsResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var pendingWebhookEvents: [PendingCommentToSyncOutbound]

    public init(status: APIStatus, pendingWebhookEvents: [PendingCommentToSyncOutbound]) {
        self.status = status
        self.pendingWebhookEvents = pendingWebhookEvents
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case pendingWebhookEvents
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(pendingWebhookEvents, forKey: .pendingWebhookEvents)
    }
}

