//
// GetPublicFeedPostsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetPublicFeedPostsResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var feedPosts: [FeedPost]
    public var user: UserSessionInfo?

    public init(status: APIStatus, feedPosts: [FeedPost], user: UserSessionInfo? = nil) {
        self.status = status
        self.feedPosts = feedPosts
        self.user = user
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case feedPosts
        case user
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(feedPosts, forKey: .feedPosts)
        try container.encodeIfPresent(user, forKey: .user)
    }
}

