//
// GetPublicPagesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetPublicPagesResponse: Sendable, Codable, Hashable {

    public var nextCursor: String?
    public var pages: [PublicPage]
    public var status: APIStatus

    public init(nextCursor: String?, pages: [PublicPage], status: APIStatus) {
        self.nextCursor = nextCursor
        self.pages = pages
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nextCursor
        case pages
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(nextCursor, forKey: .nextCursor)
        try container.encode(pages, forKey: .pages)
        try container.encode(status, forKey: .status)
    }
}

