//
// GetPagesAPIResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetPagesAPIResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var reason: String?
    public var code: String?
    public var pages: [APIPage]?
    public var status: String

    public init(reason: String? = nil, code: String? = nil, pages: [APIPage]? = nil, status: String) {
        self.reason = reason
        self.code = code
        self.pages = pages
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reason
        case code
        case pages
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(reason, forKey: .reason)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(pages, forKey: .pages)
        try container.encode(status, forKey: .status)
    }
}

