//
// GetPendingWebhookEventCountResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetPendingWebhookEventCountResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var count: Double

    public init(status: APIStatus, count: Double) {
        self.status = status
        self.count = count
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case count
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(count, forKey: .count)
    }
}

