//
// GetQuestionResultsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetQuestionResultsResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var questionResults: [QuestionResult]

    public init(status: APIStatus, questionResults: [QuestionResult]) {
        self.status = status
        self.questionResults = questionResults
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case questionResults
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(questionResults, forKey: .questionResults)
    }
}

