//
// GetSSOUsers200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetSSOUsers200Response: Sendable, Codable, JSONEncodable, Hashable {

    public var users: [APISSOUser]
    public var status: String

    public init(users: [APISSOUser], status: String) {
        self.users = users
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case users
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(users, forKey: .users)
        try container.encode(status, forKey: .status)
    }
}

