//
// GetTicketResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetTicketResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var status: APIStatus
    public var ticket: APITicketDetail
    public var availableStates: [Double]

    public init(status: APIStatus, ticket: APITicketDetail, availableStates: [Double]) {
        self.status = status
        self.ticket = ticket
        self.availableStates = availableStates
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case ticket
        case availableStates
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(ticket, forKey: .ticket)
        try container.encode(availableStates, forKey: .availableStates)
    }
}

