//
// GetTicketsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetTicketsResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var status: APIStatus
    public var tickets: [APITicket]

    public init(status: APIStatus, tickets: [APITicket]) {
        self.status = status
        self.tickets = tickets
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case tickets
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(tickets, forKey: .tickets)
    }
}

