//
// GetTenantDailyUsagesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetTenantDailyUsagesResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var tenantDailyUsages: [APITenantDailyUsage]

    public init(status: APIStatus, tenantDailyUsages: [APITenantDailyUsage]) {
        self.status = status
        self.tenantDailyUsages = tenantDailyUsages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case tenantDailyUsages
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(tenantDailyUsages, forKey: .tenantDailyUsages)
    }
}

