//
// GetTranslationsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetTranslationsResponse: Sendable, Codable, Hashable {

    /** Construct a type with a set of properties K of type T */
    public var translations: [String: String]
    public var status: APIStatus

    public init(translations: [String: String], status: APIStatus) {
        self.translations = translations
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case translations
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(translations, forKey: .translations)
        try container.encode(status, forKey: .status)
    }
}

