//
// GetTenantsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetTenantsResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var tenants: [APITenant]

    public init(status: APIStatus, tenants: [APITenant]) {
        self.status = status
        self.tenants = tenants
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case tenants
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(tenants, forKey: .tenants)
    }
}

