//
// GetTenantPackagesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetTenantPackagesResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var tenantPackages: [TenantPackage]

    public init(status: APIStatus, tenantPackages: [TenantPackage]) {
        self.status = status
        self.tenantPackages = tenantPackages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case tenantPackages
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(tenantPackages, forKey: .tenantPackages)
    }
}

