//
// GetTenantResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetTenantResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var tenant: APITenant

    public init(status: APIStatus, tenant: APITenant) {
        self.status = status
        self.tenant = tenant
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case tenant
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(tenant, forKey: .tenant)
    }
}

