//
// GetTenantUsersResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetTenantUsersResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var tenantUsers: [User]

    public init(status: APIStatus, tenantUsers: [User]) {
        self.status = status
        self.tenantUsers = tenantUsers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case tenantUsers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(tenantUsers, forKey: .tenantUsers)
    }
}

