//
// GetUserNotifications200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetUserNotifications200Response: Sendable, Codable, JSONEncodable, Hashable {

    /** Construct a type with a set of properties K of type T */
    public var translations: [String: String]?
    public var isSubscribed: Bool
    public var hasMore: Bool
    public var notifications: [RenderableUserNotification]
    public var status: APIStatus
    public var reason: String
    public var code: String
    public var secondaryCode: String?
    public var bannedUntil: Int64?
    public var maxCharacterLength: Int?
    public var translatedError: String?
    public var customConfig: CustomConfigParameters?

    public init(translations: [String: String]? = nil, isSubscribed: Bool, hasMore: Bool, notifications: [RenderableUserNotification], status: APIStatus, reason: String, code: String, secondaryCode: String? = nil, bannedUntil: Int64? = nil, maxCharacterLength: Int? = nil, translatedError: String? = nil, customConfig: CustomConfigParameters? = nil) {
        self.translations = translations
        self.isSubscribed = isSubscribed
        self.hasMore = hasMore
        self.notifications = notifications
        self.status = status
        self.reason = reason
        self.code = code
        self.secondaryCode = secondaryCode
        self.bannedUntil = bannedUntil
        self.maxCharacterLength = maxCharacterLength
        self.translatedError = translatedError
        self.customConfig = customConfig
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case translations
        case isSubscribed
        case hasMore
        case notifications
        case status
        case reason
        case code
        case secondaryCode
        case bannedUntil
        case maxCharacterLength
        case translatedError
        case customConfig
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(translations, forKey: .translations)
        try container.encode(isSubscribed, forKey: .isSubscribed)
        try container.encode(hasMore, forKey: .hasMore)
        try container.encode(notifications, forKey: .notifications)
        try container.encode(status, forKey: .status)
        try container.encode(reason, forKey: .reason)
        try container.encode(code, forKey: .code)
        try container.encodeIfPresent(secondaryCode, forKey: .secondaryCode)
        try container.encodeIfPresent(bannedUntil, forKey: .bannedUntil)
        try container.encodeIfPresent(maxCharacterLength, forKey: .maxCharacterLength)
        try container.encodeIfPresent(translatedError, forKey: .translatedError)
        try container.encodeIfPresent(customConfig, forKey: .customConfig)
    }
}

