//
// GetUserPresenceStatusesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetUserPresenceStatusesResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    /** Construct a type with a set of properties K of type T */
    public var userIdsOnline: [String: Bool]

    public init(status: APIStatus, userIdsOnline: [String: Bool]) {
        self.status = status
        self.userIdsOnline = userIdsOnline
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case userIdsOnline
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(userIdsOnline, forKey: .userIdsOnline)
    }
}

