//
// GetUserTrustFactorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetUserTrustFactorResponse: Sendable, Codable, Hashable {

    public var manualTrustFactor: Double?
    public var autoTrustFactor: Double?
    public var status: APIStatus

    public init(manualTrustFactor: Double? = nil, autoTrustFactor: Double? = nil, status: APIStatus) {
        self.manualTrustFactor = manualTrustFactor
        self.autoTrustFactor = autoTrustFactor
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case manualTrustFactor
        case autoTrustFactor
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(manualTrustFactor, forKey: .manualTrustFactor)
        try container.encodeIfPresent(autoTrustFactor, forKey: .autoTrustFactor)
        try container.encode(status, forKey: .status)
    }
}

