//
// GetUserManualBadgesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetUserManualBadgesResponse: Sendable, Codable, Hashable {

    public var badges: [UserBadge]
    public var status: APIStatus

    public init(badges: [UserBadge], status: APIStatus) {
        self.badges = badges
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case badges
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(badges, forKey: .badges)
        try container.encode(status, forKey: .status)
    }
}

