//
// GetUserInternalProfileResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetUserInternalProfileResponse: Sendable, Codable, Hashable {

    public var profile: GetUserInternalProfileResponseProfile
    public var status: APIStatus

    public init(profile: GetUserInternalProfileResponseProfile, status: APIStatus) {
        self.profile = profile
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case profile
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(profile, forKey: .profile)
        try container.encode(status, forKey: .status)
    }
}

