//
// GetUserInternalProfileResponseProfile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetUserInternalProfileResponseProfile: Sendable, Codable, Hashable {

    public var commenterName: String?
    public var firstCommentDate: Date?
    public var ipHash: String?
    public var countryFlag: String?
    public var countryCode: String?
    public var websiteUrl: String?
    public var bio: String?
    public var karma: Double?
    public var locale: String?
    public var verified: Bool?
    public var avatarSrc: String?
    public var displayName: String?
    public var username: String?
    public var commenterEmail: String?
    public var email: String?
    public var anonUserId: String?
    public var userId: String?

    public init(commenterName: String? = nil, firstCommentDate: Date? = nil, ipHash: String? = nil, countryFlag: String? = nil, countryCode: String? = nil, websiteUrl: String? = nil, bio: String? = nil, karma: Double? = nil, locale: String? = nil, verified: Bool? = nil, avatarSrc: String? = nil, displayName: String? = nil, username: String? = nil, commenterEmail: String? = nil, email: String? = nil, anonUserId: String? = nil, userId: String? = nil) {
        self.commenterName = commenterName
        self.firstCommentDate = firstCommentDate
        self.ipHash = ipHash
        self.countryFlag = countryFlag
        self.countryCode = countryCode
        self.websiteUrl = websiteUrl
        self.bio = bio
        self.karma = karma
        self.locale = locale
        self.verified = verified
        self.avatarSrc = avatarSrc
        self.displayName = displayName
        self.username = username
        self.commenterEmail = commenterEmail
        self.email = email
        self.anonUserId = anonUserId
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case commenterName
        case firstCommentDate
        case ipHash
        case countryFlag
        case countryCode
        case websiteUrl
        case bio
        case karma
        case locale
        case verified
        case avatarSrc
        case displayName
        case username
        case commenterEmail
        case email
        case anonUserId
        case userId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(commenterName, forKey: .commenterName)
        try container.encodeIfPresent(firstCommentDate, forKey: .firstCommentDate)
        try container.encodeIfPresent(ipHash, forKey: .ipHash)
        try container.encodeIfPresent(countryFlag, forKey: .countryFlag)
        try container.encodeIfPresent(countryCode, forKey: .countryCode)
        try container.encodeIfPresent(websiteUrl, forKey: .websiteUrl)
        try container.encodeIfPresent(bio, forKey: .bio)
        try container.encodeIfPresent(karma, forKey: .karma)
        try container.encodeIfPresent(locale, forKey: .locale)
        try container.encodeIfPresent(verified, forKey: .verified)
        try container.encodeIfPresent(avatarSrc, forKey: .avatarSrc)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(username, forKey: .username)
        try container.encodeIfPresent(commenterEmail, forKey: .commenterEmail)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(anonUserId, forKey: .anonUserId)
        try container.encodeIfPresent(userId, forKey: .userId)
    }
}

