//
// GetUserResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetUserResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var user: User

    public init(status: APIStatus, user: User) {
        self.status = status
        self.user = user
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case user
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(user, forKey: .user)
    }
}

