//
// GetV2PageReacts.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetV2PageReacts: Sendable, Codable, Hashable {

    public var reactedIds: [String]?
    /** Construct a type with a set of properties K of type T */
    public var counts: [String: Double]?
    public var status: APIStatus

    public init(reactedIds: [String]? = nil, counts: [String: Double]? = nil, status: APIStatus) {
        self.reactedIds = reactedIds
        self.counts = counts
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reactedIds
        case counts
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(reactedIds, forKey: .reactedIds)
        try container.encodeIfPresent(counts, forKey: .counts)
        try container.encode(status, forKey: .status)
    }
}

