//
// GetV1PageLikes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetV1PageLikes: Sendable, Codable, Hashable {

    public var urlIdWS: String
    public var didLike: Bool
    public var commentCount: Int
    public var likeCount: Int
    public var status: APIStatus

    public init(urlIdWS: String, didLike: Bool, commentCount: Int, likeCount: Int, status: APIStatus) {
        self.urlIdWS = urlIdWS
        self.didLike = didLike
        self.commentCount = commentCount
        self.likeCount = likeCount
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case urlIdWS
        case didLike
        case commentCount
        case likeCount
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(urlIdWS, forKey: .urlIdWS)
        try container.encode(didLike, forKey: .didLike)
        try container.encode(commentCount, forKey: .commentCount)
        try container.encode(likeCount, forKey: .likeCount)
        try container.encode(status, forKey: .status)
    }
}

