//
// GetVotesForUserResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetVotesForUserResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var appliedAuthorizedVotes: [PublicVote]
    public var appliedAnonymousVotes: [PublicVote]
    public var pendingVotes: [PublicVote]

    public init(status: APIStatus, appliedAuthorizedVotes: [PublicVote], appliedAnonymousVotes: [PublicVote], pendingVotes: [PublicVote]) {
        self.status = status
        self.appliedAuthorizedVotes = appliedAuthorizedVotes
        self.appliedAnonymousVotes = appliedAnonymousVotes
        self.pendingVotes = pendingVotes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case appliedAuthorizedVotes
        case appliedAnonymousVotes
        case pendingVotes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(appliedAuthorizedVotes, forKey: .appliedAuthorizedVotes)
        try container.encode(appliedAnonymousVotes, forKey: .appliedAnonymousVotes)
        try container.encode(pendingVotes, forKey: .pendingVotes)
    }
}

