//
// GetV2PageReactUsersResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetV2PageReactUsersResponse: Sendable, Codable, Hashable {

    public var userNames: [String]
    public var status: APIStatus

    public init(userNames: [String], status: APIStatus) {
        self.userNames = userNames
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userNames
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userNames, forKey: .userNames)
        try container.encode(status, forKey: .status)
    }
}

