//
// GifGetLargeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GifGetLargeResponse: Sendable, Codable, Hashable {

    public var src: String
    public var status: APIStatus

    public init(src: String, status: APIStatus) {
        self.src = src
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case src
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(src, forKey: .src)
        try container.encode(status, forKey: .status)
    }
}

