//
// GifRating.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum GifRating: String, Sendable, Codable, CaseIterable {
    case g = "g"
    case pg = "pg"
    case pg13 = "pg-13"
    case r = "r"
}
