//
// GifSearchResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GifSearchResponse: Sendable, Codable, Hashable {

    public var images: [[GifSearchResponseImagesInnerInner]]
    public var status: APIStatus

    public init(images: [[GifSearchResponseImagesInnerInner]], status: APIStatus) {
        self.images = images
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case images
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(images, forKey: .images)
        try container.encode(status, forKey: .status)
    }
}

