//
// GifSearchInternalError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GifSearchInternalError: Sendable, Codable, Hashable {

    public var code: String
    public var status: APIStatus

    public init(code: String, status: APIStatus) {
        self.code = code
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(status, forKey: .status)
    }
}

