//
// HeaderState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct HeaderState: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var notificationType: JSONValue
    public var userId: String
    public var userIdWS: String
    public var notificationCounts: [NotificationAndCount]

    public init(status: APIStatus, notificationType: JSONValue, userId: String, userIdWS: String, notificationCounts: [NotificationAndCount]) {
        self.status = status
        self.notificationType = notificationType
        self.userId = userId
        self.userIdWS = userIdWS
        self.notificationCounts = notificationCounts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case notificationType = "NotificationType"
        case userId
        case userIdWS
        case notificationCounts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(notificationType, forKey: .notificationType)
        try container.encode(userId, forKey: .userId)
        try container.encode(userIdWS, forKey: .userIdWS)
        try container.encode(notificationCounts, forKey: .notificationCounts)
    }
}

