//
// HeaderAccountNotification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct HeaderAccountNotification: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: String
    public var title: String
    public var message: String
    /** Construct a type with a set of properties K of type T */
    public var messagesByLocale: [String: String]?
    /** Construct a type with a set of properties K of type T */
    public var dates: [String: String]?
    public var severity: String
    public var linkUrl: String?
    public var linkText: String?
    public var createdAt: Date

    public init(id: String, title: String, message: String, messagesByLocale: [String: String]?, dates: [String: String]?, severity: String, linkUrl: String?, linkText: String?, createdAt: Date) {
        self.id = id
        self.title = title
        self.message = message
        self.messagesByLocale = messagesByLocale
        self.dates = dates
        self.severity = severity
        self.linkUrl = linkUrl
        self.linkText = linkText
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case title
        case message
        case messagesByLocale
        case dates
        case severity
        case linkUrl
        case linkText
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(title, forKey: .title)
        try container.encode(message, forKey: .message)
        try container.encode(messagesByLocale, forKey: .messagesByLocale)
        try container.encode(dates, forKey: .dates)
        try container.encode(severity, forKey: .severity)
        try container.encode(linkUrl, forKey: .linkUrl)
        try container.encode(linkText, forKey: .linkText)
        try container.encode(createdAt, forKey: .createdAt)
    }
}

