//
// IgnoredResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct IgnoredResponse: Sendable, Codable, JSONEncodable, Hashable {

    public enum Note: String, Sendable, Codable, CaseIterable {
        case ignoredSinceImpersonated = "ignored-since-impersonated"
        case demoNoop = "demo-noop"
    }
    public var status: APIStatus
    public var note: Note

    public init(status: APIStatus, note: Note) {
        self.status = status
        self.note = note
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case note
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(note, forKey: .note)
    }
}

