//
// ImageContentProfanityLevel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ImageContentProfanityLevel: String, Sendable, Codable, CaseIterable {
    case off = "off"
    case low = "low"
    case medium = "medium"
    case high = "high"
}
