//
// LiveEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LiveEvent: Sendable, Codable, JSONEncodable, Hashable {

    public var type: LiveEventType
    public var timestamp: Int64?
    public var ts: Int64?
    public var broadcastId: String?
    public var userId: String?
    public var badges: [CommentUserBadgeInfo]?
    public var notification: UserNotification?
    public var vote: PubSubVote?
    public var comment: PubSubComment?
    public var feedPost: FeedPost?
    public var extraInfo: LiveEventExtraInfo?
    public var config: JSONValue?
    public var isClosed: Bool?
    public var uj: [String]?
    public var ul: [String]?
    public var changes: [String: Int]?

    public init(type: LiveEventType, timestamp: Int64? = nil, ts: Int64? = nil, broadcastId: String? = nil, userId: String? = nil, badges: [CommentUserBadgeInfo]? = nil, notification: UserNotification? = nil, vote: PubSubVote? = nil, comment: PubSubComment? = nil, feedPost: FeedPost? = nil, extraInfo: LiveEventExtraInfo? = nil, config: JSONValue? = nil, isClosed: Bool? = nil, uj: [String]? = nil, ul: [String]? = nil, changes: [String: Int]? = nil) {
        self.type = type
        self.timestamp = timestamp
        self.ts = ts
        self.broadcastId = broadcastId
        self.userId = userId
        self.badges = badges
        self.notification = notification
        self.vote = vote
        self.comment = comment
        self.feedPost = feedPost
        self.extraInfo = extraInfo
        self.config = config
        self.isClosed = isClosed
        self.uj = uj
        self.ul = ul
        self.changes = changes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case timestamp
        case ts
        case broadcastId
        case userId
        case badges
        case notification
        case vote
        case comment
        case feedPost
        case extraInfo
        case config
        case isClosed
        case uj
        case ul
        case changes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(ts, forKey: .ts)
        try container.encodeIfPresent(broadcastId, forKey: .broadcastId)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(badges, forKey: .badges)
        try container.encodeIfPresent(notification, forKey: .notification)
        try container.encodeIfPresent(vote, forKey: .vote)
        try container.encodeIfPresent(comment, forKey: .comment)
        try container.encodeIfPresent(feedPost, forKey: .feedPost)
        try container.encodeIfPresent(extraInfo, forKey: .extraInfo)
        try container.encodeIfPresent(config, forKey: .config)
        try container.encodeIfPresent(isClosed, forKey: .isClosed)
        try container.encodeIfPresent(uj, forKey: .uj)
        try container.encodeIfPresent(ul, forKey: .ul)
        try container.encodeIfPresent(changes, forKey: .changes)
    }
}

