//
// LiveEventExtraInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LiveEventExtraInfo: Sendable, Codable, JSONEncodable, Hashable {

    /** Construct a type with a set of properties K of type T */
    public var commentPositions: [String: RecordStringBeforeStringOrNullAfterStringOrNullValue]?

    public init(commentPositions: [String: RecordStringBeforeStringOrNullAfterStringOrNullValue]? = nil) {
        self.commentPositions = commentPositions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case commentPositions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(commentPositions, forKey: .commentPositions)
    }
}

