//
// MediaAsset.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MediaAsset: Sendable, Codable, JSONEncodable, Hashable {

    public var w: Int
    public var h: Int
    public var src: String

    public init(w: Int, h: Int, src: String) {
        self.w = w
        self.h = h
        self.src = src
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case w
        case h
        case src
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(w, forKey: .w)
        try container.encode(h, forKey: .h)
        try container.encode(src, forKey: .src)
    }
}

