//
// MetaItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MetaItem: Sendable, Codable, JSONEncodable, Hashable {

    public var name: String
    public var values: [String]

    public init(name: String, values: [String]) {
        self.name = name
        self.values = values
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case values
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(values, forKey: .values)
    }
}

