//
// ModerationSuggestResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ModerationSuggestResponse: Sendable, Codable, Hashable {

    public var status: String
    public var pages: [ModerationPageSearchProjected]?
    public var users: [ModerationUserSearchProjected]?
    public var code: String?

    public init(status: String, pages: [ModerationPageSearchProjected]? = nil, users: [ModerationUserSearchProjected]? = nil, code: String? = nil) {
        self.status = status
        self.pages = pages
        self.users = users
        self.code = code
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case pages
        case users
        case code
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(pages, forKey: .pages)
        try container.encodeIfPresent(users, forKey: .users)
        try container.encodeIfPresent(code, forKey: .code)
    }
}

