//
// ModerationPageSearchProjected.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ModerationPageSearchProjected: Sendable, Codable, Hashable {

    public var urlId: String
    public var url: String
    public var title: String
    public var commentCount: Double

    public init(urlId: String, url: String, title: String, commentCount: Double) {
        self.urlId = urlId
        self.url = url
        self.title = title
        self.commentCount = commentCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case urlId
        case url
        case title
        case commentCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(urlId, forKey: .urlId)
        try container.encode(url, forKey: .url)
        try container.encode(title, forKey: .title)
        try container.encode(commentCount, forKey: .commentCount)
    }
}

