//
// ModerationAPIGetCommentIdsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ModerationAPIGetCommentIdsResponse: Sendable, Codable, Hashable {

    public var ids: [String]
    public var hasMore: Bool
    public var status: APIStatus

    public init(ids: [String], hasMore: Bool, status: APIStatus) {
        self.ids = ids
        self.hasMore = hasMore
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ids
        case hasMore
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ids, forKey: .ids)
        try container.encode(hasMore, forKey: .hasMore)
        try container.encode(status, forKey: .status)
    }
}

