//
// ModerationAPIGetCommentsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ModerationAPIGetCommentsResponse: Sendable, Codable, Hashable {

    public var status: APIStatus
    public var translations: JSONValue
    public var comments: [ModerationAPIComment]
    public var moderationFilter: ModerationFilter?

    public init(status: APIStatus, translations: JSONValue, comments: [ModerationAPIComment], moderationFilter: ModerationFilter? = nil) {
        self.status = status
        self.translations = translations
        self.comments = comments
        self.moderationFilter = moderationFilter
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case translations
        case comments
        case moderationFilter
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(translations, forKey: .translations)
        try container.encode(comments, forKey: .comments)
        try container.encodeIfPresent(moderationFilter, forKey: .moderationFilter)
    }
}

