//
// ModerationCommentSearchResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ModerationCommentSearchResponse: Sendable, Codable, Hashable {

    public var commentCount: Int
    public var status: APIStatus

    public init(commentCount: Int, status: APIStatus) {
        self.commentCount = commentCount
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case commentCount
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(commentCount, forKey: .commentCount)
        try container.encode(status, forKey: .status)
    }
}

