//
// ModerationUserSearchProjected.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ModerationUserSearchProjected: Sendable, Codable, Hashable {

    public var id: String
    public var username: String
    public var displayName: String?
    public var avatarSrc: String?

    public init(id: String, username: String, displayName: String? = nil, avatarSrc: String? = nil) {
        self.id = id
        self.username = username
        self.displayName = displayName
        self.avatarSrc = avatarSrc
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case username
        case displayName
        case avatarSrc
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(username, forKey: .username)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(avatarSrc, forKey: .avatarSrc)
    }
}

