//
// ModerationFilter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ModerationFilter: Sendable, Codable, Hashable {

    public var reviewed: Bool?
    public var approved: Bool?
    public var isSpam: Bool?
    public var isBannedUser: Bool?
    public var isLocked: Bool?
    public var flagCountGt: Double?
    public var userId: String?
    public var urlId: String?
    public var domain: String?
    public var moderationGroupIds: [String]?
    /** Text search terms. Each term is matched case-insensitively against the comment text. A term wrapped in quotes means exact phrase match. */
    public var commentTextSearch: [String]?
    /** Set by the `exact=\"...\"` search syntax. The comment text must equal this value exactly (case-sensitive, full-string), as opposed to the substring matching of commentTextSearch. */
    public var exactCommentText: String?

    public init(reviewed: Bool? = nil, approved: Bool? = nil, isSpam: Bool? = nil, isBannedUser: Bool? = nil, isLocked: Bool? = nil, flagCountGt: Double? = nil, userId: String? = nil, urlId: String? = nil, domain: String? = nil, moderationGroupIds: [String]? = nil, commentTextSearch: [String]? = nil, exactCommentText: String? = nil) {
        self.reviewed = reviewed
        self.approved = approved
        self.isSpam = isSpam
        self.isBannedUser = isBannedUser
        self.isLocked = isLocked
        self.flagCountGt = flagCountGt
        self.userId = userId
        self.urlId = urlId
        self.domain = domain
        self.moderationGroupIds = moderationGroupIds
        self.commentTextSearch = commentTextSearch
        self.exactCommentText = exactCommentText
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reviewed
        case approved
        case isSpam
        case isBannedUser
        case isLocked
        case flagCountGt
        case userId
        case urlId
        case domain
        case moderationGroupIds
        case commentTextSearch
        case exactCommentText
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(reviewed, forKey: .reviewed)
        try container.encodeIfPresent(approved, forKey: .approved)
        try container.encodeIfPresent(isSpam, forKey: .isSpam)
        try container.encodeIfPresent(isBannedUser, forKey: .isBannedUser)
        try container.encodeIfPresent(isLocked, forKey: .isLocked)
        try container.encodeIfPresent(flagCountGt, forKey: .flagCountGt)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(urlId, forKey: .urlId)
        try container.encodeIfPresent(domain, forKey: .domain)
        try container.encodeIfPresent(moderationGroupIds, forKey: .moderationGroupIds)
        try container.encodeIfPresent(commentTextSearch, forKey: .commentTextSearch)
        try container.encodeIfPresent(exactCommentText, forKey: .exactCommentText)
    }
}

