//
// ModerationExportStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ModerationExportStatusResponse: Sendable, Codable, Hashable {

    public var status: String
    public var jobStatus: String
    public var recordCount: Int
    public var downloadUrl: String?

    public init(status: String, jobStatus: String, recordCount: Int, downloadUrl: String? = nil) {
        self.status = status
        self.jobStatus = jobStatus
        self.recordCount = recordCount
        self.downloadUrl = downloadUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case jobStatus
        case recordCount
        case downloadUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(jobStatus, forKey: .jobStatus)
        try container.encode(recordCount, forKey: .recordCount)
        try container.encodeIfPresent(downloadUrl, forKey: .downloadUrl)
    }
}

