//
// ModerationAPIGetLogsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ModerationAPIGetLogsResponse: Sendable, Codable, Hashable {

    public var logs: [ModerationAPICommentLog]
    public var status: APIStatus

    public init(logs: [ModerationAPICommentLog], status: APIStatus) {
        self.logs = logs
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case logs
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(logs, forKey: .logs)
        try container.encode(status, forKey: .status)
    }
}

