//
// ModerationAPIChildCommentsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ModerationAPIChildCommentsResponse: Sendable, Codable, Hashable {

    public var comments: [ModerationAPIComment]
    public var status: APIStatus

    public init(comments: [ModerationAPIComment], status: APIStatus) {
        self.comments = comments
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case comments
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(comments, forKey: .comments)
        try container.encode(status, forKey: .status)
    }
}

