//
// ModerationPageSearchResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ModerationPageSearchResponse: Sendable, Codable, Hashable {

    public var pages: [ModerationPageSearchProjected]
    public var status: APIStatus

    public init(pages: [ModerationPageSearchProjected], status: APIStatus) {
        self.pages = pages
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pages
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pages, forKey: .pages)
        try container.encode(status, forKey: .status)
    }
}

