//
// ModerationSiteSearchResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ModerationSiteSearchResponse: Sendable, Codable, Hashable {

    public var sites: [ModerationSiteSearchProjected]
    public var status: APIStatus

    public init(sites: [ModerationSiteSearchProjected], status: APIStatus) {
        self.sites = sites
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sites
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sites, forKey: .sites)
        try container.encode(status, forKey: .status)
    }
}

