//
// PageUsersOnlineResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PageUsersOnlineResponse: Sendable, Codable, Hashable {

    public var nextAfterUserId: String?
    public var nextAfterName: String?
    public var totalCount: Double
    public var anonCount: Double
    public var users: [PageUserEntry]
    public var status: APIStatus

    public init(nextAfterUserId: String?, nextAfterName: String?, totalCount: Double, anonCount: Double, users: [PageUserEntry], status: APIStatus) {
        self.nextAfterUserId = nextAfterUserId
        self.nextAfterName = nextAfterName
        self.totalCount = totalCount
        self.anonCount = anonCount
        self.users = users
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nextAfterUserId
        case nextAfterName
        case totalCount
        case anonCount
        case users
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(nextAfterUserId, forKey: .nextAfterUserId)
        try container.encode(nextAfterName, forKey: .nextAfterName)
        try container.encode(totalCount, forKey: .totalCount)
        try container.encode(anonCount, forKey: .anonCount)
        try container.encode(users, forKey: .users)
        try container.encode(status, forKey: .status)
    }
}

