//
// PageUsersInfoResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PageUsersInfoResponse: Sendable, Codable, Hashable {

    public var users: [PageUserEntry]
    public var status: APIStatus

    public init(users: [PageUserEntry], status: APIStatus) {
        self.users = users
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case users
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(users, forKey: .users)
        try container.encode(status, forKey: .status)
    }
}

