//
// PostRemoveCommentApiResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PostRemoveCommentApiResponse: Sendable, Codable, Hashable {

    public var action: String
    public var status: String

    public init(action: String, status: String) {
        self.action = action
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case action
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(action, forKey: .action)
        try container.encode(status, forKey: .status)
    }
}

