//
// PublicFeedPostsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PublicFeedPostsResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var feedPosts: [FeedPost]
    public var user: UserSessionInfo?
    public var urlIdWS: String?
    public var userIdWS: String?
    public var tenantIdWS: String?
    public var myReacts: [String: [String: Bool]]?

    public init(status: APIStatus, feedPosts: [FeedPost], user: UserSessionInfo? = nil, urlIdWS: String? = nil, userIdWS: String? = nil, tenantIdWS: String? = nil, myReacts: [String: [String: Bool]]? = nil) {
        self.status = status
        self.feedPosts = feedPosts
        self.user = user
        self.urlIdWS = urlIdWS
        self.userIdWS = userIdWS
        self.tenantIdWS = tenantIdWS
        self.myReacts = myReacts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case feedPosts
        case user
        case urlIdWS
        case userIdWS
        case tenantIdWS
        case myReacts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(feedPosts, forKey: .feedPosts)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encodeIfPresent(urlIdWS, forKey: .urlIdWS)
        try container.encodeIfPresent(userIdWS, forKey: .userIdWS)
        try container.encodeIfPresent(tenantIdWS, forKey: .tenantIdWS)
        try container.encodeIfPresent(myReacts, forKey: .myReacts)
    }
}

