//
// PublicCommentBase.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PublicCommentBase: Sendable, Codable, JSONEncodable, Hashable {

    public var id: String
    public var userId: String?
    public var commenterName: String
    public var commenterLink: String?
    public var commentHTML: String
    public var parentId: String?
    public var date: Date?
    public var votes: Int?
    public var votesUp: Int?
    public var votesDown: Int?
    public var verified: Bool
    public var avatarSrc: String?
    public var hasImages: Bool?
    public var isByAdmin: Bool?
    public var isByModerator: Bool?
    public var isPinned: Bool?
    public var isLocked: Bool?
    public var displayLabel: String?
    public var rating: Double?
    public var badges: [CommentUserBadgeInfo]?
    public var viewCount: Int64?
    public var isDeleted: Bool?
    public var isDeletedUser: Bool?
    public var isSpam: Bool?
    public var anonUserId: String?
    public var feedbackIds: [String]?
    public var requiresVerification: Bool?
    public var editKey: String?
    public var approved: Bool?

    public init(id: String, userId: String? = nil, commenterName: String, commenterLink: String? = nil, commentHTML: String, parentId: String? = nil, date: Date?, votes: Int? = nil, votesUp: Int? = nil, votesDown: Int? = nil, verified: Bool, avatarSrc: String? = nil, hasImages: Bool? = nil, isByAdmin: Bool? = nil, isByModerator: Bool? = nil, isPinned: Bool? = nil, isLocked: Bool? = nil, displayLabel: String? = nil, rating: Double? = nil, badges: [CommentUserBadgeInfo]? = nil, viewCount: Int64? = nil, isDeleted: Bool? = nil, isDeletedUser: Bool? = nil, isSpam: Bool? = nil, anonUserId: String? = nil, feedbackIds: [String]? = nil, requiresVerification: Bool? = nil, editKey: String? = nil, approved: Bool? = nil) {
        self.id = id
        self.userId = userId
        self.commenterName = commenterName
        self.commenterLink = commenterLink
        self.commentHTML = commentHTML
        self.parentId = parentId
        self.date = date
        self.votes = votes
        self.votesUp = votesUp
        self.votesDown = votesDown
        self.verified = verified
        self.avatarSrc = avatarSrc
        self.hasImages = hasImages
        self.isByAdmin = isByAdmin
        self.isByModerator = isByModerator
        self.isPinned = isPinned
        self.isLocked = isLocked
        self.displayLabel = displayLabel
        self.rating = rating
        self.badges = badges
        self.viewCount = viewCount
        self.isDeleted = isDeleted
        self.isDeletedUser = isDeletedUser
        self.isSpam = isSpam
        self.anonUserId = anonUserId
        self.feedbackIds = feedbackIds
        self.requiresVerification = requiresVerification
        self.editKey = editKey
        self.approved = approved
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case userId
        case commenterName
        case commenterLink
        case commentHTML
        case parentId
        case date
        case votes
        case votesUp
        case votesDown
        case verified
        case avatarSrc
        case hasImages
        case isByAdmin
        case isByModerator
        case isPinned
        case isLocked
        case displayLabel
        case rating
        case badges
        case viewCount
        case isDeleted
        case isDeletedUser
        case isSpam
        case anonUserId
        case feedbackIds
        case requiresVerification
        case editKey
        case approved
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encode(commenterName, forKey: .commenterName)
        try container.encodeIfPresent(commenterLink, forKey: .commenterLink)
        try container.encode(commentHTML, forKey: .commentHTML)
        try container.encodeIfPresent(parentId, forKey: .parentId)
        try container.encode(date, forKey: .date)
        try container.encodeIfPresent(votes, forKey: .votes)
        try container.encodeIfPresent(votesUp, forKey: .votesUp)
        try container.encodeIfPresent(votesDown, forKey: .votesDown)
        try container.encode(verified, forKey: .verified)
        try container.encodeIfPresent(avatarSrc, forKey: .avatarSrc)
        try container.encodeIfPresent(hasImages, forKey: .hasImages)
        try container.encodeIfPresent(isByAdmin, forKey: .isByAdmin)
        try container.encodeIfPresent(isByModerator, forKey: .isByModerator)
        try container.encodeIfPresent(isPinned, forKey: .isPinned)
        try container.encodeIfPresent(isLocked, forKey: .isLocked)
        try container.encodeIfPresent(displayLabel, forKey: .displayLabel)
        try container.encodeIfPresent(rating, forKey: .rating)
        try container.encodeIfPresent(badges, forKey: .badges)
        try container.encodeIfPresent(viewCount, forKey: .viewCount)
        try container.encodeIfPresent(isDeleted, forKey: .isDeleted)
        try container.encodeIfPresent(isDeletedUser, forKey: .isDeletedUser)
        try container.encodeIfPresent(isSpam, forKey: .isSpam)
        try container.encodeIfPresent(anonUserId, forKey: .anonUserId)
        try container.encodeIfPresent(feedbackIds, forKey: .feedbackIds)
        try container.encodeIfPresent(requiresVerification, forKey: .requiresVerification)
        try container.encodeIfPresent(editKey, forKey: .editKey)
        try container.encodeIfPresent(approved, forKey: .approved)
    }
}

