//
// PublicComment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PublicComment: Sendable, Codable, JSONEncodable, Hashable {

    public var id: String
    public var userId: String?
    public var commenterName: String
    public var commenterLink: String?
    public var commentHTML: String
    public var parentId: String?
    public var date: Date?
    public var votes: Int?
    public var votesUp: Int?
    public var votesDown: Int?
    public var verified: Bool
    public var avatarSrc: String?
    public var hasImages: Bool?
    public var isByAdmin: Bool?
    public var isByModerator: Bool?
    public var isPinned: Bool?
    public var isLocked: Bool?
    public var displayLabel: String?
    public var rating: Double?
    public var badges: [CommentUserBadgeInfo]?
    public var viewCount: Int64?
    public var isDeleted: Bool?
    public var isDeletedUser: Bool?
    public var isSpam: Bool?
    public var anonUserId: String?
    public var feedbackIds: [String]?
    public var requiresVerification: Bool?
    public var editKey: String?
    public var approved: Bool?
    public var isUnread: Bool?
    public var myVoteId: String?
    public var isVotedDown: Bool?
    public var isVotedUp: Bool?
    /** This is always set when asTree=true */
    public var hasChildren: Bool?
    /** The total nested child count included in this response (may be more available w/ pagination) Only set with asTree=true, otherwise this will be null. */
    public var nestedChildrenCount: Int?
    /** You must ask the API to count children (with asTree=true&countChildren=true), otherwise this will be null. This will be the complete direct child count, whereas children may only contain a subset based on pagination. */
    public var childCount: Int?
    public var children: [PublicComment]?
    public var isFlagged: Bool?
    public var isBlocked: Bool?

    public init(id: String, userId: String? = nil, commenterName: String, commenterLink: String? = nil, commentHTML: String, parentId: String? = nil, date: Date?, votes: Int? = nil, votesUp: Int? = nil, votesDown: Int? = nil, verified: Bool, avatarSrc: String? = nil, hasImages: Bool? = nil, isByAdmin: Bool? = nil, isByModerator: Bool? = nil, isPinned: Bool? = nil, isLocked: Bool? = nil, displayLabel: String? = nil, rating: Double? = nil, badges: [CommentUserBadgeInfo]? = nil, viewCount: Int64? = nil, isDeleted: Bool? = nil, isDeletedUser: Bool? = nil, isSpam: Bool? = nil, anonUserId: String? = nil, feedbackIds: [String]? = nil, requiresVerification: Bool? = nil, editKey: String? = nil, approved: Bool? = nil, isUnread: Bool? = nil, myVoteId: String? = nil, isVotedDown: Bool? = nil, isVotedUp: Bool? = nil, hasChildren: Bool? = nil, nestedChildrenCount: Int? = nil, childCount: Int? = nil, children: [PublicComment]? = nil, isFlagged: Bool? = nil, isBlocked: Bool? = nil) {
        self.id = id
        self.userId = userId
        self.commenterName = commenterName
        self.commenterLink = commenterLink
        self.commentHTML = commentHTML
        self.parentId = parentId
        self.date = date
        self.votes = votes
        self.votesUp = votesUp
        self.votesDown = votesDown
        self.verified = verified
        self.avatarSrc = avatarSrc
        self.hasImages = hasImages
        self.isByAdmin = isByAdmin
        self.isByModerator = isByModerator
        self.isPinned = isPinned
        self.isLocked = isLocked
        self.displayLabel = displayLabel
        self.rating = rating
        self.badges = badges
        self.viewCount = viewCount
        self.isDeleted = isDeleted
        self.isDeletedUser = isDeletedUser
        self.isSpam = isSpam
        self.anonUserId = anonUserId
        self.feedbackIds = feedbackIds
        self.requiresVerification = requiresVerification
        self.editKey = editKey
        self.approved = approved
        self.isUnread = isUnread
        self.myVoteId = myVoteId
        self.isVotedDown = isVotedDown
        self.isVotedUp = isVotedUp
        self.hasChildren = hasChildren
        self.nestedChildrenCount = nestedChildrenCount
        self.childCount = childCount
        self.children = children
        self.isFlagged = isFlagged
        self.isBlocked = isBlocked
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case userId
        case commenterName
        case commenterLink
        case commentHTML
        case parentId
        case date
        case votes
        case votesUp
        case votesDown
        case verified
        case avatarSrc
        case hasImages
        case isByAdmin
        case isByModerator
        case isPinned
        case isLocked
        case displayLabel
        case rating
        case badges
        case viewCount
        case isDeleted
        case isDeletedUser
        case isSpam
        case anonUserId
        case feedbackIds
        case requiresVerification
        case editKey
        case approved
        case isUnread
        case myVoteId
        case isVotedDown
        case isVotedUp
        case hasChildren
        case nestedChildrenCount
        case childCount
        case children
        case isFlagged
        case isBlocked
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encode(commenterName, forKey: .commenterName)
        try container.encodeIfPresent(commenterLink, forKey: .commenterLink)
        try container.encode(commentHTML, forKey: .commentHTML)
        try container.encodeIfPresent(parentId, forKey: .parentId)
        try container.encode(date, forKey: .date)
        try container.encodeIfPresent(votes, forKey: .votes)
        try container.encodeIfPresent(votesUp, forKey: .votesUp)
        try container.encodeIfPresent(votesDown, forKey: .votesDown)
        try container.encode(verified, forKey: .verified)
        try container.encodeIfPresent(avatarSrc, forKey: .avatarSrc)
        try container.encodeIfPresent(hasImages, forKey: .hasImages)
        try container.encodeIfPresent(isByAdmin, forKey: .isByAdmin)
        try container.encodeIfPresent(isByModerator, forKey: .isByModerator)
        try container.encodeIfPresent(isPinned, forKey: .isPinned)
        try container.encodeIfPresent(isLocked, forKey: .isLocked)
        try container.encodeIfPresent(displayLabel, forKey: .displayLabel)
        try container.encodeIfPresent(rating, forKey: .rating)
        try container.encodeIfPresent(badges, forKey: .badges)
        try container.encodeIfPresent(viewCount, forKey: .viewCount)
        try container.encodeIfPresent(isDeleted, forKey: .isDeleted)
        try container.encodeIfPresent(isDeletedUser, forKey: .isDeletedUser)
        try container.encodeIfPresent(isSpam, forKey: .isSpam)
        try container.encodeIfPresent(anonUserId, forKey: .anonUserId)
        try container.encodeIfPresent(feedbackIds, forKey: .feedbackIds)
        try container.encodeIfPresent(requiresVerification, forKey: .requiresVerification)
        try container.encodeIfPresent(editKey, forKey: .editKey)
        try container.encodeIfPresent(approved, forKey: .approved)
        try container.encodeIfPresent(isUnread, forKey: .isUnread)
        try container.encodeIfPresent(myVoteId, forKey: .myVoteId)
        try container.encodeIfPresent(isVotedDown, forKey: .isVotedDown)
        try container.encodeIfPresent(isVotedUp, forKey: .isVotedUp)
        try container.encodeIfPresent(hasChildren, forKey: .hasChildren)
        try container.encodeIfPresent(nestedChildrenCount, forKey: .nestedChildrenCount)
        try container.encodeIfPresent(childCount, forKey: .childCount)
        try container.encodeIfPresent(children, forKey: .children)
        try container.encodeIfPresent(isFlagged, forKey: .isFlagged)
        try container.encodeIfPresent(isBlocked, forKey: .isBlocked)
    }
}

