//
// PublicPage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PublicPage: Sendable, Codable, Hashable {

    public var updatedAt: Int64
    public var commentCount: Int
    public var title: String
    public var url: String
    public var urlId: String

    public init(updatedAt: Int64, commentCount: Int, title: String, url: String, urlId: String) {
        self.updatedAt = updatedAt
        self.commentCount = commentCount
        self.title = title
        self.url = url
        self.urlId = urlId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case updatedAt
        case commentCount
        case title
        case url
        case urlId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(commentCount, forKey: .commentCount)
        try container.encode(title, forKey: .title)
        try container.encode(url, forKey: .url)
        try container.encode(urlId, forKey: .urlId)
    }
}

