//
// PublicBlockFromCommentParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PublicBlockFromCommentParams: Sendable, Codable, JSONEncodable, Hashable {

    /** A list of comment ids to check if are blocked after performing the update. */
    public var commentIds: [String]?

    public init(commentIds: [String]?) {
        self.commentIds = commentIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case commentIds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(commentIds, forKey: .commentIds)
    }
}

