//
// PublicVote.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PublicVote: Sendable, Codable, JSONEncodable, Hashable {

    public var id: String
    public var urlId: String
    public var commentId: String
    public var userId: String
    public var direction: String
    public var createdAt: Date

    public init(id: String, urlId: String, commentId: String, userId: String, direction: String, createdAt: Date) {
        self.id = id
        self.urlId = urlId
        self.commentId = commentId
        self.userId = userId
        self.direction = direction
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case urlId
        case commentId
        case userId
        case direction
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(urlId, forKey: .urlId)
        try container.encode(commentId, forKey: .commentId)
        try container.encode(userId, forKey: .userId)
        try container.encode(direction, forKey: .direction)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PublicVote: Identifiable {}
