//
// PublicAPIDeleteCommentResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PublicAPIDeleteCommentResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var comment: DeletedCommentResultComment?
    public var hardRemoved: Bool
    public var status: APIStatus

    public init(comment: DeletedCommentResultComment? = nil, hardRemoved: Bool, status: APIStatus) {
        self.comment = comment
        self.hardRemoved = hardRemoved
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case comment
        case hardRemoved
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(comment, forKey: .comment)
        try container.encode(hardRemoved, forKey: .hardRemoved)
        try container.encode(status, forKey: .status)
    }
}

