//
// PubSubComment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PubSubComment: Sendable, Codable, JSONEncodable, Hashable {

    public var id: String
    public var tenantId: String
    public var userId: String?
    public var urlId: String
    public var commenterName: String
    public var commenterLink: String?
    public var commentHTML: String
    public var comment: String
    public var parentId: String?
    public var votes: Int?
    public var votesUp: Int?
    public var votesDown: Int?
    public var verified: Bool
    public var avatarSrc: String?
    public var hasImages: Bool?
    public var hasLinks: Bool?
    public var isByAdmin: Bool?
    public var isByModerator: Bool?
    public var isPinned: Bool?
    public var isLocked: Bool?
    public var displayLabel: String?
    public var rating: Double?
    public var badges: [CommentUserBadgeInfo]?
    public var viewCount: Int64?
    public var isDeleted: Bool?
    public var isDeletedUser: Bool?
    public var isSpam: Bool?
    public var anonUserId: String?
    public var feedbackIds: [String]?
    public var flagCount: Int?
    public var domain: String?
    public var url: String
    public var pageTitle: String?
    public var expireAt: Date?
    public var reviewed: Bool?
    public var hasCode: Bool?
    public var approved: Bool
    public var locale: String?
    public var isBannedUser: Bool?
    public var groupIds: [String]?
    public var isLive: Bool?
    public var hidden: Bool?
    public var date: String

    public init(id: String, tenantId: String, userId: String? = nil, urlId: String, commenterName: String, commenterLink: String? = nil, commentHTML: String, comment: String, parentId: String? = nil, votes: Int? = nil, votesUp: Int? = nil, votesDown: Int? = nil, verified: Bool, avatarSrc: String? = nil, hasImages: Bool? = nil, hasLinks: Bool? = nil, isByAdmin: Bool? = nil, isByModerator: Bool? = nil, isPinned: Bool? = nil, isLocked: Bool? = nil, displayLabel: String? = nil, rating: Double? = nil, badges: [CommentUserBadgeInfo]? = nil, viewCount: Int64? = nil, isDeleted: Bool? = nil, isDeletedUser: Bool? = nil, isSpam: Bool? = nil, anonUserId: String? = nil, feedbackIds: [String]? = nil, flagCount: Int? = nil, domain: String? = nil, url: String, pageTitle: String? = nil, expireAt: Date? = nil, reviewed: Bool? = nil, hasCode: Bool? = nil, approved: Bool, locale: String?, isBannedUser: Bool? = nil, groupIds: [String]? = nil, isLive: Bool? = nil, hidden: Bool? = nil, date: String) {
        self.id = id
        self.tenantId = tenantId
        self.userId = userId
        self.urlId = urlId
        self.commenterName = commenterName
        self.commenterLink = commenterLink
        self.commentHTML = commentHTML
        self.comment = comment
        self.parentId = parentId
        self.votes = votes
        self.votesUp = votesUp
        self.votesDown = votesDown
        self.verified = verified
        self.avatarSrc = avatarSrc
        self.hasImages = hasImages
        self.hasLinks = hasLinks
        self.isByAdmin = isByAdmin
        self.isByModerator = isByModerator
        self.isPinned = isPinned
        self.isLocked = isLocked
        self.displayLabel = displayLabel
        self.rating = rating
        self.badges = badges
        self.viewCount = viewCount
        self.isDeleted = isDeleted
        self.isDeletedUser = isDeletedUser
        self.isSpam = isSpam
        self.anonUserId = anonUserId
        self.feedbackIds = feedbackIds
        self.flagCount = flagCount
        self.domain = domain
        self.url = url
        self.pageTitle = pageTitle
        self.expireAt = expireAt
        self.reviewed = reviewed
        self.hasCode = hasCode
        self.approved = approved
        self.locale = locale
        self.isBannedUser = isBannedUser
        self.groupIds = groupIds
        self.isLive = isLive
        self.hidden = hidden
        self.date = date
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case tenantId
        case userId
        case urlId
        case commenterName
        case commenterLink
        case commentHTML
        case comment
        case parentId
        case votes
        case votesUp
        case votesDown
        case verified
        case avatarSrc
        case hasImages
        case hasLinks
        case isByAdmin
        case isByModerator
        case isPinned
        case isLocked
        case displayLabel
        case rating
        case badges
        case viewCount
        case isDeleted
        case isDeletedUser
        case isSpam
        case anonUserId
        case feedbackIds
        case flagCount
        case domain
        case url
        case pageTitle
        case expireAt
        case reviewed
        case hasCode
        case approved
        case locale
        case isBannedUser
        case groupIds
        case isLive
        case hidden
        case date
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encode(urlId, forKey: .urlId)
        try container.encode(commenterName, forKey: .commenterName)
        try container.encodeIfPresent(commenterLink, forKey: .commenterLink)
        try container.encode(commentHTML, forKey: .commentHTML)
        try container.encode(comment, forKey: .comment)
        try container.encodeIfPresent(parentId, forKey: .parentId)
        try container.encodeIfPresent(votes, forKey: .votes)
        try container.encodeIfPresent(votesUp, forKey: .votesUp)
        try container.encodeIfPresent(votesDown, forKey: .votesDown)
        try container.encode(verified, forKey: .verified)
        try container.encodeIfPresent(avatarSrc, forKey: .avatarSrc)
        try container.encodeIfPresent(hasImages, forKey: .hasImages)
        try container.encodeIfPresent(hasLinks, forKey: .hasLinks)
        try container.encodeIfPresent(isByAdmin, forKey: .isByAdmin)
        try container.encodeIfPresent(isByModerator, forKey: .isByModerator)
        try container.encodeIfPresent(isPinned, forKey: .isPinned)
        try container.encodeIfPresent(isLocked, forKey: .isLocked)
        try container.encodeIfPresent(displayLabel, forKey: .displayLabel)
        try container.encodeIfPresent(rating, forKey: .rating)
        try container.encodeIfPresent(badges, forKey: .badges)
        try container.encodeIfPresent(viewCount, forKey: .viewCount)
        try container.encodeIfPresent(isDeleted, forKey: .isDeleted)
        try container.encodeIfPresent(isDeletedUser, forKey: .isDeletedUser)
        try container.encodeIfPresent(isSpam, forKey: .isSpam)
        try container.encodeIfPresent(anonUserId, forKey: .anonUserId)
        try container.encodeIfPresent(feedbackIds, forKey: .feedbackIds)
        try container.encodeIfPresent(flagCount, forKey: .flagCount)
        try container.encodeIfPresent(domain, forKey: .domain)
        try container.encode(url, forKey: .url)
        try container.encodeIfPresent(pageTitle, forKey: .pageTitle)
        try container.encodeIfPresent(expireAt, forKey: .expireAt)
        try container.encodeIfPresent(reviewed, forKey: .reviewed)
        try container.encodeIfPresent(hasCode, forKey: .hasCode)
        try container.encode(approved, forKey: .approved)
        try container.encode(locale, forKey: .locale)
        try container.encodeIfPresent(isBannedUser, forKey: .isBannedUser)
        try container.encodeIfPresent(groupIds, forKey: .groupIds)
        try container.encodeIfPresent(isLive, forKey: .isLive)
        try container.encodeIfPresent(hidden, forKey: .hidden)
        try container.encode(date, forKey: .date)
    }
}

