//
// PubSubVote.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PubSubVote: Sendable, Codable, JSONEncodable, Hashable {

    public var id: String
    public var tenantId: String
    public var urlId: String
    public var urlIdRaw: String
    public var commentId: String
    public var userId: String?
    public var direction: Int
    public var createdAt: Int64
    public var verificationId: String?

    public init(id: String, tenantId: String, urlId: String, urlIdRaw: String, commentId: String, userId: String? = nil, direction: Int, createdAt: Int64, verificationId: String?) {
        self.id = id
        self.tenantId = tenantId
        self.urlId = urlId
        self.urlIdRaw = urlIdRaw
        self.commentId = commentId
        self.userId = userId
        self.direction = direction
        self.createdAt = createdAt
        self.verificationId = verificationId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case tenantId
        case urlId
        case urlIdRaw
        case commentId
        case userId
        case direction
        case createdAt
        case verificationId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(urlId, forKey: .urlId)
        try container.encode(urlIdRaw, forKey: .urlIdRaw)
        try container.encode(commentId, forKey: .commentId)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encode(direction, forKey: .direction)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(verificationId, forKey: .verificationId)
    }
}

