//
// QueryPredicate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct QueryPredicate: Sendable, Codable, JSONEncodable, Hashable {

    public enum Operator: String, Sendable, Codable, CaseIterable {
        case eq = "eq"
        case notEq = "not_eq"
        case greaterThan = "greater_than"
        case lessThan = "less_than"
        case contains = "contains"
    }
    public var key: String
    public var value: QueryPredicateValue
    public var _operator: Operator

    public init(key: String, value: QueryPredicateValue, _operator: Operator) {
        self.key = key
        self.value = value
        self._operator = _operator
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case key
        case value
        case _operator = "operator"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(key, forKey: .key)
        try container.encode(value, forKey: .value)
        try container.encode(_operator, forKey: ._operator)
    }
}

