//
// QuestionDatum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct QuestionDatum: Sendable, Codable, JSONEncodable, Hashable {

    /** Construct a type with a set of properties K of type T */
    public var v: [String: Double]
    public var total: Int64

    public init(v: [String: Double], total: Int64) {
        self.v = v
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case v
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(v, forKey: .v)
        try container.encode(total, forKey: .total)
    }
}

