//
// QuestionConfigCustomOptionsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct QuestionConfigCustomOptionsInner: Sendable, Codable, JSONEncodable, Hashable {

    public var imageSrc: String
    public var name: String

    public init(imageSrc: String, name: String) {
        self.imageSrc = imageSrc
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case imageSrc
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(imageSrc, forKey: .imageSrc)
        try container.encode(name, forKey: .name)
    }
}

