//
// QuestionResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct QuestionResult: Sendable, Codable, JSONEncodable, Hashable {

    public var id: String
    public var tenantId: String
    public var urlId: String
    public var anonUserId: String
    public var userId: String
    public var createdAt: Date
    public var value: Int
    public var commentId: String?
    public var questionId: String
    public var meta: [MetaItem]?
    public var ipHash: String

    public init(id: String, tenantId: String, urlId: String, anonUserId: String, userId: String, createdAt: Date, value: Int, commentId: String? = nil, questionId: String, meta: [MetaItem]? = nil, ipHash: String) {
        self.id = id
        self.tenantId = tenantId
        self.urlId = urlId
        self.anonUserId = anonUserId
        self.userId = userId
        self.createdAt = createdAt
        self.value = value
        self.commentId = commentId
        self.questionId = questionId
        self.meta = meta
        self.ipHash = ipHash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case tenantId
        case urlId
        case anonUserId
        case userId
        case createdAt
        case value
        case commentId
        case questionId
        case meta
        case ipHash
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(urlId, forKey: .urlId)
        try container.encode(anonUserId, forKey: .anonUserId)
        try container.encode(userId, forKey: .userId)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(value, forKey: .value)
        try container.encodeIfPresent(commentId, forKey: .commentId)
        try container.encode(questionId, forKey: .questionId)
        try container.encodeIfPresent(meta, forKey: .meta)
        try container.encode(ipHash, forKey: .ipHash)
    }
}

