//
// QuestionSubQuestionVisibility.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum QuestionSubQuestionVisibility: Int, Sendable, Codable, CaseIterable {
    case _0 = 0
    case _1 = 1
}
