//
// QuestionResultAggregationOverall.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct QuestionResultAggregationOverall: Sendable, Codable, JSONEncodable, Hashable {

    /** Construct a type with a set of properties K of type T */
    public var dataByDateBucket: [String: QuestionDatum]?
    /** Construct a type with a set of properties K of type T */
    public var dataByUrlId: [String: QuestionDatum]?
    public var countsByValue: [String: Int]?
    public var total: Int64
    public var average: Double?
    public var createdAt: Date

    public init(dataByDateBucket: [String: QuestionDatum]? = nil, dataByUrlId: [String: QuestionDatum]? = nil, countsByValue: [String: Int]? = nil, total: Int64, average: Double? = nil, createdAt: Date) {
        self.dataByDateBucket = dataByDateBucket
        self.dataByUrlId = dataByUrlId
        self.countsByValue = countsByValue
        self.total = total
        self.average = average
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dataByDateBucket
        case dataByUrlId
        case countsByValue
        case total
        case average
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(dataByDateBucket, forKey: .dataByDateBucket)
        try container.encodeIfPresent(dataByUrlId, forKey: .dataByUrlId)
        try container.encodeIfPresent(countsByValue, forKey: .countsByValue)
        try container.encode(total, forKey: .total)
        try container.encodeIfPresent(average, forKey: .average)
        try container.encode(createdAt, forKey: .createdAt)
    }
}

