//
// ReactBodyParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ReactBodyParams: Sendable, Codable, JSONEncodable, Hashable {

    public var reactType: String?

    public init(reactType: String? = nil) {
        self.reactType = reactType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reactType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(reactType, forKey: .reactType)
    }
}

