//
// ReactFeedPostResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ReactFeedPostResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var reactType: String
    public var isUndo: Bool

    public init(status: APIStatus, reactType: String, isUndo: Bool) {
        self.status = status
        self.reactType = reactType
        self.isUndo = isUndo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case reactType
        case isUndo
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(reactType, forKey: .reactType)
        try container.encode(isUndo, forKey: .isUndo)
    }
}

