//
// RecordStringBeforeStringOrNullAfterStringOrNullValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RecordStringBeforeStringOrNullAfterStringOrNullValue: Sendable, Codable, JSONEncodable, Hashable {

    public var after: String
    public var before: String

    public init(after: String, before: String) {
        self.after = after
        self.before = before
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case after
        case before
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(after, forKey: .after)
        try container.encode(before, forKey: .before)
    }
}

