//
// RecordStringBeforeStringOrNullAfterStringOrNullValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RecordStringBeforeStringOrNullAfterStringOrNullValue: Sendable, Codable, ParameterConvertible, Hashable {

    public var after: String?
    public var before: String?

    public init(after: String? = nil, before: String? = nil) {
        self.after = after
        self.before = before
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case after
        case before
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(after, forKey: .after)
        try container.encodeIfPresent(before, forKey: .before)
    }
}

