//
// RenderEmailTemplateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RenderEmailTemplateResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var html: String

    public init(status: APIStatus, html: String) {
        self.status = status
        self.html = html
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case html
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(html, forKey: .html)
    }
}

