//
// RenderEmailTemplateBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RenderEmailTemplateBody: Sendable, Codable, JSONEncodable, Hashable {

    public var emailTemplateId: String
    public var ejs: String
    /** Construct a type with a set of properties K of type T */
    public var testData: [String: JSONValue]?
    /** Construct a type with a set of properties K of type T */
    public var translationOverridesByLocale: [String: Dictionary]?

    public init(emailTemplateId: String, ejs: String, testData: [String: JSONValue]? = nil, translationOverridesByLocale: [String: Dictionary]? = nil) {
        self.emailTemplateId = emailTemplateId
        self.ejs = ejs
        self.testData = testData
        self.translationOverridesByLocale = translationOverridesByLocale
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case emailTemplateId
        case ejs
        case testData
        case translationOverridesByLocale
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(emailTemplateId, forKey: .emailTemplateId)
        try container.encode(ejs, forKey: .ejs)
        try container.encodeIfPresent(testData, forKey: .testData)
        try container.encodeIfPresent(translationOverridesByLocale, forKey: .translationOverridesByLocale)
    }
}

