//
// RepeatCommentHandlingAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum RepeatCommentHandlingAction: Double, Sendable, Codable, JSONEncodable, CaseIterable {
    case _0 = 0
    case _1 = 1
    case _2 = 2
}
