//
// RepeatCommentCheckIgnoredReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum RepeatCommentCheckIgnoredReason: Double, Sendable, Codable, JSONEncodable, CaseIterable {
    case _0 = 0
    case _1 = 1
    case _2 = 2
    case _3 = 3
    case _4 = 4
    case _5 = 5
    case _6 = 6
}
