//
// ReplaceTenantUserBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ReplaceTenantUserBody: Sendable, Codable, JSONEncodable, Hashable {

    public var username: String
    public var email: String
    public var displayName: String?
    public var websiteUrl: String?
    public var signUpDate: Double?
    public var locale: String?
    public var verified: Bool?
    public var loginCount: Double?
    public var optedInNotifications: Bool?
    public var optedInTenantNotifications: Bool?
    public var hideAccountCode: Bool?
    public var avatarSrc: String?
    public var isHelpRequestAdmin: Bool?
    public var isAccountOwner: Bool?
    public var isAdminAdmin: Bool?
    public var isBillingAdmin: Bool?
    public var isAnalyticsAdmin: Bool?
    public var isCustomizationAdmin: Bool?
    public var isManageDataAdmin: Bool?
    public var isCommentModeratorAdmin: Bool?
    public var isAPIAdmin: Bool?
    public var moderatorIds: [String]?
    public var digestEmailFrequency: Double?
    public var displayLabel: String?
    public var createdFromUrlId: String?
    public var createdFromTenantId: String?
    public var lastLoginDate: Double?
    public var karma: Double?

    public init(username: String, email: String, displayName: String? = nil, websiteUrl: String? = nil, signUpDate: Double? = nil, locale: String? = nil, verified: Bool? = nil, loginCount: Double? = nil, optedInNotifications: Bool? = nil, optedInTenantNotifications: Bool? = nil, hideAccountCode: Bool? = nil, avatarSrc: String? = nil, isHelpRequestAdmin: Bool? = nil, isAccountOwner: Bool? = nil, isAdminAdmin: Bool? = nil, isBillingAdmin: Bool? = nil, isAnalyticsAdmin: Bool? = nil, isCustomizationAdmin: Bool? = nil, isManageDataAdmin: Bool? = nil, isCommentModeratorAdmin: Bool? = nil, isAPIAdmin: Bool? = nil, moderatorIds: [String]? = nil, digestEmailFrequency: Double? = nil, displayLabel: String? = nil, createdFromUrlId: String? = nil, createdFromTenantId: String? = nil, lastLoginDate: Double? = nil, karma: Double? = nil) {
        self.username = username
        self.email = email
        self.displayName = displayName
        self.websiteUrl = websiteUrl
        self.signUpDate = signUpDate
        self.locale = locale
        self.verified = verified
        self.loginCount = loginCount
        self.optedInNotifications = optedInNotifications
        self.optedInTenantNotifications = optedInTenantNotifications
        self.hideAccountCode = hideAccountCode
        self.avatarSrc = avatarSrc
        self.isHelpRequestAdmin = isHelpRequestAdmin
        self.isAccountOwner = isAccountOwner
        self.isAdminAdmin = isAdminAdmin
        self.isBillingAdmin = isBillingAdmin
        self.isAnalyticsAdmin = isAnalyticsAdmin
        self.isCustomizationAdmin = isCustomizationAdmin
        self.isManageDataAdmin = isManageDataAdmin
        self.isCommentModeratorAdmin = isCommentModeratorAdmin
        self.isAPIAdmin = isAPIAdmin
        self.moderatorIds = moderatorIds
        self.digestEmailFrequency = digestEmailFrequency
        self.displayLabel = displayLabel
        self.createdFromUrlId = createdFromUrlId
        self.createdFromTenantId = createdFromTenantId
        self.lastLoginDate = lastLoginDate
        self.karma = karma
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case username
        case email
        case displayName
        case websiteUrl
        case signUpDate
        case locale
        case verified
        case loginCount
        case optedInNotifications
        case optedInTenantNotifications
        case hideAccountCode
        case avatarSrc
        case isHelpRequestAdmin
        case isAccountOwner
        case isAdminAdmin
        case isBillingAdmin
        case isAnalyticsAdmin
        case isCustomizationAdmin
        case isManageDataAdmin
        case isCommentModeratorAdmin
        case isAPIAdmin
        case moderatorIds
        case digestEmailFrequency
        case displayLabel
        case createdFromUrlId
        case createdFromTenantId
        case lastLoginDate
        case karma
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(username, forKey: .username)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(websiteUrl, forKey: .websiteUrl)
        try container.encodeIfPresent(signUpDate, forKey: .signUpDate)
        try container.encodeIfPresent(locale, forKey: .locale)
        try container.encodeIfPresent(verified, forKey: .verified)
        try container.encodeIfPresent(loginCount, forKey: .loginCount)
        try container.encodeIfPresent(optedInNotifications, forKey: .optedInNotifications)
        try container.encodeIfPresent(optedInTenantNotifications, forKey: .optedInTenantNotifications)
        try container.encodeIfPresent(hideAccountCode, forKey: .hideAccountCode)
        try container.encodeIfPresent(avatarSrc, forKey: .avatarSrc)
        try container.encodeIfPresent(isHelpRequestAdmin, forKey: .isHelpRequestAdmin)
        try container.encodeIfPresent(isAccountOwner, forKey: .isAccountOwner)
        try container.encodeIfPresent(isAdminAdmin, forKey: .isAdminAdmin)
        try container.encodeIfPresent(isBillingAdmin, forKey: .isBillingAdmin)
        try container.encodeIfPresent(isAnalyticsAdmin, forKey: .isAnalyticsAdmin)
        try container.encodeIfPresent(isCustomizationAdmin, forKey: .isCustomizationAdmin)
        try container.encodeIfPresent(isManageDataAdmin, forKey: .isManageDataAdmin)
        try container.encodeIfPresent(isCommentModeratorAdmin, forKey: .isCommentModeratorAdmin)
        try container.encodeIfPresent(isAPIAdmin, forKey: .isAPIAdmin)
        try container.encodeIfPresent(moderatorIds, forKey: .moderatorIds)
        try container.encodeIfPresent(digestEmailFrequency, forKey: .digestEmailFrequency)
        try container.encodeIfPresent(displayLabel, forKey: .displayLabel)
        try container.encodeIfPresent(createdFromUrlId, forKey: .createdFromUrlId)
        try container.encodeIfPresent(createdFromTenantId, forKey: .createdFromTenantId)
        try container.encodeIfPresent(lastLoginDate, forKey: .lastLoginDate)
        try container.encodeIfPresent(karma, forKey: .karma)
    }
}

