//
// SaveComment200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SaveComment200Response: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var comment: FComment
    public var user: UserSessionInfo?
    /** Construct a type with a set of properties K of type T */
    public var moduleData: [String: JSONValue]?
    public var reason: String
    public var code: String
    public var secondaryCode: String?
    public var bannedUntil: Int64?
    public var maxCharacterLength: Int?
    public var translatedError: String?
    public var customConfig: CustomConfigParameters?

    public init(status: APIStatus, comment: FComment, user: UserSessionInfo?, moduleData: [String: JSONValue]? = nil, reason: String, code: String, secondaryCode: String? = nil, bannedUntil: Int64? = nil, maxCharacterLength: Int? = nil, translatedError: String? = nil, customConfig: CustomConfigParameters? = nil) {
        self.status = status
        self.comment = comment
        self.user = user
        self.moduleData = moduleData
        self.reason = reason
        self.code = code
        self.secondaryCode = secondaryCode
        self.bannedUntil = bannedUntil
        self.maxCharacterLength = maxCharacterLength
        self.translatedError = translatedError
        self.customConfig = customConfig
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case comment
        case user
        case moduleData
        case reason
        case code
        case secondaryCode
        case bannedUntil
        case maxCharacterLength
        case translatedError
        case customConfig
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(comment, forKey: .comment)
        try container.encode(user, forKey: .user)
        try container.encodeIfPresent(moduleData, forKey: .moduleData)
        try container.encode(reason, forKey: .reason)
        try container.encode(code, forKey: .code)
        try container.encodeIfPresent(secondaryCode, forKey: .secondaryCode)
        try container.encodeIfPresent(bannedUntil, forKey: .bannedUntil)
        try container.encodeIfPresent(maxCharacterLength, forKey: .maxCharacterLength)
        try container.encodeIfPresent(translatedError, forKey: .translatedError)
        try container.encodeIfPresent(customConfig, forKey: .customConfig)
    }
}

