//
// SaveCommentResponseOptimized.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SaveCommentResponseOptimized: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var comment: PublicComment
    public var user: UserSessionInfo?
    /** Construct a type with a set of properties K of type T */
    public var moduleData: [String: JSONValue]?

    public init(status: APIStatus, comment: PublicComment, user: UserSessionInfo?, moduleData: [String: JSONValue]? = nil) {
        self.status = status
        self.comment = comment
        self.user = user
        self.moduleData = moduleData
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case comment
        case user
        case moduleData
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(comment, forKey: .comment)
        try container.encode(user, forKey: .user)
        try container.encodeIfPresent(moduleData, forKey: .moduleData)
    }
}

