//
// SearchUsersSectionedResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SearchUsersSectionedResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var status: APIStatus
    public var sections: [UserSearchSectionResult]

    public init(status: APIStatus, sections: [UserSearchSectionResult]) {
        self.status = status
        self.sections = sections
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case sections
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(sections, forKey: .sections)
    }
}

