//
// SearchUsersResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SearchUsersResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var users: [UserSearchResult]

    public init(status: APIStatus, users: [UserSearchResult]) {
        self.status = status
        self.users = users
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case users
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(users, forKey: .users)
    }
}

