//
// SetCommentTextResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SetCommentTextResponse: Sendable, Codable, Hashable {

    public var newCommentTextHTML: String
    public var status: APIStatus

    public init(newCommentTextHTML: String, status: APIStatus) {
        self.newCommentTextHTML = newCommentTextHTML
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case newCommentTextHTML
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(newCommentTextHTML, forKey: .newCommentTextHTML)
        try container.encode(status, forKey: .status)
    }
}

