//
// SetCommentTextResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SetCommentTextResult: Sendable, Codable, JSONEncodable, Hashable {

    public var approved: Bool
    public var commentHTML: String

    public init(approved: Bool, commentHTML: String) {
        self.approved = approved
        self.commentHTML = commentHTML
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case approved
        case commentHTML
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(approved, forKey: .approved)
        try container.encode(commentHTML, forKey: .commentHTML)
    }
}

