//
// SetCommentTextParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SetCommentTextParams: Sendable, Codable, Hashable {

    public var comment: String

    public init(comment: String) {
        self.comment = comment
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case comment
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(comment, forKey: .comment)
    }
}

