//
// SizePreset.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum SizePreset: String, Sendable, Codable, CaseIterable {
    case _default = "Default"
    case crossPlatform = "CrossPlatform"
}
