//
// SortDirections.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum SortDirections: String, Sendable, Codable, CaseIterable {
    case of = "OF"
    case nf = "NF"
    case mr = "MR"
}
