//
// SORTDIR.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum SORTDIR: String, Sendable, Codable, CaseIterable {
    case asc = "ASC"
    case desc = "DESC"
}
