//
// SpamRule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SpamRule: Sendable, Codable, JSONEncodable, Hashable {

    public enum Actions: String, Sendable, Codable, CaseIterable {
        case spam = "spam"
        case notSpam = "not-spam"
        case ignoreRepeat = "ignore-repeat"
    }
    public var actions: [Actions]
    public var commentContains: String?

    public init(actions: [Actions], commentContains: String? = nil) {
        self.actions = actions
        self.commentContains = commentContains
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case actions
        case commentContains
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(actions, forKey: .actions)
        try container.encodeIfPresent(commentContains, forKey: .commentContains)
    }
}

