//
// TenantPackage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TenantPackage: Sendable, Codable, JSONEncodable, Hashable {

    public var id: String
    public var name: String
    public var tenantId: String
    public var createdAt: Date
    public var monthlyCostUSD: Double?
    public var yearlyCostUSD: Double?
    public var monthlyStripePlanId: String?
    public var yearlyStripePlanId: String?
    public var maxMonthlyPageLoads: Double
    public var maxMonthlyAPICredits: Double
    public var maxMonthlySmallWidgetsCredits: Double
    public var maxMonthlyComments: Double
    public var maxConcurrentUsers: Double
    public var maxTenantUsers: Double
    public var maxSSOUsers: Double
    public var maxModerators: Double
    public var maxDomains: Double
    public var maxWhiteLabeledTenants: Double
    public var maxMonthlyEventLogRequests: Double
    public var hasWhiteLabeling: Bool
    public var hasDebranding: Bool
    public var hasLLMSpamDetection: Bool
    public var forWhoText: String
    public var featureTaglines: [String]
    public var hasAuditing: Bool
    public var hasFlexPricing: Bool
    public var enableSAML: Bool?
    public var flexPageLoadCostCents: Double?
    public var flexPageLoadUnit: Double?
    public var flexCommentCostCents: Double?
    public var flexCommentUnit: Double?
    public var flexSSOUserCostCents: Double?
    public var flexSSOUserUnit: Double?
    public var flexAPICreditCostCents: Double?
    public var flexAPICreditUnit: Double?
    public var flexSmallWidgetsCreditCostCents: Double?
    public var flexSmallWidgetsCreditUnit: Double?
    public var flexModeratorCostCents: Double?
    public var flexModeratorUnit: Double?
    public var flexAdminCostCents: Double?
    public var flexAdminUnit: Double?
    public var flexDomainCostCents: Double?
    public var flexDomainUnit: Double?
    public var flexChatGPTCostCents: Double?
    public var flexChatGPTUnit: Double?
    public var flexMinimumCostCents: Double?
    public var flexManagedTenantCostCents: Double?
    public var flexSSOAdminCostCents: Double?
    public var flexSSOAdminUnit: Double?
    public var flexSSOModeratorCostCents: Double?
    public var flexSSOModeratorUnit: Double?
    public var isSSOBillingMonthlyActiveUsers: Bool?

    public init(id: String, name: String, tenantId: String, createdAt: Date, monthlyCostUSD: Double?, yearlyCostUSD: Double?, monthlyStripePlanId: String?, yearlyStripePlanId: String?, maxMonthlyPageLoads: Double, maxMonthlyAPICredits: Double, maxMonthlySmallWidgetsCredits: Double, maxMonthlyComments: Double, maxConcurrentUsers: Double, maxTenantUsers: Double, maxSSOUsers: Double, maxModerators: Double, maxDomains: Double, maxWhiteLabeledTenants: Double, maxMonthlyEventLogRequests: Double, hasWhiteLabeling: Bool, hasDebranding: Bool, hasLLMSpamDetection: Bool, forWhoText: String, featureTaglines: [String], hasAuditing: Bool, hasFlexPricing: Bool, enableSAML: Bool? = nil, flexPageLoadCostCents: Double? = nil, flexPageLoadUnit: Double? = nil, flexCommentCostCents: Double? = nil, flexCommentUnit: Double? = nil, flexSSOUserCostCents: Double? = nil, flexSSOUserUnit: Double? = nil, flexAPICreditCostCents: Double? = nil, flexAPICreditUnit: Double? = nil, flexSmallWidgetsCreditCostCents: Double? = nil, flexSmallWidgetsCreditUnit: Double? = nil, flexModeratorCostCents: Double? = nil, flexModeratorUnit: Double? = nil, flexAdminCostCents: Double? = nil, flexAdminUnit: Double? = nil, flexDomainCostCents: Double? = nil, flexDomainUnit: Double? = nil, flexChatGPTCostCents: Double? = nil, flexChatGPTUnit: Double? = nil, flexMinimumCostCents: Double? = nil, flexManagedTenantCostCents: Double? = nil, flexSSOAdminCostCents: Double? = nil, flexSSOAdminUnit: Double? = nil, flexSSOModeratorCostCents: Double? = nil, flexSSOModeratorUnit: Double? = nil, isSSOBillingMonthlyActiveUsers: Bool? = nil) {
        self.id = id
        self.name = name
        self.tenantId = tenantId
        self.createdAt = createdAt
        self.monthlyCostUSD = monthlyCostUSD
        self.yearlyCostUSD = yearlyCostUSD
        self.monthlyStripePlanId = monthlyStripePlanId
        self.yearlyStripePlanId = yearlyStripePlanId
        self.maxMonthlyPageLoads = maxMonthlyPageLoads
        self.maxMonthlyAPICredits = maxMonthlyAPICredits
        self.maxMonthlySmallWidgetsCredits = maxMonthlySmallWidgetsCredits
        self.maxMonthlyComments = maxMonthlyComments
        self.maxConcurrentUsers = maxConcurrentUsers
        self.maxTenantUsers = maxTenantUsers
        self.maxSSOUsers = maxSSOUsers
        self.maxModerators = maxModerators
        self.maxDomains = maxDomains
        self.maxWhiteLabeledTenants = maxWhiteLabeledTenants
        self.maxMonthlyEventLogRequests = maxMonthlyEventLogRequests
        self.hasWhiteLabeling = hasWhiteLabeling
        self.hasDebranding = hasDebranding
        self.hasLLMSpamDetection = hasLLMSpamDetection
        self.forWhoText = forWhoText
        self.featureTaglines = featureTaglines
        self.hasAuditing = hasAuditing
        self.hasFlexPricing = hasFlexPricing
        self.enableSAML = enableSAML
        self.flexPageLoadCostCents = flexPageLoadCostCents
        self.flexPageLoadUnit = flexPageLoadUnit
        self.flexCommentCostCents = flexCommentCostCents
        self.flexCommentUnit = flexCommentUnit
        self.flexSSOUserCostCents = flexSSOUserCostCents
        self.flexSSOUserUnit = flexSSOUserUnit
        self.flexAPICreditCostCents = flexAPICreditCostCents
        self.flexAPICreditUnit = flexAPICreditUnit
        self.flexSmallWidgetsCreditCostCents = flexSmallWidgetsCreditCostCents
        self.flexSmallWidgetsCreditUnit = flexSmallWidgetsCreditUnit
        self.flexModeratorCostCents = flexModeratorCostCents
        self.flexModeratorUnit = flexModeratorUnit
        self.flexAdminCostCents = flexAdminCostCents
        self.flexAdminUnit = flexAdminUnit
        self.flexDomainCostCents = flexDomainCostCents
        self.flexDomainUnit = flexDomainUnit
        self.flexChatGPTCostCents = flexChatGPTCostCents
        self.flexChatGPTUnit = flexChatGPTUnit
        self.flexMinimumCostCents = flexMinimumCostCents
        self.flexManagedTenantCostCents = flexManagedTenantCostCents
        self.flexSSOAdminCostCents = flexSSOAdminCostCents
        self.flexSSOAdminUnit = flexSSOAdminUnit
        self.flexSSOModeratorCostCents = flexSSOModeratorCostCents
        self.flexSSOModeratorUnit = flexSSOModeratorUnit
        self.isSSOBillingMonthlyActiveUsers = isSSOBillingMonthlyActiveUsers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case name
        case tenantId
        case createdAt
        case monthlyCostUSD
        case yearlyCostUSD
        case monthlyStripePlanId
        case yearlyStripePlanId
        case maxMonthlyPageLoads
        case maxMonthlyAPICredits
        case maxMonthlySmallWidgetsCredits
        case maxMonthlyComments
        case maxConcurrentUsers
        case maxTenantUsers
        case maxSSOUsers
        case maxModerators
        case maxDomains
        case maxWhiteLabeledTenants
        case maxMonthlyEventLogRequests
        case hasWhiteLabeling
        case hasDebranding
        case hasLLMSpamDetection
        case forWhoText
        case featureTaglines
        case hasAuditing
        case hasFlexPricing
        case enableSAML
        case flexPageLoadCostCents
        case flexPageLoadUnit
        case flexCommentCostCents
        case flexCommentUnit
        case flexSSOUserCostCents
        case flexSSOUserUnit
        case flexAPICreditCostCents
        case flexAPICreditUnit
        case flexSmallWidgetsCreditCostCents
        case flexSmallWidgetsCreditUnit
        case flexModeratorCostCents
        case flexModeratorUnit
        case flexAdminCostCents
        case flexAdminUnit
        case flexDomainCostCents
        case flexDomainUnit
        case flexChatGPTCostCents
        case flexChatGPTUnit
        case flexMinimumCostCents
        case flexManagedTenantCostCents
        case flexSSOAdminCostCents
        case flexSSOAdminUnit
        case flexSSOModeratorCostCents
        case flexSSOModeratorUnit
        case isSSOBillingMonthlyActiveUsers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(monthlyCostUSD, forKey: .monthlyCostUSD)
        try container.encode(yearlyCostUSD, forKey: .yearlyCostUSD)
        try container.encode(monthlyStripePlanId, forKey: .monthlyStripePlanId)
        try container.encode(yearlyStripePlanId, forKey: .yearlyStripePlanId)
        try container.encode(maxMonthlyPageLoads, forKey: .maxMonthlyPageLoads)
        try container.encode(maxMonthlyAPICredits, forKey: .maxMonthlyAPICredits)
        try container.encode(maxMonthlySmallWidgetsCredits, forKey: .maxMonthlySmallWidgetsCredits)
        try container.encode(maxMonthlyComments, forKey: .maxMonthlyComments)
        try container.encode(maxConcurrentUsers, forKey: .maxConcurrentUsers)
        try container.encode(maxTenantUsers, forKey: .maxTenantUsers)
        try container.encode(maxSSOUsers, forKey: .maxSSOUsers)
        try container.encode(maxModerators, forKey: .maxModerators)
        try container.encode(maxDomains, forKey: .maxDomains)
        try container.encode(maxWhiteLabeledTenants, forKey: .maxWhiteLabeledTenants)
        try container.encode(maxMonthlyEventLogRequests, forKey: .maxMonthlyEventLogRequests)
        try container.encode(hasWhiteLabeling, forKey: .hasWhiteLabeling)
        try container.encode(hasDebranding, forKey: .hasDebranding)
        try container.encode(hasLLMSpamDetection, forKey: .hasLLMSpamDetection)
        try container.encode(forWhoText, forKey: .forWhoText)
        try container.encode(featureTaglines, forKey: .featureTaglines)
        try container.encode(hasAuditing, forKey: .hasAuditing)
        try container.encode(hasFlexPricing, forKey: .hasFlexPricing)
        try container.encodeIfPresent(enableSAML, forKey: .enableSAML)
        try container.encodeIfPresent(flexPageLoadCostCents, forKey: .flexPageLoadCostCents)
        try container.encodeIfPresent(flexPageLoadUnit, forKey: .flexPageLoadUnit)
        try container.encodeIfPresent(flexCommentCostCents, forKey: .flexCommentCostCents)
        try container.encodeIfPresent(flexCommentUnit, forKey: .flexCommentUnit)
        try container.encodeIfPresent(flexSSOUserCostCents, forKey: .flexSSOUserCostCents)
        try container.encodeIfPresent(flexSSOUserUnit, forKey: .flexSSOUserUnit)
        try container.encodeIfPresent(flexAPICreditCostCents, forKey: .flexAPICreditCostCents)
        try container.encodeIfPresent(flexAPICreditUnit, forKey: .flexAPICreditUnit)
        try container.encodeIfPresent(flexSmallWidgetsCreditCostCents, forKey: .flexSmallWidgetsCreditCostCents)
        try container.encodeIfPresent(flexSmallWidgetsCreditUnit, forKey: .flexSmallWidgetsCreditUnit)
        try container.encodeIfPresent(flexModeratorCostCents, forKey: .flexModeratorCostCents)
        try container.encodeIfPresent(flexModeratorUnit, forKey: .flexModeratorUnit)
        try container.encodeIfPresent(flexAdminCostCents, forKey: .flexAdminCostCents)
        try container.encodeIfPresent(flexAdminUnit, forKey: .flexAdminUnit)
        try container.encodeIfPresent(flexDomainCostCents, forKey: .flexDomainCostCents)
        try container.encodeIfPresent(flexDomainUnit, forKey: .flexDomainUnit)
        try container.encodeIfPresent(flexChatGPTCostCents, forKey: .flexChatGPTCostCents)
        try container.encodeIfPresent(flexChatGPTUnit, forKey: .flexChatGPTUnit)
        try container.encodeIfPresent(flexMinimumCostCents, forKey: .flexMinimumCostCents)
        try container.encodeIfPresent(flexManagedTenantCostCents, forKey: .flexManagedTenantCostCents)
        try container.encodeIfPresent(flexSSOAdminCostCents, forKey: .flexSSOAdminCostCents)
        try container.encodeIfPresent(flexSSOAdminUnit, forKey: .flexSSOAdminUnit)
        try container.encodeIfPresent(flexSSOModeratorCostCents, forKey: .flexSSOModeratorCostCents)
        try container.encodeIfPresent(flexSSOModeratorUnit, forKey: .flexSSOModeratorUnit)
        try container.encodeIfPresent(isSSOBillingMonthlyActiveUsers, forKey: .isSSOBillingMonthlyActiveUsers)
    }
}

