//
// TenantBadge.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TenantBadge: Sendable, Codable, Hashable {

    public var id: String
    public var tenantId: String
    public var createdByUserId: String
    public var createdAt: Date
    public var enabled: Bool
    public var urlId: String?
    public var type: Double
    public var threshold: Double
    public var uses: Double
    public var name: String
    public var description: String
    public var displayLabel: String
    public var displaySrc: String?
    public var backgroundColor: String?
    public var borderColor: String?
    public var textColor: String?
    public var cssClass: String?
    public var veteranUserThresholdMillis: Double?
    public var isAwaitingReprocess: Bool
    public var isAwaitingDeletion: Bool
    public var replacesBadgeId: String?

    public init(id: String, tenantId: String, createdByUserId: String, createdAt: Date, enabled: Bool, urlId: String? = nil, type: Double, threshold: Double, uses: Double, name: String, description: String, displayLabel: String, displaySrc: String?, backgroundColor: String?, borderColor: String?, textColor: String?, cssClass: String? = nil, veteranUserThresholdMillis: Double? = nil, isAwaitingReprocess: Bool, isAwaitingDeletion: Bool, replacesBadgeId: String? = nil) {
        self.id = id
        self.tenantId = tenantId
        self.createdByUserId = createdByUserId
        self.createdAt = createdAt
        self.enabled = enabled
        self.urlId = urlId
        self.type = type
        self.threshold = threshold
        self.uses = uses
        self.name = name
        self.description = description
        self.displayLabel = displayLabel
        self.displaySrc = displaySrc
        self.backgroundColor = backgroundColor
        self.borderColor = borderColor
        self.textColor = textColor
        self.cssClass = cssClass
        self.veteranUserThresholdMillis = veteranUserThresholdMillis
        self.isAwaitingReprocess = isAwaitingReprocess
        self.isAwaitingDeletion = isAwaitingDeletion
        self.replacesBadgeId = replacesBadgeId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case tenantId
        case createdByUserId
        case createdAt
        case enabled
        case urlId
        case type
        case threshold
        case uses
        case name
        case description
        case displayLabel
        case displaySrc
        case backgroundColor
        case borderColor
        case textColor
        case cssClass
        case veteranUserThresholdMillis
        case isAwaitingReprocess
        case isAwaitingDeletion
        case replacesBadgeId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(createdByUserId, forKey: .createdByUserId)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(enabled, forKey: .enabled)
        try container.encodeIfPresent(urlId, forKey: .urlId)
        try container.encode(type, forKey: .type)
        try container.encode(threshold, forKey: .threshold)
        try container.encode(uses, forKey: .uses)
        try container.encode(name, forKey: .name)
        try container.encode(description, forKey: .description)
        try container.encode(displayLabel, forKey: .displayLabel)
        try container.encode(displaySrc, forKey: .displaySrc)
        try container.encode(backgroundColor, forKey: .backgroundColor)
        try container.encode(borderColor, forKey: .borderColor)
        try container.encode(textColor, forKey: .textColor)
        try container.encodeIfPresent(cssClass, forKey: .cssClass)
        try container.encodeIfPresent(veteranUserThresholdMillis, forKey: .veteranUserThresholdMillis)
        try container.encode(isAwaitingReprocess, forKey: .isAwaitingReprocess)
        try container.encode(isAwaitingDeletion, forKey: .isAwaitingDeletion)
        try container.encodeIfPresent(replacesBadgeId, forKey: .replacesBadgeId)
    }
}

