//
// TOSConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TOSConfig: Sendable, Codable, JSONEncodable, Hashable {

    public var enabled: Bool?
    /** Construct a type with a set of properties K of type T */
    public var textByLocale: [String: String]?
    public var lastUpdated: Date?

    public init(enabled: Bool? = nil, textByLocale: [String: String]? = nil, lastUpdated: Date? = nil) {
        self.enabled = enabled
        self.textByLocale = textByLocale
        self.lastUpdated = lastUpdated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enabled
        case textByLocale
        case lastUpdated
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(textByLocale, forKey: .textByLocale)
        try container.encodeIfPresent(lastUpdated, forKey: .lastUpdated)
    }
}

