//
// UpdateTenantUserBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateTenantUserBody: Sendable, Codable, JSONEncodable, Hashable {

    public var username: String?
    public var displayName: String?
    public var websiteUrl: String?
    public var email: String?
    public var signUpDate: Double?
    public var verified: Bool?
    public var loginCount: Double?
    public var optedInNotifications: Bool?
    public var optedInTenantNotifications: Bool?
    public var hideAccountCode: Bool?
    public var avatarSrc: String?
    public var isHelpRequestAdmin: Bool?
    public var isAccountOwner: Bool?
    public var isAdminAdmin: Bool?
    public var isBillingAdmin: Bool?
    public var isAnalyticsAdmin: Bool?
    public var isCustomizationAdmin: Bool?
    public var isManageDataAdmin: Bool?
    public var isCommentModeratorAdmin: Bool?
    public var isAPIAdmin: Bool?
    public var moderatorIds: [String]?
    public var locale: String?
    public var digestEmailFrequency: Double?
    public var displayLabel: String?

    public init(username: String? = nil, displayName: String? = nil, websiteUrl: String? = nil, email: String? = nil, signUpDate: Double? = nil, verified: Bool? = nil, loginCount: Double? = nil, optedInNotifications: Bool? = nil, optedInTenantNotifications: Bool? = nil, hideAccountCode: Bool? = nil, avatarSrc: String? = nil, isHelpRequestAdmin: Bool? = nil, isAccountOwner: Bool? = nil, isAdminAdmin: Bool? = nil, isBillingAdmin: Bool? = nil, isAnalyticsAdmin: Bool? = nil, isCustomizationAdmin: Bool? = nil, isManageDataAdmin: Bool? = nil, isCommentModeratorAdmin: Bool? = nil, isAPIAdmin: Bool? = nil, moderatorIds: [String]? = nil, locale: String? = nil, digestEmailFrequency: Double? = nil, displayLabel: String? = nil) {
        self.username = username
        self.displayName = displayName
        self.websiteUrl = websiteUrl
        self.email = email
        self.signUpDate = signUpDate
        self.verified = verified
        self.loginCount = loginCount
        self.optedInNotifications = optedInNotifications
        self.optedInTenantNotifications = optedInTenantNotifications
        self.hideAccountCode = hideAccountCode
        self.avatarSrc = avatarSrc
        self.isHelpRequestAdmin = isHelpRequestAdmin
        self.isAccountOwner = isAccountOwner
        self.isAdminAdmin = isAdminAdmin
        self.isBillingAdmin = isBillingAdmin
        self.isAnalyticsAdmin = isAnalyticsAdmin
        self.isCustomizationAdmin = isCustomizationAdmin
        self.isManageDataAdmin = isManageDataAdmin
        self.isCommentModeratorAdmin = isCommentModeratorAdmin
        self.isAPIAdmin = isAPIAdmin
        self.moderatorIds = moderatorIds
        self.locale = locale
        self.digestEmailFrequency = digestEmailFrequency
        self.displayLabel = displayLabel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case username
        case displayName
        case websiteUrl
        case email
        case signUpDate
        case verified
        case loginCount
        case optedInNotifications
        case optedInTenantNotifications
        case hideAccountCode
        case avatarSrc
        case isHelpRequestAdmin
        case isAccountOwner
        case isAdminAdmin
        case isBillingAdmin
        case isAnalyticsAdmin
        case isCustomizationAdmin
        case isManageDataAdmin
        case isCommentModeratorAdmin
        case isAPIAdmin
        case moderatorIds
        case locale
        case digestEmailFrequency
        case displayLabel
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(username, forKey: .username)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(websiteUrl, forKey: .websiteUrl)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(signUpDate, forKey: .signUpDate)
        try container.encodeIfPresent(verified, forKey: .verified)
        try container.encodeIfPresent(loginCount, forKey: .loginCount)
        try container.encodeIfPresent(optedInNotifications, forKey: .optedInNotifications)
        try container.encodeIfPresent(optedInTenantNotifications, forKey: .optedInTenantNotifications)
        try container.encodeIfPresent(hideAccountCode, forKey: .hideAccountCode)
        try container.encodeIfPresent(avatarSrc, forKey: .avatarSrc)
        try container.encodeIfPresent(isHelpRequestAdmin, forKey: .isHelpRequestAdmin)
        try container.encodeIfPresent(isAccountOwner, forKey: .isAccountOwner)
        try container.encodeIfPresent(isAdminAdmin, forKey: .isAdminAdmin)
        try container.encodeIfPresent(isBillingAdmin, forKey: .isBillingAdmin)
        try container.encodeIfPresent(isAnalyticsAdmin, forKey: .isAnalyticsAdmin)
        try container.encodeIfPresent(isCustomizationAdmin, forKey: .isCustomizationAdmin)
        try container.encodeIfPresent(isManageDataAdmin, forKey: .isManageDataAdmin)
        try container.encodeIfPresent(isCommentModeratorAdmin, forKey: .isCommentModeratorAdmin)
        try container.encodeIfPresent(isAPIAdmin, forKey: .isAPIAdmin)
        try container.encodeIfPresent(moderatorIds, forKey: .moderatorIds)
        try container.encodeIfPresent(locale, forKey: .locale)
        try container.encodeIfPresent(digestEmailFrequency, forKey: .digestEmailFrequency)
        try container.encodeIfPresent(displayLabel, forKey: .displayLabel)
    }
}

