//
// UpdateQuestionConfigBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateQuestionConfigBody: Sendable, Codable, JSONEncodable, Hashable {

    public var name: String?
    public var question: String?
    public var helpText: String?
    public var type: String?
    public var numStars: Double?
    public var min: Double?
    public var max: Double?
    public var defaultValue: Double?
    public var labelNegative: String?
    public var labelPositive: String?
    public var customOptions: [QuestionConfigCustomOptionsInner]?
    public var subQuestionIds: [String]?
    public var alwaysShowSubQuestions: Bool?
    public var reportingOrder: Double?

    public init(name: String? = nil, question: String? = nil, helpText: String? = nil, type: String? = nil, numStars: Double? = nil, min: Double? = nil, max: Double? = nil, defaultValue: Double? = nil, labelNegative: String? = nil, labelPositive: String? = nil, customOptions: [QuestionConfigCustomOptionsInner]? = nil, subQuestionIds: [String]? = nil, alwaysShowSubQuestions: Bool? = nil, reportingOrder: Double? = nil) {
        self.name = name
        self.question = question
        self.helpText = helpText
        self.type = type
        self.numStars = numStars
        self.min = min
        self.max = max
        self.defaultValue = defaultValue
        self.labelNegative = labelNegative
        self.labelPositive = labelPositive
        self.customOptions = customOptions
        self.subQuestionIds = subQuestionIds
        self.alwaysShowSubQuestions = alwaysShowSubQuestions
        self.reportingOrder = reportingOrder
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case question
        case helpText
        case type
        case numStars
        case min
        case max
        case defaultValue
        case labelNegative
        case labelPositive
        case customOptions
        case subQuestionIds
        case alwaysShowSubQuestions
        case reportingOrder
    }

    public var additionalProperties: [String: JSONValue] = [:]

    public subscript(key: String) -> JSONValue? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(question, forKey: .question)
        try container.encodeIfPresent(helpText, forKey: .helpText)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(numStars, forKey: .numStars)
        try container.encodeIfPresent(min, forKey: .min)
        try container.encodeIfPresent(max, forKey: .max)
        try container.encodeIfPresent(defaultValue, forKey: .defaultValue)
        try container.encodeIfPresent(labelNegative, forKey: .labelNegative)
        try container.encodeIfPresent(labelPositive, forKey: .labelPositive)
        try container.encodeIfPresent(customOptions, forKey: .customOptions)
        try container.encodeIfPresent(subQuestionIds, forKey: .subQuestionIds)
        try container.encodeIfPresent(alwaysShowSubQuestions, forKey: .alwaysShowSubQuestions)
        try container.encodeIfPresent(reportingOrder, forKey: .reportingOrder)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        name = try container.decodeIfPresent(String.self, forKey: .name)
        question = try container.decodeIfPresent(String.self, forKey: .question)
        helpText = try container.decodeIfPresent(String.self, forKey: .helpText)
        type = try container.decodeIfPresent(String.self, forKey: .type)
        numStars = try container.decodeIfPresent(Double.self, forKey: .numStars)
        min = try container.decodeIfPresent(Double.self, forKey: .min)
        max = try container.decodeIfPresent(Double.self, forKey: .max)
        defaultValue = try container.decodeIfPresent(Double.self, forKey: .defaultValue)
        labelNegative = try container.decodeIfPresent(String.self, forKey: .labelNegative)
        labelPositive = try container.decodeIfPresent(String.self, forKey: .labelPositive)
        customOptions = try container.decodeIfPresent([QuestionConfigCustomOptionsInner].self, forKey: .customOptions)
        subQuestionIds = try container.decodeIfPresent([String].self, forKey: .subQuestionIds)
        alwaysShowSubQuestions = try container.decodeIfPresent(Bool.self, forKey: .alwaysShowSubQuestions)
        reportingOrder = try container.decodeIfPresent(Double.self, forKey: .reportingOrder)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("name")
        nonAdditionalPropertyKeys.insert("question")
        nonAdditionalPropertyKeys.insert("helpText")
        nonAdditionalPropertyKeys.insert("type")
        nonAdditionalPropertyKeys.insert("numStars")
        nonAdditionalPropertyKeys.insert("min")
        nonAdditionalPropertyKeys.insert("max")
        nonAdditionalPropertyKeys.insert("defaultValue")
        nonAdditionalPropertyKeys.insert("labelNegative")
        nonAdditionalPropertyKeys.insert("labelPositive")
        nonAdditionalPropertyKeys.insert("customOptions")
        nonAdditionalPropertyKeys.insert("subQuestionIds")
        nonAdditionalPropertyKeys.insert("alwaysShowSubQuestions")
        nonAdditionalPropertyKeys.insert("reportingOrder")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(JSONValue.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

