//
// UpdateTenantBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateTenantBody: Sendable, Codable, JSONEncodable, Hashable {

    public var name: String?
    public var email: String?
    public var signUpDate: Double?
    public var packageId: String?
    public var paymentFrequency: Double?
    public var billingInfoValid: Bool?
    public var billingHandledExternally: Bool?
    public var createdBy: String?
    public var isSetup: Bool?
    public var domainConfiguration: [APIDomainConfiguration]?
    public var billingInfo: BillingInfo?
    public var stripeCustomerId: String?
    public var stripeSubscriptionId: String?
    public var stripePlanId: String?
    public var enableProfanityFilter: Bool?
    public var enableSpamFilter: Bool?
    public var removeUnverifiedComments: Bool?
    public var unverifiedCommentsTTLms: Double?
    public var commentsRequireApproval: Bool?
    public var autoApproveCommentOnVerification: Bool?
    public var sendProfaneToSpam: Bool?
    public var deAnonIpAddr: Double?
    /** Construct a type with a set of properties K of type T */
    public var meta: [String: String]?
    public var managedByTenantId: String?

    public init(name: String? = nil, email: String? = nil, signUpDate: Double? = nil, packageId: String? = nil, paymentFrequency: Double? = nil, billingInfoValid: Bool? = nil, billingHandledExternally: Bool? = nil, createdBy: String? = nil, isSetup: Bool? = nil, domainConfiguration: [APIDomainConfiguration]? = nil, billingInfo: BillingInfo? = nil, stripeCustomerId: String? = nil, stripeSubscriptionId: String? = nil, stripePlanId: String? = nil, enableProfanityFilter: Bool? = nil, enableSpamFilter: Bool? = nil, removeUnverifiedComments: Bool? = nil, unverifiedCommentsTTLms: Double? = nil, commentsRequireApproval: Bool? = nil, autoApproveCommentOnVerification: Bool? = nil, sendProfaneToSpam: Bool? = nil, deAnonIpAddr: Double? = nil, meta: [String: String]? = nil, managedByTenantId: String? = nil) {
        self.name = name
        self.email = email
        self.signUpDate = signUpDate
        self.packageId = packageId
        self.paymentFrequency = paymentFrequency
        self.billingInfoValid = billingInfoValid
        self.billingHandledExternally = billingHandledExternally
        self.createdBy = createdBy
        self.isSetup = isSetup
        self.domainConfiguration = domainConfiguration
        self.billingInfo = billingInfo
        self.stripeCustomerId = stripeCustomerId
        self.stripeSubscriptionId = stripeSubscriptionId
        self.stripePlanId = stripePlanId
        self.enableProfanityFilter = enableProfanityFilter
        self.enableSpamFilter = enableSpamFilter
        self.removeUnverifiedComments = removeUnverifiedComments
        self.unverifiedCommentsTTLms = unverifiedCommentsTTLms
        self.commentsRequireApproval = commentsRequireApproval
        self.autoApproveCommentOnVerification = autoApproveCommentOnVerification
        self.sendProfaneToSpam = sendProfaneToSpam
        self.deAnonIpAddr = deAnonIpAddr
        self.meta = meta
        self.managedByTenantId = managedByTenantId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case email
        case signUpDate
        case packageId
        case paymentFrequency
        case billingInfoValid
        case billingHandledExternally
        case createdBy
        case isSetup
        case domainConfiguration
        case billingInfo
        case stripeCustomerId
        case stripeSubscriptionId
        case stripePlanId
        case enableProfanityFilter
        case enableSpamFilter
        case removeUnverifiedComments
        case unverifiedCommentsTTLms
        case commentsRequireApproval
        case autoApproveCommentOnVerification
        case sendProfaneToSpam
        case deAnonIpAddr
        case meta
        case managedByTenantId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(signUpDate, forKey: .signUpDate)
        try container.encodeIfPresent(packageId, forKey: .packageId)
        try container.encodeIfPresent(paymentFrequency, forKey: .paymentFrequency)
        try container.encodeIfPresent(billingInfoValid, forKey: .billingInfoValid)
        try container.encodeIfPresent(billingHandledExternally, forKey: .billingHandledExternally)
        try container.encodeIfPresent(createdBy, forKey: .createdBy)
        try container.encodeIfPresent(isSetup, forKey: .isSetup)
        try container.encodeIfPresent(domainConfiguration, forKey: .domainConfiguration)
        try container.encodeIfPresent(billingInfo, forKey: .billingInfo)
        try container.encodeIfPresent(stripeCustomerId, forKey: .stripeCustomerId)
        try container.encodeIfPresent(stripeSubscriptionId, forKey: .stripeSubscriptionId)
        try container.encodeIfPresent(stripePlanId, forKey: .stripePlanId)
        try container.encodeIfPresent(enableProfanityFilter, forKey: .enableProfanityFilter)
        try container.encodeIfPresent(enableSpamFilter, forKey: .enableSpamFilter)
        try container.encodeIfPresent(removeUnverifiedComments, forKey: .removeUnverifiedComments)
        try container.encodeIfPresent(unverifiedCommentsTTLms, forKey: .unverifiedCommentsTTLms)
        try container.encodeIfPresent(commentsRequireApproval, forKey: .commentsRequireApproval)
        try container.encodeIfPresent(autoApproveCommentOnVerification, forKey: .autoApproveCommentOnVerification)
        try container.encodeIfPresent(sendProfaneToSpam, forKey: .sendProfaneToSpam)
        try container.encodeIfPresent(deAnonIpAddr, forKey: .deAnonIpAddr)
        try container.encodeIfPresent(meta, forKey: .meta)
        try container.encodeIfPresent(managedByTenantId, forKey: .managedByTenantId)
    }
}

