//
// UpdateEmailTemplateBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateEmailTemplateBody: Sendable, Codable, JSONEncodable, Hashable {

    public var emailTemplateId: String?
    public var displayName: String?
    public var ejs: String?
    public var domain: String?
    /** Construct a type with a set of properties K of type T */
    public var translationOverridesByLocale: [String: Dictionary]?
    /** Construct a type with a set of properties K of type T */
    public var testData: [String: JSONValue]?

    public init(emailTemplateId: String? = nil, displayName: String? = nil, ejs: String? = nil, domain: String? = nil, translationOverridesByLocale: [String: Dictionary]? = nil, testData: [String: JSONValue]? = nil) {
        self.emailTemplateId = emailTemplateId
        self.displayName = displayName
        self.ejs = ejs
        self.domain = domain
        self.translationOverridesByLocale = translationOverridesByLocale
        self.testData = testData
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case emailTemplateId
        case displayName
        case ejs
        case domain
        case translationOverridesByLocale
        case testData
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(emailTemplateId, forKey: .emailTemplateId)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(ejs, forKey: .ejs)
        try container.encodeIfPresent(domain, forKey: .domain)
        try container.encodeIfPresent(translationOverridesByLocale, forKey: .translationOverridesByLocale)
        try container.encodeIfPresent(testData, forKey: .testData)
    }
}

