//
// UpdateDomainConfigParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateDomainConfigParams: Sendable, Codable, JSONEncodable, Hashable {

    public var domain: String
    public var emailFromName: String?
    public var emailFromEmail: String?
    public var logoSrc: String?
    public var logoSrc100px: String?
    public var footerUnsubscribeURL: String?
    /** Construct a type with a set of properties K of type T */
    public var emailHeaders: [String: String]?

    public init(domain: String, emailFromName: String? = nil, emailFromEmail: String? = nil, logoSrc: String? = nil, logoSrc100px: String? = nil, footerUnsubscribeURL: String? = nil, emailHeaders: [String: String]? = nil) {
        self.domain = domain
        self.emailFromName = emailFromName
        self.emailFromEmail = emailFromEmail
        self.logoSrc = logoSrc
        self.logoSrc100px = logoSrc100px
        self.footerUnsubscribeURL = footerUnsubscribeURL
        self.emailHeaders = emailHeaders
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case domain
        case emailFromName
        case emailFromEmail
        case logoSrc
        case logoSrc100px
        case footerUnsubscribeURL
        case emailHeaders
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(domain, forKey: .domain)
        try container.encodeIfPresent(emailFromName, forKey: .emailFromName)
        try container.encodeIfPresent(emailFromEmail, forKey: .emailFromEmail)
        try container.encodeIfPresent(logoSrc, forKey: .logoSrc)
        try container.encodeIfPresent(logoSrc100px, forKey: .logoSrc100px)
        try container.encodeIfPresent(footerUnsubscribeURL, forKey: .footerUnsubscribeURL)
        try container.encodeIfPresent(emailHeaders, forKey: .emailHeaders)
    }
}

