//
// UpdateAPISSOUserData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateAPISSOUserData: Sendable, Codable, JSONEncodable, Hashable {

    public var groupIds: [String]?
    public var hasBlockedUsers: Bool?
    public var isProfileDMDisabled: Bool?
    public var isProfileCommentsPrivate: Bool?
    public var isProfileActivityPrivate: Bool?
    public var isCommentModeratorAdmin: Bool?
    public var isAdminAdmin: Bool?
    public var isAccountOwner: Bool?
    public var displayName: String?
    public var displayLabel: String?
    public var optedInSubscriptionNotifications: Bool?
    public var optedInNotifications: Bool?
    public var avatarSrc: String?
    public var loginCount: Int?
    public var createdFromUrlId: String?
    public var signUpDate: Int64?
    public var email: String?
    public var websiteUrl: String?
    public var username: String?
    public var id: String?

    public init(groupIds: [String]? = nil, hasBlockedUsers: Bool? = nil, isProfileDMDisabled: Bool? = nil, isProfileCommentsPrivate: Bool? = nil, isProfileActivityPrivate: Bool? = nil, isCommentModeratorAdmin: Bool? = nil, isAdminAdmin: Bool? = nil, isAccountOwner: Bool? = nil, displayName: String? = nil, displayLabel: String? = nil, optedInSubscriptionNotifications: Bool? = nil, optedInNotifications: Bool? = nil, avatarSrc: String? = nil, loginCount: Int? = nil, createdFromUrlId: String? = nil, signUpDate: Int64? = nil, email: String? = nil, websiteUrl: String? = nil, username: String? = nil, id: String? = nil) {
        self.groupIds = groupIds
        self.hasBlockedUsers = hasBlockedUsers
        self.isProfileDMDisabled = isProfileDMDisabled
        self.isProfileCommentsPrivate = isProfileCommentsPrivate
        self.isProfileActivityPrivate = isProfileActivityPrivate
        self.isCommentModeratorAdmin = isCommentModeratorAdmin
        self.isAdminAdmin = isAdminAdmin
        self.isAccountOwner = isAccountOwner
        self.displayName = displayName
        self.displayLabel = displayLabel
        self.optedInSubscriptionNotifications = optedInSubscriptionNotifications
        self.optedInNotifications = optedInNotifications
        self.avatarSrc = avatarSrc
        self.loginCount = loginCount
        self.createdFromUrlId = createdFromUrlId
        self.signUpDate = signUpDate
        self.email = email
        self.websiteUrl = websiteUrl
        self.username = username
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case groupIds
        case hasBlockedUsers
        case isProfileDMDisabled
        case isProfileCommentsPrivate
        case isProfileActivityPrivate
        case isCommentModeratorAdmin
        case isAdminAdmin
        case isAccountOwner
        case displayName
        case displayLabel
        case optedInSubscriptionNotifications
        case optedInNotifications
        case avatarSrc
        case loginCount
        case createdFromUrlId
        case signUpDate
        case email
        case websiteUrl
        case username
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(groupIds, forKey: .groupIds)
        try container.encodeIfPresent(hasBlockedUsers, forKey: .hasBlockedUsers)
        try container.encodeIfPresent(isProfileDMDisabled, forKey: .isProfileDMDisabled)
        try container.encodeIfPresent(isProfileCommentsPrivate, forKey: .isProfileCommentsPrivate)
        try container.encodeIfPresent(isProfileActivityPrivate, forKey: .isProfileActivityPrivate)
        try container.encodeIfPresent(isCommentModeratorAdmin, forKey: .isCommentModeratorAdmin)
        try container.encodeIfPresent(isAdminAdmin, forKey: .isAdminAdmin)
        try container.encodeIfPresent(isAccountOwner, forKey: .isAccountOwner)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(displayLabel, forKey: .displayLabel)
        try container.encodeIfPresent(optedInSubscriptionNotifications, forKey: .optedInSubscriptionNotifications)
        try container.encodeIfPresent(optedInNotifications, forKey: .optedInNotifications)
        try container.encodeIfPresent(avatarSrc, forKey: .avatarSrc)
        try container.encodeIfPresent(loginCount, forKey: .loginCount)
        try container.encodeIfPresent(createdFromUrlId, forKey: .createdFromUrlId)
        try container.encodeIfPresent(signUpDate, forKey: .signUpDate)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(websiteUrl, forKey: .websiteUrl)
        try container.encodeIfPresent(username, forKey: .username)
        try container.encodeIfPresent(id, forKey: .id)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension UpdateAPISSOUserData: Identifiable {}
