//
// UpdateUserNotificationCommentSubscriptionStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateUserNotificationCommentSubscriptionStatusResponse: Sendable, Codable, Hashable {

    public enum Note: String, Sendable, Codable, CaseIterable {
        case ignoredSinceImpersonated = "ignored-since-impersonated"
        case demoNoop = "demo-noop"
    }
    public var status: APIStatus
    public var matchedCount: Int64?
    public var modifiedCount: Int64?
    public var note: Note?

    public init(status: APIStatus, matchedCount: Int64? = nil, modifiedCount: Int64? = nil, note: Note? = nil) {
        self.status = status
        self.matchedCount = matchedCount
        self.modifiedCount = modifiedCount
        self.note = note
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case matchedCount
        case modifiedCount
        case note
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(matchedCount, forKey: .matchedCount)
        try container.encodeIfPresent(modifiedCount, forKey: .modifiedCount)
        try container.encodeIfPresent(note, forKey: .note)
    }
}

