//
// UpdateAPIUserSubscriptionData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateAPIUserSubscriptionData: Sendable, Codable, JSONEncodable, Hashable {

    public var notificationFrequency: Double?

    public init(notificationFrequency: Double? = nil) {
        self.notificationFrequency = notificationFrequency
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case notificationFrequency
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(notificationFrequency, forKey: .notificationFrequency)
    }
}

