//
// UpdateNotificationBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateNotificationBody: Sendable, Codable, JSONEncodable, Hashable {

    public var viewed: Bool?
    public var optedOut: Bool?

    public init(viewed: Bool? = nil, optedOut: Bool? = nil) {
        self.viewed = viewed
        self.optedOut = optedOut
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case viewed
        case optedOut
    }

    public var additionalProperties: [String: JSONValue] = [:]

    public subscript(key: String) -> JSONValue? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(viewed, forKey: .viewed)
        try container.encodeIfPresent(optedOut, forKey: .optedOut)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        viewed = try container.decodeIfPresent(Bool.self, forKey: .viewed)
        optedOut = try container.decodeIfPresent(Bool.self, forKey: .optedOut)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("viewed")
        nonAdditionalPropertyKeys.insert("optedOut")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(JSONValue.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

