//
// UpdateHashTagBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateHashTagBody: Sendable, Codable, JSONEncodable, Hashable {

    public var tenantId: String?
    public var url: String?
    public var tag: String?

    public init(tenantId: String? = nil, url: String? = nil, tag: String? = nil) {
        self.tenantId = tenantId
        self.url = url
        self.tag = tag
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tenantId
        case url
        case tag
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tenantId, forKey: .tenantId)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(tag, forKey: .tag)
    }
}

