//
// UpdateAPIPageData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateAPIPageData: Sendable, Codable, JSONEncodable, Hashable {

    public var isClosed: Bool?
    public var accessibleByGroupIds: [String]?
    public var title: String?
    public var url: String?
    public var urlId: String?

    public init(isClosed: Bool? = nil, accessibleByGroupIds: [String]? = nil, title: String? = nil, url: String? = nil, urlId: String? = nil) {
        self.isClosed = isClosed
        self.accessibleByGroupIds = accessibleByGroupIds
        self.title = title
        self.url = url
        self.urlId = urlId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isClosed
        case accessibleByGroupIds
        case title
        case url
        case urlId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isClosed, forKey: .isClosed)
        try container.encodeIfPresent(accessibleByGroupIds, forKey: .accessibleByGroupIds)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(urlId, forKey: .urlId)
    }
}

