//
// UpdateTenantPackageBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateTenantPackageBody: Sendable, Codable, JSONEncodable, Hashable {

    public var name: String?
    public var monthlyCostUSD: Double?
    public var yearlyCostUSD: Double?
    public var maxMonthlyPageLoads: Double?
    public var maxMonthlyAPICredits: Double?
    public var maxMonthlyComments: Double?
    public var maxConcurrentUsers: Double?
    public var maxTenantUsers: Double?
    public var maxSSOUsers: Double?
    public var maxModerators: Double?
    public var maxDomains: Double?
    public var hasDebranding: Bool?
    public var hasWhiteLabeling: Bool?
    public var forWhoText: String?
    public var featureTaglines: [String]?
    public var hasFlexPricing: Bool?
    public var flexPageLoadCostCents: Double?
    public var flexPageLoadUnit: Double?
    public var flexCommentCostCents: Double?
    public var flexCommentUnit: Double?
    public var flexSSOUserCostCents: Double?
    public var flexSSOUserUnit: Double?
    public var flexAPICreditCostCents: Double?
    public var flexAPICreditUnit: Double?
    public var flexModeratorCostCents: Double?
    public var flexModeratorUnit: Double?
    public var flexAdminCostCents: Double?
    public var flexAdminUnit: Double?
    public var flexDomainCostCents: Double?
    public var flexDomainUnit: Double?
    public var flexMinimumCostCents: Double?

    public init(name: String? = nil, monthlyCostUSD: Double? = nil, yearlyCostUSD: Double? = nil, maxMonthlyPageLoads: Double? = nil, maxMonthlyAPICredits: Double? = nil, maxMonthlyComments: Double? = nil, maxConcurrentUsers: Double? = nil, maxTenantUsers: Double? = nil, maxSSOUsers: Double? = nil, maxModerators: Double? = nil, maxDomains: Double? = nil, hasDebranding: Bool? = nil, hasWhiteLabeling: Bool? = nil, forWhoText: String? = nil, featureTaglines: [String]? = nil, hasFlexPricing: Bool? = nil, flexPageLoadCostCents: Double? = nil, flexPageLoadUnit: Double? = nil, flexCommentCostCents: Double? = nil, flexCommentUnit: Double? = nil, flexSSOUserCostCents: Double? = nil, flexSSOUserUnit: Double? = nil, flexAPICreditCostCents: Double? = nil, flexAPICreditUnit: Double? = nil, flexModeratorCostCents: Double? = nil, flexModeratorUnit: Double? = nil, flexAdminCostCents: Double? = nil, flexAdminUnit: Double? = nil, flexDomainCostCents: Double? = nil, flexDomainUnit: Double? = nil, flexMinimumCostCents: Double? = nil) {
        self.name = name
        self.monthlyCostUSD = monthlyCostUSD
        self.yearlyCostUSD = yearlyCostUSD
        self.maxMonthlyPageLoads = maxMonthlyPageLoads
        self.maxMonthlyAPICredits = maxMonthlyAPICredits
        self.maxMonthlyComments = maxMonthlyComments
        self.maxConcurrentUsers = maxConcurrentUsers
        self.maxTenantUsers = maxTenantUsers
        self.maxSSOUsers = maxSSOUsers
        self.maxModerators = maxModerators
        self.maxDomains = maxDomains
        self.hasDebranding = hasDebranding
        self.hasWhiteLabeling = hasWhiteLabeling
        self.forWhoText = forWhoText
        self.featureTaglines = featureTaglines
        self.hasFlexPricing = hasFlexPricing
        self.flexPageLoadCostCents = flexPageLoadCostCents
        self.flexPageLoadUnit = flexPageLoadUnit
        self.flexCommentCostCents = flexCommentCostCents
        self.flexCommentUnit = flexCommentUnit
        self.flexSSOUserCostCents = flexSSOUserCostCents
        self.flexSSOUserUnit = flexSSOUserUnit
        self.flexAPICreditCostCents = flexAPICreditCostCents
        self.flexAPICreditUnit = flexAPICreditUnit
        self.flexModeratorCostCents = flexModeratorCostCents
        self.flexModeratorUnit = flexModeratorUnit
        self.flexAdminCostCents = flexAdminCostCents
        self.flexAdminUnit = flexAdminUnit
        self.flexDomainCostCents = flexDomainCostCents
        self.flexDomainUnit = flexDomainUnit
        self.flexMinimumCostCents = flexMinimumCostCents
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case monthlyCostUSD
        case yearlyCostUSD
        case maxMonthlyPageLoads
        case maxMonthlyAPICredits
        case maxMonthlyComments
        case maxConcurrentUsers
        case maxTenantUsers
        case maxSSOUsers
        case maxModerators
        case maxDomains
        case hasDebranding
        case hasWhiteLabeling
        case forWhoText
        case featureTaglines
        case hasFlexPricing
        case flexPageLoadCostCents
        case flexPageLoadUnit
        case flexCommentCostCents
        case flexCommentUnit
        case flexSSOUserCostCents
        case flexSSOUserUnit
        case flexAPICreditCostCents
        case flexAPICreditUnit
        case flexModeratorCostCents
        case flexModeratorUnit
        case flexAdminCostCents
        case flexAdminUnit
        case flexDomainCostCents
        case flexDomainUnit
        case flexMinimumCostCents
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(monthlyCostUSD, forKey: .monthlyCostUSD)
        try container.encodeIfPresent(yearlyCostUSD, forKey: .yearlyCostUSD)
        try container.encodeIfPresent(maxMonthlyPageLoads, forKey: .maxMonthlyPageLoads)
        try container.encodeIfPresent(maxMonthlyAPICredits, forKey: .maxMonthlyAPICredits)
        try container.encodeIfPresent(maxMonthlyComments, forKey: .maxMonthlyComments)
        try container.encodeIfPresent(maxConcurrentUsers, forKey: .maxConcurrentUsers)
        try container.encodeIfPresent(maxTenantUsers, forKey: .maxTenantUsers)
        try container.encodeIfPresent(maxSSOUsers, forKey: .maxSSOUsers)
        try container.encodeIfPresent(maxModerators, forKey: .maxModerators)
        try container.encodeIfPresent(maxDomains, forKey: .maxDomains)
        try container.encodeIfPresent(hasDebranding, forKey: .hasDebranding)
        try container.encodeIfPresent(hasWhiteLabeling, forKey: .hasWhiteLabeling)
        try container.encodeIfPresent(forWhoText, forKey: .forWhoText)
        try container.encodeIfPresent(featureTaglines, forKey: .featureTaglines)
        try container.encodeIfPresent(hasFlexPricing, forKey: .hasFlexPricing)
        try container.encodeIfPresent(flexPageLoadCostCents, forKey: .flexPageLoadCostCents)
        try container.encodeIfPresent(flexPageLoadUnit, forKey: .flexPageLoadUnit)
        try container.encodeIfPresent(flexCommentCostCents, forKey: .flexCommentCostCents)
        try container.encodeIfPresent(flexCommentUnit, forKey: .flexCommentUnit)
        try container.encodeIfPresent(flexSSOUserCostCents, forKey: .flexSSOUserCostCents)
        try container.encodeIfPresent(flexSSOUserUnit, forKey: .flexSSOUserUnit)
        try container.encodeIfPresent(flexAPICreditCostCents, forKey: .flexAPICreditCostCents)
        try container.encodeIfPresent(flexAPICreditUnit, forKey: .flexAPICreditUnit)
        try container.encodeIfPresent(flexModeratorCostCents, forKey: .flexModeratorCostCents)
        try container.encodeIfPresent(flexModeratorUnit, forKey: .flexModeratorUnit)
        try container.encodeIfPresent(flexAdminCostCents, forKey: .flexAdminCostCents)
        try container.encodeIfPresent(flexAdminUnit, forKey: .flexAdminUnit)
        try container.encodeIfPresent(flexDomainCostCents, forKey: .flexDomainCostCents)
        try container.encodeIfPresent(flexDomainUnit, forKey: .flexDomainUnit)
        try container.encodeIfPresent(flexMinimumCostCents, forKey: .flexMinimumCostCents)
    }
}

