//
// UserSearchSectionResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserSearchSectionResult: Sendable, Codable, ParameterConvertible, Hashable {

    public var section: UserSearchSection
    public var users: [UserSearchResult]

    public init(section: UserSearchSection, users: [UserSearchResult]) {
        self.section = section
        self.users = users
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case section
        case users
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(section, forKey: .section)
        try container.encode(users, forKey: .users)
    }
}

