//
// UserNotificationWriteResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserNotificationWriteResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var matchedCount: Int64
    public var modifiedCount: Int64

    public init(status: APIStatus, matchedCount: Int64, modifiedCount: Int64) {
        self.status = status
        self.matchedCount = matchedCount
        self.modifiedCount = modifiedCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case matchedCount
        case modifiedCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(matchedCount, forKey: .matchedCount)
        try container.encode(modifiedCount, forKey: .modifiedCount)
    }
}

