//
// UserNotificationCount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserNotificationCount: Sendable, Codable, JSONEncodable, Hashable {

    public var id: String
    public var count: Double
    public var createdAt: Date
    public var expireAt: Date

    public init(id: String, count: Double, createdAt: Date, expireAt: Date) {
        self.id = id
        self.count = count
        self.createdAt = createdAt
        self.expireAt = expireAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case count
        case createdAt
        case expireAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(count, forKey: .count)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(expireAt, forKey: .expireAt)
    }
}

