//
// UserReactsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserReactsResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var reacts: [String: [String: Bool]]

    public init(status: APIStatus, reacts: [String: [String: Bool]]) {
        self.status = status
        self.reacts = reacts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case reacts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(reacts, forKey: .reacts)
    }
}

