//
// UserSearchSection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum UserSearchSection: String, Sendable, Codable, CaseIterable {
    case moderators = "moderators"
    case onthispage = "onThisPage"
    case onthissite = "onThisSite"
}
