//
// UserBadgeProgress.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserBadgeProgress: Sendable, Codable, JSONEncodable, Hashable {

    public var id: String
    public var tenantId: String
    public var userId: String
    public var firstCommentId: String
    public var firstCommentDate: Date
    public var autoTrustFactor: Double?
    public var manualTrustFactor: Double?
    /** Construct a type with a set of properties K of type T */
    public var progress: [String: Double]

    public init(id: String, tenantId: String, userId: String, firstCommentId: String, firstCommentDate: Date, autoTrustFactor: Double? = nil, manualTrustFactor: Double? = nil, progress: [String: Double]) {
        self.id = id
        self.tenantId = tenantId
        self.userId = userId
        self.firstCommentId = firstCommentId
        self.firstCommentDate = firstCommentDate
        self.autoTrustFactor = autoTrustFactor
        self.manualTrustFactor = manualTrustFactor
        self.progress = progress
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case tenantId
        case userId
        case firstCommentId
        case firstCommentDate
        case autoTrustFactor
        case manualTrustFactor
        case progress
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(userId, forKey: .userId)
        try container.encode(firstCommentId, forKey: .firstCommentId)
        try container.encode(firstCommentDate, forKey: .firstCommentDate)
        try container.encodeIfPresent(autoTrustFactor, forKey: .autoTrustFactor)
        try container.encodeIfPresent(manualTrustFactor, forKey: .manualTrustFactor)
        try container.encode(progress, forKey: .progress)
    }
}

