//
// UserPresenceData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserPresenceData: Sendable, Codable, JSONEncodable, Hashable {

    public var urlIdWS: String?
    public var userIdWS: String?
    public var tenantIdWS: String?

    public init(urlIdWS: String? = nil, userIdWS: String? = nil, tenantIdWS: String? = nil) {
        self.urlIdWS = urlIdWS
        self.userIdWS = userIdWS
        self.tenantIdWS = tenantIdWS
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case urlIdWS
        case userIdWS
        case tenantIdWS
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(urlIdWS, forKey: .urlIdWS)
        try container.encodeIfPresent(userIdWS, forKey: .userIdWS)
        try container.encodeIfPresent(tenantIdWS, forKey: .tenantIdWS)
    }
}

