//
// UserBadge.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserBadge: Sendable, Codable, JSONEncodable, Hashable {

    public var id: String
    public var userId: String
    public var badgeId: String
    public var fromTenantId: String
    public var createdAt: Date
    public var type: Int
    public var threshold: Int64
    public var description: String
    public var displayLabel: String
    public var displaySrc: String?
    public var backgroundColor: String?
    public var borderColor: String?
    public var textColor: String?
    public var cssClass: String?
    public var veteranUserThresholdMillis: Int64
    public var displayedOnComments: Bool
    public var receivedAt: Date
    public var order: Int?

    public init(id: String, userId: String, badgeId: String, fromTenantId: String, createdAt: Date, type: Int, threshold: Int64, description: String, displayLabel: String, displaySrc: String? = nil, backgroundColor: String? = nil, borderColor: String? = nil, textColor: String? = nil, cssClass: String? = nil, veteranUserThresholdMillis: Int64, displayedOnComments: Bool, receivedAt: Date, order: Int? = nil) {
        self.id = id
        self.userId = userId
        self.badgeId = badgeId
        self.fromTenantId = fromTenantId
        self.createdAt = createdAt
        self.type = type
        self.threshold = threshold
        self.description = description
        self.displayLabel = displayLabel
        self.displaySrc = displaySrc
        self.backgroundColor = backgroundColor
        self.borderColor = borderColor
        self.textColor = textColor
        self.cssClass = cssClass
        self.veteranUserThresholdMillis = veteranUserThresholdMillis
        self.displayedOnComments = displayedOnComments
        self.receivedAt = receivedAt
        self.order = order
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case userId
        case badgeId
        case fromTenantId
        case createdAt
        case type
        case threshold
        case description
        case displayLabel
        case displaySrc
        case backgroundColor
        case borderColor
        case textColor
        case cssClass
        case veteranUserThresholdMillis
        case displayedOnComments
        case receivedAt
        case order
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(userId, forKey: .userId)
        try container.encode(badgeId, forKey: .badgeId)
        try container.encode(fromTenantId, forKey: .fromTenantId)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(type, forKey: .type)
        try container.encode(threshold, forKey: .threshold)
        try container.encode(description, forKey: .description)
        try container.encode(displayLabel, forKey: .displayLabel)
        try container.encodeIfPresent(displaySrc, forKey: .displaySrc)
        try container.encodeIfPresent(backgroundColor, forKey: .backgroundColor)
        try container.encodeIfPresent(borderColor, forKey: .borderColor)
        try container.encodeIfPresent(textColor, forKey: .textColor)
        try container.encodeIfPresent(cssClass, forKey: .cssClass)
        try container.encode(veteranUserThresholdMillis, forKey: .veteranUserThresholdMillis)
        try container.encode(displayedOnComments, forKey: .displayedOnComments)
        try container.encode(receivedAt, forKey: .receivedAt)
        try container.encodeIfPresent(order, forKey: .order)
    }
}

