//
// VoteBodyParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VoteBodyParams: Sendable, Codable, JSONEncodable, Hashable {

    public enum VoteDir: String, Sendable, Codable, CaseIterable {
        case up = "up"
        case down = "down"
    }
    public var commenterEmail: String?
    public var commenterName: String?
    public var voteDir: VoteDir
    public var url: String?

    public init(commenterEmail: String?, commenterName: String?, voteDir: VoteDir, url: String?) {
        self.commenterEmail = commenterEmail
        self.commenterName = commenterName
        self.voteDir = voteDir
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case commenterEmail
        case commenterName
        case voteDir
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(commenterEmail, forKey: .commenterEmail)
        try container.encode(commenterName, forKey: .commenterName)
        try container.encode(voteDir, forKey: .voteDir)
        try container.encode(url, forKey: .url)
    }
}

