//
// VoteDeleteResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VoteDeleteResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: APIStatus
    public var wasPendingVote: Bool?

    public init(status: APIStatus, wasPendingVote: Bool? = nil) {
        self.status = status
        self.wasPendingVote = wasPendingVote
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case wasPendingVote
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(wasPendingVote, forKey: .wasPendingVote)
    }
}

