//
// VoteResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VoteResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var status: VoteResponseStatus
    public var voteId: String?
    public var isVerified: Bool?
    public var user: VoteResponseUser?
    public var editKey: String?

    public init(status: VoteResponseStatus, voteId: String? = nil, isVerified: Bool? = nil, user: VoteResponseUser? = nil, editKey: String? = nil) {
        self.status = status
        self.voteId = voteId
        self.isVerified = isVerified
        self.user = user
        self.editKey = editKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case voteId
        case isVerified
        case user
        case editKey
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(voteId, forKey: .voteId)
        try container.encodeIfPresent(isVerified, forKey: .isVerified)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encodeIfPresent(editKey, forKey: .editKey)
    }
}

