//
// VoteResponseUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VoteResponseUser: Sendable, Codable, JSONEncodable, Hashable {

    public var sessionId: String?

    public init(sessionId: String? = nil) {
        self.sessionId = sessionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sessionId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(sessionId, forKey: .sessionId)
    }
}

